### ISSUE TITLE
Discord app not show all folders in home

### ISSUE THREAD

**Issue by trprado** [flathub/com.discordapp.Discord#10]
I installed discord app using flatpack with the option --user. When I selected to send files in chat, the file dialog not show all my folders in home folder, only the pictures folder, the videos folder and all my root system.

Is it normal or is a bug in configurations?

**Comment by TingPing** [comment]
This is on purpose to be somewhat sandboxed. You can do `flatpak override --user --filesystem=home com.discordapp.Discord` (and restart the app).

**Comment by trprado** [comment]
Thanks for fast reply. This solution solve my problem.

**Comment by jadbox** [comment]
This doesnt seem to work anymore as a work around.

**Comment by TingPing** [comment]
Nothing changed AFAIK.

**Comment by rigred** [comment]
Worked fine for me. 
```
flatpak override --user --filesystem=home com.discordapp.Discord
```
But this is essential for being able to upload files, without it you just get a blank window.
It should be documented somewhere.

**Comment by Melvasul** [comment]
Why isn't this integrated by default in the Discord app?
I've seen that nowadays most of the apps from flatpak have no problem accessing all your "home" files and folders (thinking about vscode, vlc, LibreOffice, telegram, drawio, steam) whereas Discord still has this problem.

**Comment by TingPing** [comment]
There is no right answer, the permission is "Make the package insecure?" so either it is an opt-in or opt-out.

**Comment by Iey4iej3** [comment]
> Why isn't this integrated by default in the Discord app?
> I've seen that nowadays most of the apps from flatpak have no problem accessing all your "home" files and folders (thinking about vscode, vlc, LibreOffice, telegram, drawio, steam) whereas Discord still has this problem.

`Discord` is not open-source and I think that it is good to be sandboxed so that it cannot access arbitrary files and folders without explicit permission from the user.
