### ISSUE TITLE
Update necessary

### ISSUE THREAD

**Issue by bjorn3** [flathub/com.discordapp.Discord#102]
```
[Modules] Host update is available. Manual update required!
```

**Comment by Fuseteam** [comment]
confirmed current discord version is 0.11
flatpak ships 0.10

**Comment by markusgod** [comment]
https://github.com/flathub/com.discordapp.Discord/pull/100

**Comment by Fuseteam** [comment]
just saw that

**Comment by lionirdeadman** [comment]
#100 was merged, can be closed now.

**Comment by bjorn3** [comment]
That was quick, thanks!

**Comment by Fuseteam** [comment]
no updates seen yet, how long does it typically take?

**Comment by BrainBlasted** [comment]
Have to wait for the build to be published: https://flathub.org/builds/#/apps/com.discordapp.Discord

**Comment by Fuseteam** [comment]
thanks for the link

**Comment by kedodrill** [comment]
@lionirdeadman Thanks for the quick update! Looks like the builds are finished - updating now :)
