### ISSUE TITLE
Inconsistent emoji

### ISSUE THREAD

**Issue by ghost** [flathub/com.discordapp.Discord#106]
Possibly related to #27 ?

Is there a way to make emoji display consistent? Currently emojis show up in two different fonts depending on their locations in the UI.

![1](https://user-images.githubusercontent.com/69660487/90210075-aada3100-de1f-11ea-9fca-fa31b8f7c0b1.png)

**Comment by Fuseteam** [comment]
i believe that's the way discord works, emoji's in the chat isn't using you're system font and is instead rendered using images. they extended this further to allow custom emojis and animated emoji's.

**Comment by pgqz53** [comment]
So is there a way to make the channel name display consistent with the rest of the system (window title bar, for example)?
![image](https://user-images.githubusercontent.com/69660487/90554100-f9911d80-e1c7-11ea-86d6-3ba3a0e7e6ec.png)

**Comment by Fuseteam** [comment]
that is just your font, you will have to change your font inside of the snap i'm not sure how to do that

**Comment by pgqz53** [comment]
Yes, I'm aware this is a font issue, and I am looking for a solution. This is not a snap, please read the repo name before posting.

**Comment by Fuseteam** [comment]
ah oops still means you need to add the font to the flatpak somehow.
i knew something was off when i said snap. fwiw i saw a similar issue with snap a while ago, perhaps it can serve as a reference to a solution with flatpak

**Comment by H4ndrycx** [comment]
am I having the same problem any solution?

**Comment by Fuseteam** [comment]
@H4ndrycx please read back a few messages, it may be point out a solution it might provide hints to a possible solution

**Comment by pgqz53** [comment]
So, I don't have a solution yet, but I want to provide more context first. The outline emoji font that I'm trying to get rid of is called [https://fontlibrary.org/en/font/symbola](Symbola), which can be uninstalled by removing the `gdouros-symbola-fonts` package on Fedora. You'll have to figure out how to remove this font on other distros by yourself. This will force the client to use something better, it's still not 100% consistent with what Gnome uses (for the window title bar), but it already looks better to me.

**Comment by tiritto** [comment]
Recently I've decided to give flatpak a chance and start using flatpak apps. As soon as I've logged into my Discord account I got disappointed with all missing emojis that literally cause many channels to look simply out of place, since properly rendered emojis are supposed to have fixed size within the same font. While it doesn't break anything important, it really does feel like using an inferior app. Hopefully someone finds a nice and easy solution to this problem.

**Comment by Fuseteam** [comment]
@tiritto that's a font issue not a issue with this flatpak perse, are able to reproduce the issue with the deb version?

**Comment by tiritto** [comment]
Reproduce the issue with the deb version? No, not at all. In fact, using deb version is working just perfectly fine unlike flatpak version.
![Zrzut ekranu z 2020-10-31 00-16-54](https://user-images.githubusercontent.com/5196829/97772169-ba2a6a00-1b44-11eb-9066-7a669bbae910.png)
Here you can see the difference. Flatpak on the left side and .deb version on the right side. Both running at the same time on the same system. I also added a red line that shows how much of a difference right emojis might cause in terms of alignment.

**Comment by Fuseteam** [comment]
huh looks like the flatpak isn't using your system font for some reason
