### ISSUE TITLE
Discord can't detect running games like OpenTTD or games running through Steam

### ISSUE THREAD

**Issue by Zachs-Kappler** [flathub/com.discordapp.Discord#11]
I'm not sure what is preventing this from happening, but Discord can't figure out when a game is running like the regular deb/rpm version can. Is it possible to expose the running process list to this version of Discord in Flatpak, or will I have to install the packaged one to have that feature?

All that is listed in the list of games to add is flatpak-bwrap.

**Comment by TingPing** [comment]
Flatpaks run in their own isolated namespace so that is to be expected and I don't believe can be reasonably worked around.

**Comment by Zachs-Kappler** [comment]
Well that's unfortunate. I really like what Flatpak and Flathub are doing for software management and compatibility, so I guess Discord will have to be the odd one out for now. Thanks for the response.

I guess this issue can be closed if a workaround isn't possible.

**Comment by jython234** [comment]
There actually is a solution to this, works on Manjaro 17.1.5 and allows Discord to see processes.
You can modify the sandbox by running ```flatpak run --filesystem=/proc com.discordapp.Discord```
That will launch discord and allow it to see the system processes.

If you want to make it permanent, you can run ```flatpak override --user --filesystem=/proc com.discordapp.Discord``` to permanently modify the sandbox, and allow discord to see the processes when launched normally through your DE or in terminal. You can override the sandbox system-wide by omitting the ```--user``` flag and running as root.

**Comment by TingPing** [comment]
I'm honestly surprised that would work.

**Comment by TingPing** [comment]
Actually it *shouldn't* work: https://github.com/flatpak/flatpak/blob/b66243e26dcc8fc545683f3849cda04d7ba81d12/common/flatpak-context.c#L1735-L1738

What is your `flatpak` version @jython234?

**Comment by jython234** [comment]
Whichever version currently ships with Manjaro, unable to access my
computer currently.

**Comment by jython234** [comment]
@TingPing I have ```Flatpak 0.10.3```. Looks like that's the latest stable version.

**Comment by kparal** [comment]
> You can modify the sandbox by running flatpak run --filesystem=/proc com.discordapp.Discord
> That will launch discord and allow it to see the system processes.

I can confirm this works on Fedora 27. Awesome!

> Actually it shouldn't work:

Why don't we **not** fix the bug until flatpak can offer the same functionality natively and securely? :)

**Comment by TingPing** [comment]
> Why don't we not fix the bug until flatpak can offer the same functionality natively and securely? :)

Well exposing the host `/proc` *probably* isn't secure (but this flatpak isn't secure in general). We'll see if it is a bug.

**Comment by ullebe1** [comment]
For me it seems like the above workaround no longer works, using Flatpak 1.7.2.

**Comment by TheFlagCourier** [comment]
As ullebe1 said, this workaround no longer _works around_ the issue. Using Flatpak 1.6.3 (Fedora 32 Beta)

The only programs it seems to pick up are within it's sandbox.
![image](https://user-images.githubusercontent.com/2712890/79860908-227be000-8399-11ea-9004-68e1c147ae70.png)

**Comment by lolrepeatlol** [comment]
Is there no updated solution for this still?

**Comment by Fuseteam** [comment]
there is no solution flatpaks are too isolated for this feature to be enabled

**Comment by gregorywaynepower** [comment]
On Pop_OS, don't use the Flatpack version, run the Debian install and you should be good to go.
