### ISSUE TITLE
Hardware video encoding does not appear to be supported

### ISSUE THREAD

**Issue by aidalgol** [flathub/com.discordapp.Discord#114]
Discord does not output any logging to let me be certain, but based on the drop in framerate when streaming games through the flathub version of Discord that does not occur when streaming with the upstream version, it seems that flathub Discord is unable to use hardware encoding for streaming.

**Comment by TingPing** [comment]
Considering we don't build any encoder ourself I assume its bundling something. Needs more info.

**Comment by aidalgol** [comment]
Let me know if there is any information you need from me.  I saw nothing on stdout about codecs when I ran Discord to stream.

**Comment by vchernin** [comment]
To see actual hardware encoder usage, you should look at metrics from your GPU. If on Intel you should be able to install `intel-gpu-tools` and run `sudo intel_gpu_top`. If on AMD you can try `radeontop`. Not sure about Nvidia.

I've never seen actual hardware encoder functioanlity in any Chromium build or Electron app on Linux. Even hardware video decoding doesn't necessarily work reliably. I am not sure if Discord uses a custom implementation or not, if they use WebRTC the best way would probably be to get hardware encoding working by default in Chromium WebRTC, which isn't exactly easy. I don't see any mentions of encoding in [Chromium's Arch Wiki page](https://wiki.archlinux.org/title/Chromium#Hardware_video_acceleration).

**Comment by guihkx** [comment]
Unless this issue is specific to the Flatpak package (which I doubt), there's really no point in keep it open.

In any case, let me know if I'm mistaken, and I'll reopen this.

**Comment by aidalgol** [comment]
Definitely not Flatpak-specific.  I have since tried this with the official packages, and it just does not seem to support hardware encoding on Linux.  Apologies for not updating this issue earlier; I had completely forgotten about it.
