### ISSUE TITLE
Sandbox fails to run

### ISSUE THREAD

**Issue by rizakara** [flathub/com.discordapp.Discord#118]
I encountered a gtk module loading issue on pop os 20.10. When i start discord just an empty gtk page appers and nothing happens then. I installed Discord yesterday via flatpak and all packages are up to date. I will attach screenshots.
![Screenshot from 2020-11-23 23-28-24](https://user-images.githubusercontent.com/17912708/100012809-ebfdbc00-2de4-11eb-9296-749689b555a2.png)
![image](https://user-images.githubusercontent.com/17912708/100013104-5b73ab80-2de5-11eb-9ed2-faa08b489f1c.png)

**Comment by TingPing** [comment]
Maybe @refi64 can help debug the zypak failure.

**Comment by refi64** [comment]
This error generally means that Discord itself died, so Zypak exits with it. (I made it a debug log in the next release, since it looks a lot like a Zypak error and causes quite a bit of confusion.)

**Comment by Mershl** [comment]
Todays update has fixed the gtk startup issue for me.
