### ISSUE TITLE
Spell Check Hack?

### ISSUE THREAD

**Issue by cerulis64** [flathub/com.discordapp.Discord#119]
Discord's Linux tar.gz does not include spell check, but I found that on Archlinux, using system electron (using [this AUR package](https://aur.archlinux.org/packages/discord_arch_electron/)) somehow allowed spell check to work (hunspell may be required).

Is it possible to do something similar in the Flatpak package to add spell check?

**Comment by TingPing** [comment]
I don't plan on having this use any electron version than the one it ships with as its just hard to support that.

**Comment by cerulis77** [comment]
Fair.
Will a pull request adding that feature be accepted?

**Comment by TingPing** [comment]
Yes that would be great.

**Comment by TingPing** [comment]
No, I don't think its supportable long term.

**Comment by anthr76** [comment]
@cerulis64 care to elaborate how that may not be supportable long term. AFAIK Arch has been using it for years.

Regardless it looks like Discord ptb got native spell checking.

**Comment by cerulis64** [comment]
@anthr76 it is not the official Discord build of electron and @TingPing did not want to package an unofficial build.

from my point of view, using an unofficial build is just a slight inconvenience as that means that electron would have to be upgraded in the package along with Discord itself. other than that, its completely fine. i doubt there will be compatibility issues or anything.

closing this issue for now since spell checking seems to be on ptb.

**Comment by lionirdeadman** [comment]
Worth mentioning but spell checking is now on the stable build with the release of 0.13
