### ISSUE TITLE
Discord 0.0.13 is out

### ISSUE THREAD

**Issue by fredoche** [flathub/com.discordapp.Discord#122]
Hi,

I'm just letting you know that Discord 0.0.13 is out, and the previous version doesn't start anymore.
If one would kindly build & update the flatpak, that would be great.

Thanks!

**Comment by fredoche** [comment]
I ran the suggested line and it works for me.

**Comment by TheGreatestJannet** [comment]
Shouldn't this stay open until #121 has been merged?

**Comment by lionirdeadman** [comment]
It has been merged.
