### ISSUE TITLE
I'm locked out of launching Discord via the Flatpak

### ISSUE THREAD

**Issue by cobalt2727** [flathub/com.discordapp.Discord#123]
Every time I try do, I'm met with this:
[https://i.imgur.com/nhpdtM0.png](url)
I'd rather avoid using the .deb so that I can keep automatically updating it through Flatpak. So I guess the solution here would be to just ensure that the Flatpak build gets updated with each new release faster?

**Comment by lionirdeadman** [comment]
Well, we do our best to keep it updated as soon as possible. We unfortunately have no way to know when updates will be launched although we have a bot checking if the download link offers a newer version which you can see has happened [here](https://github.com/flathub/com.discordapp.Discord/pull/121). It's been merged, it should be published any moment now.

Sorry for the inconvenience.

**Comment by cobalt2727** [comment]
Ah, my bad. I just kind of assumed this was official, actually! Probably should have checked that first...

**Comment by lionirdeadman** [comment]
> Ah, my bad. I just kind of assumed this was official, actually! Probably should have checked that first...

Nah, it's just me and some volunteers repackaging the tarball while Discord pushes updates whenever they want and we try to do it as fast as possible to avoid people being locked out. Really wish they didn't lock people out...

**Comment by cobalt2727** [comment]
Gotta say, you guys are doing some really good work here. Thank you!
