### ISSUE TITLE
Segfaulting on Startup on Fedora 33

### ISSUE THREAD

**Issue by ManuelHu** [flathub/com.discordapp.Discord#126]
```
Discord 0.0.13
(node:4) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Failed to generate minidump.[fake-sandbox: zypak-sandbox] No data could be read (host died?)
[fake-sandbox: zypak-sandbox] Quitting Zygote...
/app/bin/discord: Zeile 8:     4 Speicherzugriffsfehler  (Speicherabzug geschrieben) env TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/discord/Discord "$@"
```

It somehow stopped working yesterday, and I do not know what I have changed at my system. If I can help debugging a bit, let me know how as I'm not quite found with how flatpak works internally...

**Comment by blueish4** [comment]
I also experienced this (also on Fedora 33)- it's probably a change that Discord pushed as an update since I hadn't changed anything either. Uninstalling and deleting the app folder then reinstalling fixed it for me.

**Comment by ManuelHu** [comment]
Yes, that worked. Thanks for the workaround!

**Comment by Fuseteam** [comment]
if this doesn't affect you anymore you may want to close this issue, if the problem cannot be reproduced it cannot be fixed either
