### ISSUE TITLE
No icon on FlatHub !

### ISSUE THREAD

**Issue by Nokia808** [flathub/com.discordapp.Discord#127]
Hi. I detected that there is no icon for your application in FlatHub when viewed from within a category - see attached screenshot bellow (red arrow):

![icons](https://user-images.githubusercontent.com/25375330/103275699-a6707800-49bc-11eb-8e7a-3a88419b2a13.png)

**Comment by lionirdeadman** [comment]
I have noticed this however the data seems correct, see : https://github.com/flathub/com.discordapp.Discord/blob/master/com.discordapp.Discord.appdata.xml#L10

Therefore, I think it might just be a Flathub probem. Gonna hop on the matrix channel.
