### ISSUE TITLE
What level of filesystem access should Discord have?

### ISSUE THREAD

**Issue by lionirdeadman** [flathub/com.discordapp.Discord#134]
After further testing, the file portal hack made by zypak can't work for everything and therefore breaks things like changing profile pictures because they don't work the same way and it is quite hard to deal with because of ABI incompatibility.

With this option being taken out, I believe I'll be giving discord full read-only home access (`home:ro`) and read-write download folder access (`xdg-download:rw`). This avoids the security issues, takes care of usability concerns but doesn't take care of the privacy concerns.

Those in favour should give this message a thumbs up, those who are not can thumbs down this message. I'll leave it for two weeks. Feel free to comment to clarify your position, please avoid debating.

In the meanwhile, the default will stay the same as it was. Obviously, whichever the choice ends up being, people can change the permissions.

**Comment by mindinsomnia** [comment]
I support this change.

For those who are concerned about privacy, perhaps there could be instructions provided for changing the default permissions to be more restrictive?

**Comment by lionirdeadman** [comment]
Instructions will be given in the README of this repository very shortly.

**Comment by geekley** [comment]
Entire home is too much. As a developer, I have even executable programs inside home.
I think you should at the very least exclude (`--nofilesystem=...`) `xdg-config`, `xdg-cache`, `xdg-data`.
Or better, include only `xdg-desktop, xdg-documents, xdg-download, xdg-music, xdg-pictures, xdg-public-share, xdg-videos, xdg-templates`, maybe with `:ro` on most of them.

**Comment by ssokolow** [comment]
If `home:ro` wins out, at *least* go take a look at the blacklist entries in the `/etc/firejail/disable-secret.inc` and `/etc/firejail/disable-common.inc` rulesets from [Firejail](https://github.com/netblue30/firejail).

(Bear in mind that, on my system, there are roughly a hundred of them, some are wildcards, and they're not exhaustive. That's why you whitelist access to home directories.)

**Comment by refi64** [comment]
It's not possible have any form of exclusions from within filesystem permissions, i.e. when you grant `filesystem=...`, you cannot block out subdirectories of the granted path. This means that "home but no access to dot directories" is not possible; you'd have to simply `nofilesystem=home` and then manually add all the subdirectories you want.

**Comment by soredake** [comment]
> home:ro

Saving files from discord will be impossible, so at least xdg-download:rw is needed.

**Comment by lionirdeadman** [comment]
> Saving files from discord will be impossible, so at least xdg-download:rw is needed.
Ah, right, I forgot about that. I'll add that.

**Comment by geekley** [comment]
Oh, so that works only on user overrides? That's a bummer...
Then I guess the best is adding xdg-* from my comment above. I actually don't mind those folders being rw. For example, I tend to use desktop as a replacement for donwloads.

**Comment by lionirdeadman** [comment]
The main problem with giving only `xdg-*` is that any folder created in home outside of those will not be accessible. `~/Projects` or `~/Games` for example. I know people have been frustrated with that in the past. The security concerns though do bother me quite a bit and I was hoping exclusive would work but seems that's not the case. :disappointed:

**Comment by geekley** [comment]
> I was hoping exclusive would work but seems that's not the case.

Have you tried something like `--filesystem=!~/.*`?

**Comment by refi64** [comment]
Actually, amendment, you *can* use nofilesystem on subdirectories, it's `persist` that doesn't work, sorry for any confusion that causes.

However, globs are not supported at all:

```
flatpak run --command=bash --filesystem=home --nofilesystem='~/.*' org.freedesktop.Platform//20.08
[📦 org.freedesktop.Platform ~]$ file ~/.ssh/config
/var/home/ryan/.ssh/config: ASCII text
[📦 org.freedesktop.Platform ~]$ 
```

**Comment by geekley** [comment]
Ok, so can we all agree that at least `xdg-config, xdg-cache, xdg-data` should be excluded if home ends up being added?

**Comment by lionirdeadman** [comment]
I will go down the rabbit hole of which directories need to be excluded in the PR if `home:ro` + `xdg-download:rw` wins, no worries on that.

**Comment by lionirdeadman** [comment]
The PR is up for those who want to check for blacklisting missing from it.

**Comment by ssokolow** [comment]
Here are a few reasons that come to mind for why I'll be sticking to in-browser Discord unless it's possible to use Flatseal to switch the Flatpak back to whitelist-based sandboxing:

* For historical reasons relating to my hierarchy of different types of automated backup, my KeePass2 password database, though encrypted, is still inside xdg-documents.
* Secrets for websites I run are found in `~/src` (which, again for historical reasons which I haven't fixed yet, is a symlink to `~/Documents/Critical/src`) and SQL dumps for things like my WordPress blog can be found in `~/.backups`.
* It's not standard as far as I remember, and my rcfiles are on GitHub but, if you're trying to hide people's rcfiles, I should mention that I can't be the only one who created something like a `~/.bash_completion.d`. (Hell, most of my rcfiles are in `~/.common_sh_init`, in a form both bash and zsh can understand.)
* I have an unsorted dump of `$HOME` from my previous machine in a folder with a name like `~/OldHome` in my home directory. (Not actually what it's called. No need to make it *too* easy for bad actors.)
* For historical reasons the auth token I use for GitHub was moved from `.gitconfig` to a separate file your blacklist couldn't possibly know about, included using `[include]`.
* The location of credentials for publishing to crates.io (the Rust package repository) defaults to `~/.cargo/credentials.toml`, but is actually `$CARGO_HOME/credentials.toml` and it wouldn't surprise me if the same concern exists for other language repository systems.

**Comment by lionirdeadman** [comment]
> Here are a few reasons that come to mind for why I'll be sticking to in-browser Discord unless it's possible to use Flatseal to switch the Flatpak back to whitelist-based sandboxing:

I believe I've made it very clear that you can change the permissions yourself either using flatpak override manually or using a GUI like Flatseal so you can add blacklists yourself or remove the $HOME whitelist that I've made only with the blacklists and add back only the directories you want. You can even only give it `~/Share` or something if you want.

> It's not standard as far as I remember, and my rcfiles are on GitHub but, if you're trying to hide people's rcfiles, I should mention that I can't be the only one who created something like a ~/.bash_completion.d. (Hell, most of my rcfiles are in ~/.common_sh_init, in a form both bash and zsh can understand.)

I did this to avoid someone from escaping the sandbox this way but I've just realised this isn't neccessary because we already give $HOME read-only. I'll keep them blacklisted anyhow though.

> ...plus all the stuff you missed that I mentioned on the PR. I wouldn't want to play whac-a-mole with Flatpak permissions every time I start learning a new language with a "publish package to repository" client that needs to store credentials.

I totally understand this concern and I'm trying my best to add all of them ideally but it is a whack-a-mole game in the end. I still think that the improvement first impression for people using Discord will be better. I have had many many people complain about the fact that they can't share files from anywhere in their HOME directory so I did this poll.

Note that I personally am not a fan of this whack-a-mole game but if people want $HOME access then it's the best I can do unfortunately because I don't really want to be annoying to people using Discord through FlatHub. Ideally, Electron would have the native file picker but it's just not there yet and we tried to hack something to make it work with current electron using Zypak but it just didn't work.

**Comment by lionirdeadman** [comment]
I've decided this is no longer what I want to do. I'll wait for Discord to push for newer Electron with the file portal. Sorry to those I'm disappointing.
