### ISSUE TITLE
Any way to launch discord app upon logon minimized?

### ISSUE THREAD

**Issue by ACodingGenie** [flathub/com.discordapp.Discord#136]
I am currently using GNOME Tweaks to autostart the app on system login but is there a parameter I can pass in to the startup command to make it start minimized? Thanks.

**Comment by lionirdeadman** [comment]
I believe `flatpak run com.discordapp.Discord --start-minimized` should work. It seems to still flash for a second before minimizing though. I think this is just a discord bug though.

Hope this works for you.

**Comment by ACodingGenie** [comment]
It does work indeed. Better than having to close it myself every time. Thank you!

**Comment by yaroslavrick** [comment]
cd ~/.config/autostart       
add to org.telegram.desktop.desktop file in exec: :
 --start-minimized

You wil have something like this:

[Desktop Entry]
Type=Application
Name=org.telegram.desktop
Exec=flatpak run --command=telegram-desktop org.telegram.desktop -workdir /home/yaroslav/.var/app/org.telegram.desktop/data/TelegramDesktop/ -autostart
X-Flatpak=org.telegram.desktop


It still need pair of seconds to minimize, but it works
