### ISSUE TITLE
Doesnt stop running when Visual Studio closes

### ISSUE THREAD

**Issue by MillzyG** [flathub/com.discordapp.Discord#139]

**Comment by Fuseteam** [comment]
wait wat? somehow closing visual studio closes discord? can you provide more details?

**Comment by MillzyG** [comment]
the rich presence stays when I close Visual Studio
its probably a bug on discords end as it resolved when I reloaded discord, but this doesn't happen with any other RPC I use

**Comment by lionirdeadman** [comment]
If this doesn't happen with any other programs with RPC then I won't consider it related to this package. Feel free to re-open if you think this is related to the package.
