### ISSUE TITLE
Login and known login location is lost on upgrades

### ISSUE THREAD

**Issue by ell1e** [flathub/com.discordapp.Discord#140]
The login appears to be lost when the flatpak itself upgrades and it counts as a new login location. This is bad because new login location even though it is the same machine, this means going through discord's security e-mail system which they sadly seem to do a very bad job at running. (Basically verification e-mails tend to arrive super late with a way too short timeout, sometimes making logging in again literally impossible for a while.) At the very least, even if I need to login again, the identification as the same machine / login location should be kept.

**Comment by lionirdeadman** [comment]
Sorry for lateness. What system is this running on? I've never experienced this nor heard anyone experience this.

**Comment by guihkx** [comment]
Closing due to lack of response.

Side note: I also never experienced this, even after upgrading this Flatpak package for years.
