### ISSUE TITLE
Couldn't connect to Discord via RPC: Error: RPC_CONNECTION_TIMEOUT

### ISSUE THREAD

**Issue by RenardNocturne** [flathub/com.discordapp.Discord#148]
My error: Couldn't connect to Discord via RPC: Error: RPC_CONNECTION_TIMEOUT
Not a connection problem please help.

![image_2021-05-09_232731](https://user-images.githubusercontent.com/75169150/117587412-20103380-b11e-11eb-8a41-b0eceae3dff5.png)

**Comment by lionirdeadman** [comment]
What application is trying to reach Discord?

**Comment by RenardNocturne** [comment]
Visual Studio Code with the extension "Discord Presence" by Crawl

**Comment by RenardNocturne** [comment]
Problem solved thanks.
