### ISSUE TITLE
Feasibility of using upstream electron similar to AUR package

### ISSUE THREAD

**Issue by anthr76** [flathub/com.discordapp.Discord#151]
Hello

ArchLinux AUR has seemed to workaround some discord's shortcomings with electron/screen sharing with pipewire etc.

They're using the system's electron. Is it possible we can do something like that with the flatpak?

They unpack the asar

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=discord_arch_electron#n36

```bash
  install -d "$pkgdir"/usr/lib/$_pkgname

  # HACKS FOR SYSTEM ELECTRON
  asar e Discord/resources/app.asar Discord/resources/app
  rm Discord/resources/app.asar
  sed -i "s|process.resourcesPath|'/usr/lib/$_pkgname'|" Discord/resources/app/app_bootstrap/buildInfo.js
  sed -i "s|exeDir,|'/usr/share/pixmaps',|" Discord/resources/app/app_bootstrap/autoStart/linux.js
  asar p Discord/resources/app Discord/resources/app.asar --unpack-dir '**'
  rm -rf Discord/resources/app
```

I have not tested myself but I have read/ and heard doing something like this allows you to use Pipewire and screen share properly

**Comment by carlocastoldi** [comment]
As far as I tested `discord_arch_electron` doesn't make it possible to screenshare using pipewire. If you hope to enable screensharing with this proposal, I highly doubt it will.

P.S. tested with:
```bash
❯ cat /usr/bin/discord
#!/bin/sh
exec electron --enable-features=WebRTCPipeWireCapturer --enable-features=UseOzonePlatform --enable-gpu --ozone-platform=wayland /usr/lib/discord/app.asar $@
```

**Comment by lionirdeadman** [comment]
I believe I've said this before but not sure where. Doing this might count as a client modification and I don't want to cross that line.

**Comment by SystemlessDev** [comment]
I'm necroposting a bit but doing this would absolutely be considered a client mod. Any modifications to discord, or any of its components, is against their tos.

**Comment by anthr76** [comment]
I mean the options Discord gives it's paying Linux customers are abysmal but if upstream has no desire I'm going to go ahead and close the issue.

**Comment by lionirdeadman** [comment]
I still believe that it would be a violation but I'd like to keep this open because I've sent an email about it to Discord to see if this breaks their policies or not.

**Comment by anthr76** [comment]
Thanks! I'll keep an eye and would be happy to help if we get a response back..

**Comment by lionirdeadman** [comment]
We already contacted them previously to allow the distribution of the binary. I recently emailed them about how they handled updates but they said their team and the infra was too small to do the things I wanted (either email me or check flatpak for updates instead of their current prompt)

**Comment by thegarlynch** [comment]
Just say fuck it and break TOS ? it is only support for it. it wouldn't be capital cost for them.

**Comment by guihkx** [comment]
In recent times, Discord has greatly improved on this specific scenario.

For instance, Discord 0.70.0 ([released yesterday](https://github.com/flathub/com.discordapp.Discord/pull/449)), already includes Electron 32.0.0 (with Chromium 128), which is the [most recent](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline) stable version of Electron today.

For that reason, my personal judgment is that we don't need this anymore. If any collaborator disagrees, feel free to re-open.
