### ISSUE TITLE
Consider using SKIP_HOST_UPDATE to disable the host update check at startup

### ISSUE THREAD

**Issue by ahayzen** [flathub/com.discordapp.Discord#154]
The snap of discord has enabled `SKIP_HOST_UPDATE` from the pull request description "Discord has two updaters. We disable the one that blocks launching discord when upstream releases a new version. This allows the app to continue functioning in such situations." ( https://github.com/snapcrafters/discord/pull/109 ).

Can the same be done to the flatpak, so that users can keep using discord and they aren't blocked by the dialog asking them to update the deb (which they haven't installed) ?  It appears that a script would just need to set `SKIP_HOST_UPDATE = true` into `~/.var/app/com.discordapp.Discord/config/discord/settings.json` .

**Comment by lionirdeadman** [comment]
Thank you very much for telling me. I find it very annoying that Discord didn't tell me about it when I emailed them on the 26th when I told them about my struggles with the blocking updates..

I will work on this immediately.
