### ISSUE TITLE
Wrong instructions on the Rich Precense wiki entry 

### ISSUE THREAD

**Issue by Lonsfor** [flathub/com.discordapp.Discord#156]
On the instructions for [flatpak apps](https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)#flatpak-apps) says to make a link **from** `$XDG_RUNTIME_DIR/discord-ipc-0` **to** `$XDG_RUNTIME_DIR/app/com.discordapp.Discord/discord-ipc-0` but the suggested script links from `app/com.discordapp.Discord` (not `$XDG_RUNTIME_DIR/app/com.discordapp.Discord/discord-ipc-0`) to  `$XDG_RUNTIME_DIR/discord-ipc-0`. also the test doesnt seem to do anything.

**Comment by lionirdeadman** [comment]
I've made some changes which should clarify things. Please tell me what you think.

**Comment by Lonsfor** [comment]
i guess now is more consistent. but i have to ask, is there a way to make flatpak apps work with normal discord rp? i keep being asked about it and havent found a solution.

**Comment by lionirdeadman** [comment]
If you're talking about non-flatpaked Discord talking to Flatpaked programs, you'd only need to give `$XDG_RUNTIME_DIR/discord-ipc-0` access to the Flatpak programs, I believe. I think that might not work for programs which have the workaround for Discord Flatpak though.

I'm biased but I'd definitely recommend Flatpaking Discord though. :x

**Comment by Lonsfor** [comment]
by workaround you mean the script that is in the wiki entry, right? because i just tested adding `--filesystem=xdg-run/discord-ipc-0` to the finish-args and it did work. might be worth adding it to the wiki.

**Comment by lionirdeadman** [comment]
What application did you do this to?

Also, the wiki is meant for the Discord Flatpak, not for non-Flatpak Discord :p

**Comment by Lonsfor** [comment]
to org.srb2.SRB2Kart

> the wiki is meant for the Discord Flatpak, not for non-Flatpak Discord :p

but it does have instructions on setting up discord rich presence and this is part of that setup. also i think doing this little thing is better than asking people to "just change to the flatpak package bro", they are more likely to uninstall the flatpak app than to uninstall discord and reinstall it as a flatpak.

**Comment by lionirdeadman** [comment]
I can certainly understand that but it seems odd to have information that's general to all flatpaks that want to interact with something I don't ship nor encourage people to use. Does that make sense?

**Comment by Lonsfor** [comment]
if you really really really really really dont want to add it (which is a weird hill to die on since it would be like 2 lines) then there should be a disclaimer that the instructions only work for flatpak discord. cause back when i added support for drp i was under the impression that it would also work for normal discord and i only noticed when i saw people complain.

**Comment by gasinvein** [comment]
> a disclaimer that the instructions only work for flatpak discord

Isn't this obvious already? This is a wiki of an flatpak app. If you read Steam flatpak wiki, would you assume that info there applies to your distro's steam package?

**Comment by Lonsfor** [comment]
no i dont think is obvious seeing as many other apps make the same mistake including the steam one

**Comment by gasinvein** [comment]
What mistake are you talking about?

**Comment by Lonsfor** [comment]
not having support for normal discord rich presence

**Comment by JoshuaFern** [comment]
@lionirdeadman What about com.discordapp.DiscordCanary? Should that be given permissions as well?
