### ISSUE TITLE
Cant launch discord after fresh install on void linux with wayland

### ISSUE THREAD

**Issue by ZerdoX-x** [flathub/com.discordapp.Discord#160]
After installing:

```
zerdox% flatpak run com.discordapp.Discord 
settings.json doesn't yet exist, can't disable it yet
/app/bin/discord: line 10:     6 Aborted                 env TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/discord/Discord "$@"
[6 zypak-helper] Failed to connect to session bus: [org.freedesktop.DBus.Error.NotSupported] Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead                                   
[6 zypak-helper] src/helper/main.cc:40(DetermineZygoteStrategy): Assertion failed: bus
zerdox% Traceback (most recent call last):
  File "/app/bin/set-gtk-dark-theme.py", line 17, in <module>
    disp = Xlib.display.Display()
  File "/app/lib/python3.8/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/app/lib/python3.8/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/app/lib/python3.8/site-packages/Xlib/protocol/display.py", line 84, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/app/lib/python3.8/site-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "/app/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 76, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""
```

Then after some researching I tried to `export $(dbus-launch)`.
After some more and more researching:
```
zerdox% DISPLAY=":0" flatpak run com.discordapp.Discord

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/zerdox/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

bwrap: Can't find source path /tmp/.X11-unix/X0: No such file or directory
```

Then I tried to create dir and file but after this I get more and more errors...

**Comment by lionirdeadman** [comment]
Can you provide more information?

**Comment by ZerdoX-x** [comment]
> Can you provide more information?

Sorry, I accidentally pressed enter while creating issue :)
Updated my original post

**Comment by refi64** [comment]
Try starting your window manager with `dbus-run-session`, described [here](https://docs.voidlinux.org/config/session-management.html#d-bus).

**Comment by refi64** [comment]
Also you don't need the DISPLAY= var, that's only for Xorg. For some more context on the errors:

- D-Bus isn't running, but it's needed for Electron Flatpaks to work.
- D-Bus can be auto-started in certain environments, but it a) requires Xorg and b) won't actually be the behavior we want here (it would be auto-started *inside* the Flatpak, but we need it *outside*). This is why your error mentions Xorg and the `DISPLAY` environment variable.
- Setting `DISPLAY=":0"` doesn't work, because that's saying you have an Xorg session running with display ID 0. When Flatpak's bubblewrap (the sandboxing tool) trying to give the sandbox access to this Xorg display, it fails, since the display doesn't actually exist.

**Comment by ZerdoX-x** [comment]
> Try starting your window manager with `dbus-run-session`, described [here](https://docs.voidlinux.org/config/session-management.html#d-bus).

After running my wm with dbus-run-session I still get errors about display

```
zerdox% flatpak run com.discordapp.Discord                 

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/zerdox/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

settings.json doesn't yet exist, can't disable it yet
[6 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/discord/Discord --type=zygote
Traceback (most recent call last):
  File "/app/bin/set-gtk-dark-theme.py", line 17, in <module>
    disp = Xlib.display.Display()
  File "/app/lib/python3.8/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/app/lib/python3.8/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/app/lib/python3.8/site-packages/Xlib/protocol/display.py", line 84, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/app/lib/python3.8/site-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "/app/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 76, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""
Discord 0.0.15
(node:6) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
The futex facility returned an unexpected error code.
Failed to generate minidump./app/bin/discord: line 10:     6 Aborted                 env TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/discord/Discord "$@"
```

**Comment by ZerdoX-x** [comment]
> So Discord itself does *not* run natively on Wayland. 

I have found this: https://www.reddit.com/r/swaywm/comments/l2w0mo/does_anyone_know_how_to_get_discord_to_run_with/

```
$ electron --enable-features=UseOzonePlatform --enable-gpu --ozone-platform=wayland /usr/lib/discord/app.asar
```

Is it possible to do this trick with flatpak's discord?
I am being able to do this thing with vscode which also runs on electron.

**Comment by refi64** [comment]
It *should* "work", but afaik there are no plans for the Flatpak version to use anything but the Electron version that Discord ships with (IIRC it would be in a shady area of the ToS, though @lionirdeadman can correct me on this if there was also another reason).

**Comment by lionirdeadman** [comment]
The path looks wrong and that command would definitely not work in flatpak as we need zypak to run in a flatpak environment.

Also, no, I will not support this in any way until Discord answers me about the legality of doing so. see #151

**Comment by aquaspy** [comment]
I had the same issue on artix linux and I fixed it adding "eval $(dbus-launch --exit-with-session --sh-syntax)" on .xinitrc file.

I just found out that the runit dbus alone is not enough

**Comment by ZerdoX-x** [comment]
> I had the same issue on artix linux and I fixed it adding "eval $(dbus-launch --exit-with-session --sh-syntax)" on .xinitrc file.

Wayland doesn't have xinitrc file. Your comment not related to issue

**Comment by ZerdoX-x** [comment]
So we have nothing to do with flatpak until official discord build will support wayland. I got it launched finally using `electron --enable-features=UseOzonePlatform --ozone-platform=wayland /usr/lib/discord/app.asar` (not flatpak version of course), but it's crashing instantly. Just waiting until discord team will make all the work. Process can be tracked here: https://support.discord.com/hc/en-us/community/posts/360047644231-Native-Wayland-Support
