### ISSUE TITLE
Activity status consists of only Discord processes

### ISSUE THREAD

**Issue by alvinbengeorge** [flathub/com.discordapp.Discord#161]
So, I got to know about the activity status very recently. I wanted to try out. I checked the settings. Scrolled down and found the settings, and when I pressed the drop down, it showed only discord processes
![image](https://user-images.githubusercontent.com/69302420/128464166-00e970ea-f4e7-4c32-936a-e336470ede66.png)

I know that usually it would show apps that are running
Any solution for this?
Thanks in advance

Edit: Is it a flatpak override? I recently did filesystem

**Comment by TingPing** [comment]
There is no solution, its in a sandbox and proprietary.

**Comment by alvinbengeorge** [comment]
Which language is it written in, because I found out a solution for this in python
```[i for i in [p.info['name'] for p in psutil.process_iter(['name'])]]```
Yes this includes psutil and python, i am pretty sure something like this could be done in any language

**Comment by TingPing** [comment]
Flatpak is a sandbox. You cannot see host processes.

**Comment by alvinbengeorge** [comment]
All right cool

**Comment by HybridZach** [comment]
Came here to check about this having not noticed it's mentioned in the readme. It's a shame really, because this is the only real viable option for steam deck users. Is there no recent updates on workarounds or anything?

**Comment by TingPing** [comment]
If anything happens you could probably follow it here: https://github.com/flatpak/xdg-desktop-portal/issues/653

But not likely any time soon.
