### ISSUE TITLE
"View Repository" button doesn't do anything on Linux Discord

### ISSUE THREAD

**Issue by sethicis** [flathub/com.discordapp.Discord#171]
I added the Discord Presence extension to my VSC on Manjaro Linux and everything seemed to work out of the box, but after further testing I noticed that the "View Repository" button for my presence detection did nothing when I'd click it.

I checked on mobile and Windows and the button works as expected there, so the issue appears to be specific to Linux (or at least Manjaro Linux).

The version of Discord that I'm using is the one installed from the Manjaro package store, which does not seem to be a snap or flatpak application.

Please let me know if I can provide any additional information of use.

**Comment by lionirdeadman** [comment]
Um, if this is for the Manjaro package, this is the wrong place to report it. This repository is for the Flatpak package.

**Comment by sethicis** [comment]
Drat, thanks @lionirdeadman .
