### ISSUE TITLE
Run in background permission is broken, even when unset e.g. in flatseal discord continues in background

### ISSUE THREAD

**Issue by ell1e** [flathub/com.discordapp.Discord#179]
It appears that the Run in background permission is broken. From my tests even when the permission is removed e.g. in flatseal, Discord continues in background when I close its window (or even when I use GNOME 3's "Quit" from the shell menu which is supposed to terminate the program fully). Because Discord tends to bug out for me when running for an hour or longer, this is quite annoying because it really does not want to be fully terminated so restarting it becomes quite a hassle. Also, I guess this is also a mild privacy/security issue since a user would reasonably expect it to not be able to continue running in the background, for whatever that allows it to continue to do.

Edit: turns out for my own use case I can use Discord's "Minimize to tray" setting and disable it. that however still leaves the privacy expectations angle

**Comment by TingPing** [comment]
I think this is something to report elsewhere, maybe `xdg-desktop-portal`. If the permissions is denied its up to a system service to stop the software.

**Comment by guihkx** [comment]
I agree with the two responses above. This is not an issue caused by this package, so we can’t act upon it.
