### ISSUE TITLE
Crash on startup (Fedora 34 / GNOME / Wayland)

### ISSUE THREAD

**Issue by Igetin** [flathub/com.discordapp.Discord#181]
# Description of the issue

Trying to run a fresh install of the Discord Flatpak package results in the application crashing. The app briefly shows the small loading window with the text “Starting…”, after which it loads up a screen-sized empty window with windows decorations. Then that window seems to reopen once, and then the window closes with nothing happening after that.

# Log output

Running `flatpak run com.discordapp.Discord` gives the following output:

```
Disabling updates already done
[6 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/discord/Discord --type=zygote
Discord 0.0.16
Gtk-Message: 19:01:11.226: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:01:11.226: Failed to load module "pk-gtk-module"
Gtk-Message: 19:01:11.226: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:01:11.226: Failed to load module "pk-gtk-module"
Starting app.
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: disabled
[Modules] Module updates: enabled
[Modules] Module install path: /home/ige/.var/app/com.discordapp.Discord/config/discord/0.0.16/modules
[Modules] Module installed file path: /home/ige/.var/app/com.discordapp.Discord/config/discord/0.0.16/modules/installed.json
[Modules] Module download path: /home/ige/.var/app/com.discordapp.Discord/config/discord/0.0.16/modules/pending
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[Modules] No updates to install
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discord.com/api/modules/stable/versions.json
[Modules] No module updates available.
Cannot upload crash dump: failed to open
--2021-10-20 19:01:11--  https://sentry.io/api/146342/minidump/?sentry_key=384ce4413de74fe0be270abe03b2b35a
Resolving sentry.io (sentry.io)... 35.188.42.15
Connecting to sentry.io (sentry.io)|35.188.42.15|:443... connected.
HTTP request sent, awaiting response... [WebContents] crashed (crashed)... reloading
400 Bad Request
2021-10-20 19:01:12 ERROR 400: Bad Request.


Unexpected crash report id length
Failed to get crash dump id.
Report Id: 
Cannot upload crash dump: failed to open
--2021-10-20 19:01:12--  https://sentry.io/api/146342/minidump/?sentry_key=384ce4413de74fe0be270abe03b2b35a
Resolving sentry.io (sentry.io)... 35.188.42.15
Connecting to sentry.io (sentry.io)|35.188.42.15|:443... connected.
HTTP request sent, awaiting response... [WebContents] double crashed (crashed)... RIP =(
400 Bad Request
2021-10-20 19:01:13 ERROR 400: Bad Request.


Unexpected crash report id length
Failed to get crash dump id.
Report Id:
```

# App information

Running `flatpak info com.discordapp.Discord` gives the following output:

```
Discord - Messaging, Voice, and Video Client

          ID: com.discordapp.Discord
         Ref: app/com.discordapp.Discord/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.0.16
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 197.3 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: 50cdba1d069ca5b215ea4e5ab14ea81fe48cee3a5c45a78bd7d3beaedad66073
      Parent: 7b1e7dbd12d4eb214e5dfb9285dbdb1a82e847530b49e8f39fe45c00f1906bba
     Subject: Use backups from the Internet Archive. (ecdf680c)
        Date: 2021-10-03 17:25:05 +0000
```

# System information

Operating system: Fedora 34
GNOME version: 40.4 (mutter 40.5)
Windowing system: Wayland

**Comment by FilBot3** [comment]
This also happens on KDE with Fedora 34 as well. I switched from Xorg to Wayland to try it out with Nvidia cards.

```bash
Operating System: Fedora 34
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.85.0
Qt Version: 5.15.2
Kernel Version: 5.14.15-200.fc34.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 3800X 8-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
```

**Comment by vchernin** [comment]
@I-g-e are you also on Nvidia? 

@FilBot3 do you have xwayland 21.1.2.901 or newer on your system? It includes some important Nvidia Xwayland fixes.

**Comment by I-g-e** [comment]
> @I-g-e are you also on Nvidia?

Nope, I'm on AMD (RX 6800 XT).

**Comment by FilBot3** [comment]
> @FilBot3 do you have xwayland 21.1.2.901 or newer on your system? It includes some important Nvidia Xwayland fixes.

I will check. Hopefully Fedora 34 KDE has them ready. I keep it fairly up-to-date. How does one check?

**Comment by vchernin** [comment]
`rpm -q xorg-x11-server-Xwayland`

If you're up-to-date you should already have 21.1.2.901 or 21.1.3 (they're basically the same).

However note KDE 5.23.2 (in 35 testing) has GBM support for Nvidia-this is a good thing, but unfortunately due to this Qt bug: https://codereview.qt-project.org/c/qt/qtwayland/+/373473 the interface will be extremely slow (but otherwise should mostly work).

**Comment by lionirdeadman** [comment]
Does this also happen on a non-flatpaked Discord for you? Would be rather interesting if it was specific to Flatpak.

**Comment by I-g-e** [comment]
The crash only happened for me on Wayland when I used the Flatpak package installed via Flathub. The RPM package installed via DNF from the RPM Fusion repository does not have the problem (which is why I'm currently using that).

I just tried logging into a Xorg session, and the Flatpak package seems to launch and run fine there.

**Comment by vchernin** [comment]
Can you try running with no gpu?  `flatpak run com.discordapp.Discord --disable-gpu`

See also https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/76
https://github.com/flathub/org.chromium.Chromium/issues/166

**Comment by lionirdeadman** [comment]
I have some ideas.

@I-g-e Can you paste your permission overrides? `flatpak info --show-permissions com.discordapp.Discord` would do it. Maybe you did something that breaks only in Wayland somehow. Setting `fallback-x11` and `wayland` would probably do that.

@FilBot3 You are forcing it to run in Wayland although you're not using Ozone, this will result in a crash. I'd recommend resetting your permissions as I see you've given `fallback-x11` (which removes x11 access if Wayland is available). As a side note, `/proc/` does not work so you might as well remove that too.

**Comment by I-g-e** [comment]
I didn't have the Flatpak version installed anymore, so I reinstalled it now. Seems to be working fine now under Wayland… something probably changed in my system, because back when I created this issue, I tried reinstalling the app and rebooting _multiple_ times, but got always the same crash.

I'm still running the same GNOME & mutter versions too, so the root cause probably wasn't related to those. I didn't mess with my Flatpak configuration during that time either, the last `flatpak` command I ran before today was the uninstall command when I gave up trying to get it working a couple of weeks ago.

> @I-g-e Can you paste your permission overrides? `flatpak info --show-permissions com.discordapp.Discord` would do it.

This probably won't help anymore, but just in case:

```
[Context]
shared=network;ipc;
sockets=x11;pulseaudio;
devices=all;
filesystems=xdg-download;xdg-pictures:ro;xdg-videos:ro;

[Session Bus Policy]
org.kde.StatusNotifierWatcher=talk
org.freedesktop.Notifications=talk
com.canonical.AppMenu.Registrar=talk
com.canonical.indicator.application=talk
com.canonical.Unity.LauncherEntry=talk
```

---

Anyway, as far as I'm concerned, the issue is “resolved” — although the root cause is a mystery. @FilBot3⁠'s issue seems to be a different one.

**Comment by lionirdeadman** [comment]
> Anyway, as far as I'm concerned, the issue is “resolved” — although the root cause is a mystery, as I can't reproduce the crash anymore.

That's good, I'll hope nobody else is facing that bug.

> FilBot3⁠'s issue seems to be a different one.

I do think it is different as well (as no data point matches other than running in a wayland session)

**Comment by gati-petriashvili-twino** [comment]
I've started to get the same issues on Discord, Spotify and Signal flatpak applications right after I upgraded to Fedora 35.
Not sure what changed there, running with `--disable-gpu` does the trick as a workaroud but can't figure out how to fix the issue for good.

**Comment by guihkx** [comment]
Does this still happen?
