### ISSUE TITLE
Stuck on "Bip bup. Bup bip?"

### ISSUE THREAD

**Issue by canonex** [flathub/com.discordapp.Discord#185]
Right after flatpack install, i try to login.
I enter user and pass.
"Bip bup. Bup bip?" are you human or robot prompt appears and it stays forever.

![DiscordFlatpack](https://user-images.githubusercontent.com/1444378/140193639-efc14136-ed67-4d7c-a91c-00c062e083f9.png)

I have no possibility other that close the software. On restart, the same screen appears.

I'm on Debian 11, Gnome 3.30.2

Thank you,
Riccardo

**Comment by lionirdeadman** [comment]
Sorry for the late reply, is there any log data?

**Comment by canonex** [comment]
Searching how to debug flatpack I did:
`flatpak run --command=sh --devel com.discordapp.Discord`
and got
`error: runtime/org.freedesktop.Sdk/x86_64/21.08 not installed`
so I did
`sudo flatpak install org.freedesktop.Sdk/x86_64/21.08`

After I retried:
`flatpak run --command=sh --devel com.discordapp.Discord`
and it was ok
`[📦 com.discordapp.Discord ~]$ discord `

Executing `discord`
I got the stuck window but some more info:
```
2021/11/14 12:13:07 socat[5] E "/run/user/1000/app/com.discordapp.Discord/discord-ipc-0" exists
Disabling updates already done
[8 zypak-helper] Error retrieving supports property: org.freedesktop.DBus.Error.InvalidArgs: Proprietà «supports» inesistente
[8 zypak-helper] Portal v4 is not available
Error reading dictionary property: 'BACKGROUND_COLOR'
Discord 0.0.16
Quitting secondary instance.
Gtk-Message: 12:13:08.306: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:13:08.306: Failed to load module "canberra-gtk-module"
[16 zypak-sandbox] Dropping 0x55f9815f32c0 (3) because of connection closed
[16 zypak-sandbox] Host is gone, preparing to exit...
[16 zypak-sandbox] Quitting Zygote...
/app/bin/discord: riga 11: kill: (5) - Nessun processo corrisponde
```


Thank you,
RIccardo

**Comment by eunakria** [comment]
I feel like in this case, you're better off looking out for any errors in the browser dev console. Try pressing ctrl-shift-i and check what it logs there?

**Comment by lionirdeadman** [comment]
Some of this log is pretty strange in regards to SETTINGS.json, I'd recommend clearing `~/.var/com.discordapp.Discord/` to fix that at least.

**Comment by canonex** [comment]
> I'd recommend clearing `~/.var/com.discordapp.Discord/` to fix that at least.

That solved the issue. I'm able to use the Discord Flatpack!

@eunakria I didn't know it was a browser...!

**Comment by lionirdeadman** [comment]
Glad it now works!

**Comment by eunakria** [comment]
@canonex yup, Discord is an Electron app, which basically means it's a web app that has a couple native system privileges. I'm not a huge fan of Electron apps, but being able to use the Chrome dev tools to debug them is pretty nice

**Comment by canonex** [comment]
I reopen this issue as it is happens again after updating to version 0.0.17.
The worst it that it happens all the time I re-open the app.

As the last time, after the update it gets stuck on Bip Bup.
As the last time I deleted all config in:
`~/.var/com.discordapp.Discord/`
Starting the app, it does work.

But this time, after each startup, it repeats the same situation: the login is not saved and at each startup it asks for the password and after entering it freezes on beep bup.

Thank you.
