### ISSUE TITLE
Does not run in Fedora 35

### ISSUE THREAD

**Issue by jalberto** [flathub/com.discordapp.Discord#195]
After upgrade to F35 this package doesn't run, I tried reinstalling and running in cli with `-vv` but nothing shows up

**Comment by lionirdeadman** [comment]
Hi,

I use F35 and have been for months as other people I know have so I find it hard to relate to that.

What GPU? DE? X11 or Wayland?

Furthermore, have you tried `flatpak update`?

Can you try clearing `~/.var/app/com.Discord app.Discord/` (this will clear your login information, cache and such)?

**Comment by jalberto** [comment]
![image](https://user-images.githubusercontent.com/99927/148052055-c0089acc-672d-4748-8a41-dd9707529204.png)

I am on wayland on an intel embedded GPU (Dell XPS laptop)

**Comment by vchernin** [comment]
Are you using default permissions for this package? Perhaps see if it coredumped (`flatpak-coredumpctl` can help).

**Comment by Aex12** [comment]
I'm running Discord flatpak on F35 without issues. I had a minor issue with wireplumber (voice never connected) which I resolved by just switching wireplumber to pipewire-media-session. More info here: https://fedoraproject.org/wiki/Changes/WirePlumber#How_To_Switch

**Comment by diegosace2000** [comment]
i have a problem running it on f35 too in wayland 
¨[6 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/discord/Discord --type=zygote
Traceback (most recent call last):
  File "/app/bin/set-gtk-dark-theme.py", line 17, in <module>
    disp = Xlib.display.Display()
  File "/app/lib/python3.9/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/app/lib/python3.9/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/app/lib/python3.9/site-packages/Xlib/protocol/display.py", line 84, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/app/lib/python3.9/site-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "/app/lib/python3.9/site-packages/Xlib/support/unix_connect.py", line 76, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""
Discord 0.0.17
Failed to generate minidump./app/bin/discord: línea 18:     6 Violación de segmento  (`core' generado) env TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/discord/Discord $FLAGS "$@"
exit code
