### ISSUE TITLE
Streamer mode does not activates automatically with Flatpak installation

### ISSUE THREAD

**Issue by Deuchnord** [flathub/com.discordapp.Discord#197]
This might be related to #99, but I'm not entirely sure it actually is.

Discord provides [an feature](https://support.discord.com/hc/en-us/articles/218485407-Streamer-Mode-101) that, when enabled, detects automatically that you are sharing your screen, through OBS Studio for instance. This feature enables typically three behaviors:

- it displays an alert at the top of the application to remind you that your screen is shared;
- it disables all the notifications;
- it hides sensible information, like your identifier.

![A Discord window with the Streamer Mode activated](https://user-images.githubusercontent.com/7600265/149658781-7129c132-e66c-4c35-af78-299c3a20cb18.png)

While this feature works like a charm when Discord is installed system-wide, it looks like it looses the ability to detect that you are sharing your screen when it is installed with Flatpak.

**Comment by lionirdeadman** [comment]
I'm not sure how it detects it but I think it's more likely to be #115 which is not something I can fix.

**Comment by vchernin** [comment]
In theory there could be an api/hack to check if there’s an _external_ active pipewire/x-d-p screencast session. At least that sounds cleaner than reading `/proc`.

**Comment by lionirdeadman** [comment]
Yeah, such an API would be quite neat. It would also support non-obs detection. On the other hand, that could also be harmful and prevent someone from screen sharing a screen (for DRM purposes).

**Comment by guihkx** [comment]
As already mentioned by someone else in this thread (and also last I checked), Discord detects OBS by reading from `/proc`, which is something currently [impossible](https://github.com/flathub/com.discordapp.Discord/issues/115#issuecomment-2389231773) with Flatpak.

Therefore, this is not something we can really act upon right now.
