### ISSUE TITLE
Discord losing audio after two minutes in a voice call

### ISSUE THREAD

**Issue by sebastiaanfranken** [flathub/com.discordapp.Discord#202]
When running Discord (Stable 113404 (30b719d)) on a up-to-date Fedora 35 install the sound input is lost after about 2 minutes in a voice (group) call. 

My hardware is detected fine by Discord and the audio test feature is clear, I can hear myself just fine through it. The first two minutes of the call go well, the other side can hear me fine, I can hear them. After that there's no sound from me. I can still hear the other side fine, but what I say does not come through. The audio test feature doesn't work after that, I can't hear myself with that either.

Hardware in question:
Sennheiser HMD 300 Pro into a Focusrite Scarlett 2i2 3rd generation which is connected to my machine via the included USB cable. 

The same hardware setup works (on the same machine) with Windows, and on my macOS machine(s), so I'm doubtfull it's hardware related.

If any more info is required, let me know.

**Comment by lionirdeadman** [comment]
Is this still the case? I'm not really sure how this could be related to the Flatpak and more so might be a pipewire or discord bug

**Comment by sebastiaanfranken** [comment]
Sorry for the late reply. I really haven't checked if this is stil the case. Will test tonight in VC, though I suspect the issue is still here.
I don't think it's a pipewire bug, since I use the same hardware for recording with Audacity, and that goes well. Might be a Discord bug though, yeah.

**Comment by sebastiaanfranken** [comment]
Ok, I'm in a voice chat right now and the mic signal stopped being picked up by Discord after ~5 minutes. Is there a way I can troubleshoot this in some way, to see if it's a Flatpak or a Discord issue?

**Comment by sebastiaanfranken** [comment]
I've been in a voice chat on Fedora for a few hours. The voice chat is working fine, audio quality is good. The thing I changed was the hardware timeout time for wireplumber in `/etc/wireplumber/main.lua.d/50-alsa-config.lua`:

```
["session.suspend-timeout-seconds"] = 0,
```
At the end of the file in the `aplay_properties` block.

Since it's fixed, and it wasn't a flathub/flatpak bug, I'm closing this.
