### ISSUE TITLE
"Open discord on system start" option doesn't work

### ISSUE THREAD

**Issue by kparal** [flathub/com.discordapp.Discord#21]
I have to run Discord every time manually after logging in, even when the autostart option is enabled. I'm using Fedora 27 with GNOME. Is this something that's still not implemented in Flatpak?

**Comment by TingPing** [comment]
That can't be implemented, and it can't be hidden, so it will just be a broken option there.

**Comment by TingPing** [comment]
You can yourself make an autostart entry in `~/.config/autostart` though copying over the `com.discordapp.Discord.desktop` file.

**Comment by kparal** [comment]
Thanks for info. Can you please explain why this can't be implemented? Is this currently a missing feature in Flatpak?

**Comment by TingPing** [comment]
This application can not read/write files in your home to create a launcher. (Even if it did it would need to be modified for flatpak but that is another thing).

Now Flatpak could implement some secure way of doing this by asking the user and flatpak creating it but that would require Discord use that feature which would be a long time from now if ever anyway.

**Comment by kparal** [comment]
I see, thanks.

**Comment by geekley** [comment]
> Now Flatpak could implement some secure way of doing this by asking the user and flatpak creating it but that would require Discord use that feature which would be a long time from now if ever anyway.

You mean flatpak dynamically prompting the user to allow this kind of permission/operation? That would be cool.

**Comment by dancojocaru2000** [comment]
As FlatPak has added support for this in [#118](https://github.com/flatpak/flatpak/issues/118), can this issue be reopened? (@TingPing?)

**Comment by lionirdeadman** [comment]
My understanding is that this requires work by Discord to use the portal. I'm not sure if we can hack something with a script but I imagine it might be possible.

I'll re-open this. If anyone is interested in trying to hack it, feel free.

**Comment by TingPing** [comment]
Still requires some hacky work.

**Comment by atirut-w** [comment]
You could look at how [Pika Backup](https://gitlab.gnome.org/World/pika-backup), a Flatpak app, gets permission to create an autostart entry without asking for explicit permission. Their implementation works flawlessly.

**Comment by guihkx** [comment]
As mentioned by other people above, it's really up to Discord devs ([or Electron devs](https://github.com/electron/electron/pull/42727)) to implement this using the appropriate portal API.

For now, PR #454 adds instructions to our README page on how to do that manually, which is good enough for me.
