### ISSUE TITLE
Stuck at login after clicking "I'm not a robot"

### ISSUE THREAD

**Issue by AlxHnr** [flathub/com.discordapp.Discord#210]
When clicking "I'm not a robot" during the login, the app hangs for about a minute and then the captcha turns gray:

![Screenshot_2022-03-24_20-02-19](https://user-images.githubusercontent.com/8235638/159992681-2cfbab27-5468-4a84-9a6e-558f3e374f90.png)

This issue is similar to #162 and #185, but deleting `~/.var/com.discordapp.Discord/` does not work. Neither does reinstalling the app. I tried downloading the official release tarball from Discord's homepage and the login works great! So does the web app via Firefox. This problem only occurs when installing Discord via flathub.

Here is the output of `flatpak run com.discordapp.Discord`:

```
Disabled updates
[6 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/discord/Discord --type=zygote
Xlib.xauth: warning, no xauthority details available
Discord 0.0.17
Gtk-Message: 20:01:00.855: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:01:00.855: Failed to load module "pk-gtk-module"
Gtk-Message: 20:01:00.855: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:01:00.856: Failed to load module "pk-gtk-module"
Starting app.
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: disabled
[Modules] Module updates: enabled
[Modules] Module install path: /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.17/modules
[Modules] Module installed file path: /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.17/modules/installed.json
[Modules] Module download path: /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.17/modules/pending
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[Modules] No updates to install
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discord.com/api/modules/stable/versions.json
[Modules] No module updates available.
Module ./ElectronTestRpc was not included.
Cannot upload crash dump: failed to open
--2022-03-24 20:02:00--  https://sentry.io/api/146342/minidump/[...]
Resolving sentry.io (sentry.io)... [...]
Connecting to sentry.io (sentry.io)|[...]|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2022-03-24 20:02:01 ERROR 400: Bad Request.


Unexpected crash report id length
Failed to get crash dump id.
Report Id:
```

The log above contains the following error, which does not occur with the official Discord binary:

```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

Maybe flatpak's sandbox is misconfigured?

My OS: Fedora 34
This flatpak app used to work perfectly fine in the past, but I can't tell you at which point the login broke.

**Comment by AlxHnr** [comment]
I can get rid of the libva error by adding `--disable-gpu` to my flatpak command. But that does not solve the problem.

**Comment by mystic-githuber** [comment]
@lionirdeadman @TingPing 
Could you please look into this? I am unable to login into my accounts.

**Comment by TingPing** [comment]
The only part of this package that could be breaking this is the extra flags we add: https://github.com/flathub/com.discordapp.Discord/blob/master/discord.sh#L9

So you can try running:

`flatpak run --command=zypak-wrapper com.discordapp.Discord /app/discord/Discord` without any flags to see if that changes anything.

If it crashes with no flags, its probably just Discords bug.

**Comment by mystic-githuber** [comment]
@TingPing 
Thanks! it worked by running `flatpak run --command=zypak-wrapper com.discordapp.Discord /app/discord/Discord`

**Comment by AlxHnr** [comment]
I can confirm that it works.

> If it works try removing flags from that list to narrow it down.

The problem is `CanvasOopRasterization` in the script. The fix should look like this:

```diff
- FLAGS='--enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --enable-features=UseSkiaRenderer,CanvasOopRasterization'
+ FLAGS='--enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --enable-features=UseSkiaRenderer'
```

Let me create a PR.
