### ISSUE TITLE
not closing properly

### ISSUE THREAD

**Issue by iaacornus** [flathub/com.discordapp.Discord#211]
the app won't close, you need to do `flatpak kill com.discordapp.Discord` in terminal, compared to other apps where closing the window is enough.

**Comment by lionirdeadman** [comment]
This is how Discord works. It runs in the background. Your desktop environment may provide a setting to prevent it from running in the background (like gnome allows in gnome control center) or it may provide a system tray icon which allows you to quit it.

**Comment by TwoHandsWithoutThumbs** [comment]
Go to User Settings -> APP SETTINGS -> Linux Settings and toggle off Minimize to Tray, that will properly close the program down when you kill the window.
