### ISSUE TITLE
can't upload files from external drives

### ISSUE THREAD

**Issue by levalithan** [flathub/com.discordapp.Discord#215]
so i know about the issue with not being able to access the whole local drive by default but after i type that command in it still won't let me take images from external drives and upload them which is bugging me a little

thanks

**Comment by TingPing** [comment]
If you added host filesystem permissions you have to restart the app. That is `flatpak override --user com.discordapp.Discord --filesystem=host`

This permission will stop being needed whenever Discord updates their bundled version of Electron.
