### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by babafc** [flathub/com.discordapp.Discord#217]
Is there any way I can have the same flatpak discord install running at the same time?
Playing with flatpak run I always get "/run/user/MYUID/app/com.discordapp.Discord/discord-ipc-0 exists"

**Comment by TingPing** [comment]
That's a file this package makes so sounds like a bug.

**Comment by guihkx** [comment]
I think this bug report is conflating two different things.

That error message you're getting is completely unrelated to your inability of launching multiple Discord instances, which is an unsupported feature even with non-Flatpak Discord, and won't be supported here either.

That message comes from `socat`, which we use to essentially make Discord's [Rich Presence feature](https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-\(discord-rpc\))  work.

Now, we shouldn't be seeing that message (somehow `socat` fails to remove that socket file, sometimes), and that's definitely a bug, but I think it's what's causing https://github.com/flathub/com.discordapp.Discord/issues/241 instead.
