### ISSUE TITLE
Hovering text field does not show text contextual cursor

### ISSUE THREAD

**Issue by Nightfirecat** [flathub/com.discordapp.Discord#222]
See title. This works as expected when installing to my system via Discord's native `.deb`.

My system is Debian 11 running KDE on Xorg.

**Comment by lionirdeadman** [comment]
Is this still an issue?

By contextual cursor, I assume we mean that when hovering over the text field, the cursor changes. If so, this works for me on GNOME 44, Fedora 38.

**Comment by Nightfirecat** [comment]
It seems to work fine now. The flatpak isn't using my system's cursors (it's using KDE Classic instead of Phoeton), but it is showing the text cursor when hovering text fields, etc.
