### ISSUE TITLE
Update to 0.0.18

### ISSUE THREAD

**Issue by ata-star** [flathub/com.discordapp.Discord#224]
![Bildschirmfoto vom 2022-06-08 21-05-44](https://user-images.githubusercontent.com/62115669/172696592-7761d63d-35d2-45ca-a55d-949ad9c4a1fc.png)

**Comment by Evernow** [comment]
People need to learn to be patient. Just wait for https://github.com/flathub/com.discordapp.Discord/commit/87163dcfa3df0b70550e977a1bf601608ec23e0b

**Comment by lionirdeadman** [comment]
Should be published, closing.
