### ISSUE TITLE
Audio is messed up. | Fedora Workstation 36

### ISSUE THREAD

**Issue by Munoida** [flathub/com.discordapp.Discord#225]
After a while, Discord notifications will stop playing their sounds (Messages, muting, deafening, e.t.c.)
Video playback will work (however no Audio will be outputted.)
Audio playback will not work (because yknow, what I said earlier.)

The only audio that will work are calls (which is convenient enough lmao.)

Although could also be a pipewire issue because I installed pipewire to get WineASIO to work (still didn't figure it out, gave up, and just stuck with pipewire lmao.)

**Comment by dowttie** [comment]
I'm experiencing the same issue on arch, also using pipewire.
All sounds stop after some time, only calls keep working.

**Comment by SuchBlue** [comment]
I am experiencing this too. Tried reinstalling discord but it did not work

**Comment by SuchBlue** [comment]
There was just an update to PipeWire on Fedora 36 that fixes this issue. I'm not sure about Arch, but I'd say it's worth giving it a try too.

**Comment by dowttie** [comment]
Haven't tried an update yet but I want to add this is not exclusive to flatpak, it happens with the arch package as well since version 18

**Comment by SuchBlue** [comment]
also I deleted my previous comment about updating because I had noticed that I just hadn't waited enough time for the sound to stop working (except for calls)

**Comment by SuchBlue** [comment]
I followed the instructions from the Arch wiki, and it seems to work for me now, hopefully it keeps working this time 🙃
https://wiki.archlinux.org/title/PipeWire#No_notification_sounds_from_Discord

If you don't have any configuration files, just copy /usr/share/pipewire to /etc/pipewire

**Comment by lionirdeadman** [comment]
Assuming this is an audio system issue instead of a problem with the flatpak, closing.
