### ISSUE TITLE
Failed on startup on Visual Studio Code

### ISSUE THREAD

**Issue by nimishmedatwal** [flathub/com.discordapp.Discord#230]
In runtime status it's showing 
uncaught error : Cannot read properties of null (reading 'write')
![image](https://user-images.githubusercontent.com/91622060/179798814-b3946ac0-692a-4301-96a9-b69c5f2722f0.png)

**Comment by lionirdeadman** [comment]
This is the Discord repository?

**Comment by nimishmedatwal** [comment]
Nope, this is the vscode.
