### ISSUE TITLE
Discord doesn't launch (awesome-wm)

### ISSUE THREAD

**Issue by Seme4eg** [flathub/com.discordapp.Discord#232]
Installed (and reinstalled) discord using flathub, cleared all cache, nothing helped, here what im getting in stderr from awesome-wm:

```
[6 zypak-helper] Failed to connect to session bus: [org.freedesktop.DBus.Error.NotSupported] Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
[6 zypak-helper] src/helper/main.cc:40(DetermineZygoteStrategy): Assertion failed: bus
/app/bin/discord: line 18:     6 Aborted                 (core dumped) env TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/discord/Discord $FLAGS "$@"
```

**Comment by refi64** [comment]
You need to have a D-Bus session instance running in order to use this. (The instructions to do this depend on your distro.)

**Comment by Seme4eg** [comment]
![image](https://user-images.githubusercontent.com/24554850/179847840-b5f5b6f0-f9da-4fd2-9819-fccb03bdc7c3.png)

**Comment by refi64** [comment]
I...have no idea how that value ended up like that, but I'm moderately sure Flatpak doesn't support the `guid=` part inside (and I'm not sure if it supports the session bus socket being under `/tmp` to begin with, but it might).

**Comment by Seme4eg** [comment]
restarted my wm, now i have this output.. no variable is set, i do get already that prob. this issue doesn't belong here, but perhaps you have any hint for me where and for what to research?
![image](https://user-images.githubusercontent.com/24554850/179850222-2dea831a-b6eb-44c1-b23f-3c157e961802.png)

**Comment by Seme4eg** [comment]
> I...have no idea how that value ended up like that, but I'm moderately sure Flatpak doesn't support the `guid=` part inside (and I'm not sure if it supports the session bus socket being under `/tmp` to begin with, but it might).
> 
> **EDIT:** also this seems to be using a UNIX abstract socket which I think isn't supported either?

And as answer for that was set like that when i ran `export $(dbus-launch)`

**Comment by refi64** [comment]
systemctl's dbus.service is the system-level bus, not the *session* bus, which is the one needed here. That being said, unless you have some very strange tweaks to your system, a session bus should already be running, likely at `/run/user/YOUR-USER-ID/bus`.

Instead, I'd imagine Awesome isn't hooked up properly to your systemd user session, so the environment variables that systemd sets for your user (viewable with `systemctl --user show-environment`) aren't showing up for you. The specifics of this are definitely beyond this tracker, but *as a temporary workaround*, you can probably set `DBUS_SESSION_BUS_ADDRESS` by hand to the session bus location I mentioned previously, and then look into your Awesome setup for any problems.
