### ISSUE TITLE
USB Webcam keeps resetting forever when I open Discord

### ISSUE THREAD

**Issue by ThePituLegend** [flathub/com.discordapp.Discord#233]
So, as son as I run Discord Flatpak, my `dmesg` log gets flooded with `usb 3-2: reset high-speed USB device number 3 using xhci_hcd` (confirmed, that USB device is indeed the webcam). It doesn't happen when I use the cam in a videocall, but the second the app opens.

That's not an issue per se, as I'm not seeing any functional impact whatsoever, but it's annoying and a clear sign that something is wrong. This behaviour didn't happen with any other app (neither Flatpak nor native) so far.

---

Some quick facts about my config, and I'm willing to help with more info if needed:

**Webcam:** Logitech C270 HD

**OS:** Pop!_OS 22.04 LTS

**uname:**  
```
5.18.10-76051810-generic #202207071639~1657252310~22.04~7d5e891 
SMP PREEMPT_DYNAMIC Fri J x86_64 x86_64 x86_64 GNU/Linux
```

**inxi -b:**
```
System:
  Host: oscar-pop Kernel: 5.18.10-76051810-generic x86_64 bits: 64
    Desktop: GNOME 42.2 Distro: Pop!_OS 22.04 LTS
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: <superuser required>
  Mobo: ASUSTeK model: PRIME B550-PLUS v: Rev X.0x
    serial: <superuser required> UEFI: American Megatrends v: 2803
    date: 04/27/2022
CPU:
  Info: 6-core AMD Ryzen 5 5600G with Radeon Graphics [MT MCP] speed (MHz):
    avg: 3301 min/max: 1400/4464
Graphics:
  Device-1: AMD Cezanne driver: amdgpu v: kernel
  Device-2: Logitech Webcam C270 type: USB driver: snd-usb-audio,uvcvideo
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,radeon,vesa gpu: amdgpu resolution:
    1: 1920x1080~60Hz 2: 1920x1080~60Hz
  OpenGL:
    renderer: AMD RENOIR (LLVM 13.0.1 DRM 3.46 5.18.10-76051810-generic)
    v: 4.6 Mesa 22.0.1
Network:
  Device-1: Intel Wireless 7265 driver: iwlwifi
  Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-3: Intel Bluetooth wireless interface type: USB driver: btusb
Drives:
  Local Storage: total: 2.73 TiB used: 61.09 GiB (2.2%)
Info:
  Processes: 392 Uptime: 35m Memory: 30.66 GiB used: 4.23 GiB (13.8%)
  Shell: Zsh inxi: 3.3.13
```

**Comment by 20after4** [comment]
I have the same issue with the same model of webcam.  For me, however,  it does cause functional impact in that I use the mic on my webcam for discord audio and my audio cuts out every few seconds when I'm using it.

**Comment by Frederico-Messa** [comment]
I also have the same issue with the same model of webcam.

**Comment by henfredemars** [comment]
I also have this issue. In my case, it doesn't matter whether I use flatpak or the deb release. I do not believe this is related to this project. 

Also, when this error started, I noticed the camera having issues in Windows also in my dual-boot configuration. I suspect that this could be a failure mode of this low-cost camera.

**Comment by mutax** [comment]
I have this or a very similar issue with a Logitech StreamCam:

Bus 004 Device 010: ID 046d:0893 Logitech, Inc. StreamCam

The camera works in Windows and all other applications in my arch installation, but when trying to enable it in discord the device resets, shows up as mass storage device briefly, resets again and reappears as camera. I suspect somehow the firmware upgrade process is being triggered. 

My only workaround so far is to use obs and a virtual v4l loopback camera to use it.

**Comment by guihkx** [comment]
Closing because the reports above indicate this not our bug, and so we can't do anything about it.
