### ISSUE TITLE
"Upload Failed" with filesystem access

### ISSUE THREAD

**Issue by Gingeh** [flathub/com.discordapp.Discord#237]
As the title says, I am unable to upload files. I have given access to user files with Flatseal. Uploads work correctly with the official `.deb` package.

Error message (shows with files from filesystem or clipboard):
![image](https://user-images.githubusercontent.com/39150378/184521612-77107890-5477-4ef4-987e-ccee83459105.png)

Flatseal setting:
![image](https://user-images.githubusercontent.com/39150378/184521607-16091163-65b7-4c15-a0df-4a32d4f8dd72.png)

**Comment by Epsi22** [comment]
I am having this same issue with a mounted drive directory. After giving the permission multiple times via command line to access the mounted filesystem - 
`sudo flatpak override com.discordapp.Discord --filesystem=/mnt/"drivename"
`
-  and also trying with Flatseal, it is still not showing the directory when opening the "upload a file" dialogue, or permitting drag and drop files to upload.

I switched to using the .deb for a bit to circumvent this, but that meant extra steps to update the app every time a new update is pushed. I've also gotten around the permissions issue by opening Discord in my web browser and uploading files that way, but that essentially means having two Discord clients open.

**Comment by TingPing** [comment]
One thing to note is the application has to be fully shut down and reopened after permission changes (ensure its not running in the background).

**Comment by Epsi22** [comment]
Okay, I actually dug into this a little harder, and I swear it wasn't working, yes, with the app closed properly.
I had tried navigating to /mnt/"drivename", right, in the file manager that pops up when you go to upload a file manually. I swear it wasn't showing up in the directory at all from Discord.
So in a text editor, I messed around with the override file (/var/lib/flatpak/overrides/com.discordapp.Discord) that was generated from the command line, while looking over the documentation on [Flatpak's file permissions](https://docs.flatpak.org/en/latest/sandbox-permissions.html).
I added another line to the override file: `--perisist=/mnt/"drivename"` and saved it, and opened Discord, and voila, I could navigate to the mnt directory and to the disk I wanted. So I added it to the side panel as a favorite link right away so I didn't have to navigate to it every time.

But here's where it gets trippy. For kicks and giggles, I went back to the override file and deleted the entries, (the "--filesystem" and "--persist" lines) one at a time, saving in between each deletion, quitting and reopening Discord each time to check. The shortcut/favorite link I created in the sidebar persisted, along with the ability to navigate to /mnt manually. Despite the override file being empty.

Now, I haven't rebooted or logged out of my user account on the computer yet, so if I leave the override file empty after doing that, will the permission persist? I'm going to try that next.

**Comment by TingPing** [comment]
`--persist` is not what you want but with both it should be ignored.

**Comment by FullMetalMeowchemist** [comment]
For my simplistic case, I just did `sudo flatpak override com.discordapp.Discord --filesystem=home` to allow it access to most files I might be uploading.

**Comment by TingPing** [comment]
I'm going to close this since it hasn't been updated with any information to believe its an issue.

**Comment by rybak** [comment]
This issue seems to have re-appeared. Upgraded from 0.0.61 to 0.0.63, it didn't help. Tried changing filesystem with Flatseal and with [KDE's System Settings](https://invent.kde.org/plasma/flatpak-kcm), didn't help.

Here's what the override file has currently:

```
$ cat ~/.local/share/flatpak/overrides/com.discordapp.Discord 
[Context]
sockets=fallback-x11;wayland
filesystems=/home/andrei/Pictures;xdg-pictures;home:ro
```

For reference, the `.desktop` file, which has the exec line:

```
$ cat /home/andrei/.local/share/applications/com.discordapp.Discord.desktop 
[Desktop Entry]
Name=Discord
StartupWMClass=discord
Comment=All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
GenericName=Internet Messenger
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=com.discordapp.Discord com.discordapp.Discord
Icon=com.discordapp.Discord
Type=Application
Categories=Network;InstantMessaging;
Path=/usr/bin
X-Desktop-File-Install-Version=0.27
MimeType=x-scheme-handler/discord;
X-Flatpak-Tags=proprietary;
X-Flatpak=com.discordapp.Discord
```
