### ISSUE TITLE
Detecting games and black screen when sharing a screen

### ISSUE THREAD

**Issue by mihail727** [flathub/com.discordapp.Discord#238]
[Detecting games]
I read this page but did not understand how to start it all correctly...
Can you please explain to me how to do this with `flatseal`?

[Black screen #Wayland]
I also read various discussions and eventually realized that there is no final solution for the flatpak version (excluding discord electron).
again, maybe I read it wrong, but maybe something can be done through `flatseal`?

**Comment by TingPing** [comment]
It can't detect games.

**Comment by TingPing** [comment]
I've never used the screen sharing functionality, but its very likely it simply doesn't support Wayland. That would be a Discord problem.

**Comment by TingPing** [comment]
Flatpak runs inside of a sandbox. It cannot see other processes on the host.

There is a chance this becomes possible in the future but I wouldn't expect it anytime soon.

**Comment by lionirdeadman** [comment]
Separate issues exist for both. #89 #115
