### ISSUE TITLE
Video / Screensharing reported as unsupported

### ISSUE THREAD

**Issue by librarianmage** [flathub/com.discordapp.Discord#247]
With the latest update, when joining a voice chat a yellow banner appears that states that video / screen sharing / etc. is unsupported by this client.

**Comment by TingPing** [comment]
Works fine here. Maybe they switched to using pipewire so you'll need an up to date `pipewire`, `xdg-desktop-portal`, etc.

**Comment by librarianmage** [comment]
I am currently on GNOME (Pop! OS 22.04). What do I need to do to make sure I have it correctly updated?

**Comment by devurandom** [comment]
Is this still a problem? I believe in recent versions it still cannot screen share, but for different reasons: https://github.com/flathub/com.discordapp.Discord/issues/380

**Comment by guihkx** [comment]
Closing due to lack of response from the reporter.

Feel free to reopen if this issue still persists with the latest version of Discord.
