### ISSUE TITLE
Possible to patch screenshare audio issue using wrapper? Link to fix attached

### ISSUE THREAD

**Issue by ttang4299** [flathub/com.discordapp.Discord#250]
I've reached out to Discord support and opened a support ticket, but they replied saying that they don't have an interest in fixing screenshare audio on Linux unless it gets enough upvotes on their support forum.

I don't want to depend on that figure for a fix, so I was wondering if the developers of this wrapper are capable of patching the fix in so that no action is necessary from Discord.

The link to the fix is here: https://github.com/edisionnano/Screenshare-with-audio-on-Discord-with-Linux

**Comment by TingPing** [comment]
AFAICT this is for use with the website, not the Electron app. Their ToS also does not allow modifications to their application.

**Comment by TheRealDeLorian** [comment]
> I've reached out to Discord support and opened a support ticket, but they replied saying that they don't have an interest in fixing screenshare audio on Linux unless it gets enough upvotes on their support forum.

Can I get a link to that support forum so I can upvote it?

**Comment by ttang4299** [comment]
@TheRealDeLorian Apologies for the delayed reply, here's the link: https://support.discord.com/hc/en-us/community/posts/10669798330391-There-is-a-fix-for-screenshare-audio-on-Linux-but-Discord-isn-t-implementing-it

CC'ing @quazar-omega @cassidyjames @Sukuratchi @Eskander as per your reactions so you guys can get on that too if you wish.

Drop some upvotes and some comments to help get the post some traction.

> AFAICT this is for use with the website, not the Electron app. Their ToS also does not allow modifications to their application.

@TingPing Electron itself is a browser wrapper for Discord. If the fix works on a web browser, it should theoretically work with a patch to the desktop app as well (with minimal tweaks if needed). And while 3rd party mods to the desktop app aren't allowed, the ultimate goal is to get this solution officially implemented by Discord themselves.

**Comment by lionirdeadman** [comment]
While it might be possible to patch it, we don't want to patch the application as it would be against their TOS. If the goal is to get this fix officially in Discord, it might be possible to contribute here: https://github.com/discord/electron/tree/22-x-y though I've not seen anyone outside of the Discord team.

**Comment by quazar-omega** [comment]
@ttang4299 Thanks for that!  
Btw, it seems from a comment there that the fix wouldn't work anymore so, if it is true, is there any point in going there and upvote?

**Comment by ttang4299** [comment]
> While it might be possible to patch it, we don't want to patch the application as it would be against their TOS.

TingPing had made that clear previously.

> If the goal is to get this fix officially in Discord, it might be possible to contribute here: https://github.com/discord/electron/tree/22-x-y though I've not seen anyone outside of the Discord team contribute.

Will submit an issue there and see where it leads.

> Btw, it seems from a comment there that the fix wouldn't work anymore so, if it is true, is there any point in going there and upvote?

@quazar-omega That comment was from 9 months ago. The GitHub repo I linked has been actively worked on since then, with the last change being 2 months ago. I think that user might just be having a hardware problem, but also, upvoting anyways and leaving more comments always gives us a better chance of getting attention from a Discord dev.

**Comment by quazar-omega** [comment]
Ah I see, that sounds good! I guess it doesn't hurt to try

**Comment by guihkx** [comment]
As previously mentioned by others, this won't be added because it breaks Discord's ToS.

Sorry everyone.
