### ISSUE TITLE
Enabling Hardware Acceleration causes extermely high CPU usage

### ISSUE THREAD

**Issue by peterlobster** [flathub/com.discordapp.Discord#260]
Enabling Hardware Acceleration cause my CPU (8700K) to jump to 70-90% CPU usage; making the application barely usable causing the Audio to lag, and everything to slow down to a crawl.

Turning off Hardware Acceleration brought down the CPU usage to 30-50%; which still seems high, but solves most of the problems. 

FWIW I'm using Prime (which I think is actually Reverse Prime), I dunno if that has anything to do with it.

**Comment by TingPing** [comment]
We do enable some flags that might cause the issue. You could test out removing them to see if that helps.

Try running Discord with `flatpak run --command=zypak-wrapper com.discordapp.Discord /app/discord/Discord`.

That will run without any flags. If that does work better you can try slowly adding these flags one by one to see which is problematic: https://github.com/flathub/com.discordapp.Discord/blob/master/discord.sh#L9

**Comment by lionirdeadman** [comment]
Is this still an issue on Discord 0.0.27? (Assuming newer Electron might not have this problem)
