### ISSUE TITLE
Needs to be updated to 0.0.23

### ISSUE THREAD

**Issue by a73s** [flathub/com.discordapp.Discord#262]
Launching discord flatpak gives the update window, "Must be your lucky day, there's a new update!". I am on fedora 36. Using webcord in the meantime, but it's inferior.

**Comment by Jeshix** [comment]
You can trick the launcher by editing version from `0.0.22` to `0.0.23` in `/var/lib/flatpak/app/com.discordapp.Discord/current/active/files/discord/resources/build_info.json`

**Comment by Fuseteam** [comment]
this was solved in #261 perhaps you need to update your flatpak

**Comment by Lonsfor** [comment]
the update was not published for some reason tho

i think the bot might be bugged or something

**Comment by TingPing** [comment]
I'll manually publish it again.

**Comment by TingPing** [comment]
Success, just update :)
