### ISSUE TITLE
Error when launching app

### ISSUE THREAD

**Issue by aandrew-me** [flathub/com.discordapp.Discord#266]
I am getting this error when launching app after the latest update
![image](https://user-images.githubusercontent.com/66430340/212486843-1431a68b-3077-4cfa-b4d9-95a5dc5355ba.png)

**Comment by TingPing** [comment]
We don't modify the application. You can report it to Discord.

**Comment by TingPing** [comment]
0.24.0 will be out later today, so probably update and try again.

**Comment by aandrew-me** [comment]
Okay thanks
