### ISSUE TITLE
Error when starting discord in arch-linux: coreModule.startup is not a function.

### ISSUE THREAD

**Issue by BlackORTS** [flathub/com.discordapp.Discord#271]
I installed arch in a laptop and when trying to open discord (i tried to open it with the .tar.gz and from the arch repository) i get the following error: 
![2023-01-27-23:38:29-screenshot](https://user-images.githubusercontent.com/45906919/215220028-f821b867-e560-4504-b947-77f2d7fb52b0.png)

**Comment by TingPing** [comment]
This repo is for the Flatpak...?
