### ISSUE TITLE
Clicking links doesn't open web browser

### ISSUE THREAD

**Issue by ComplexPlane** [flathub/com.discordapp.Discord#272]
On Ubuntu 22.04 LTS and Brave as the default browser (no idea about other browsers), clicking links does nothing. The .deb Discord works.

**Comment by TingPing** [comment]
Is `xdg-desktop-portal-gtk` installed?

Does `flatpak run --command=xdg-open com.discordapp.Discord https://example.org` work?

Does `gio open https://example.org` work outside of Flatpak?

**Comment by ComplexPlane** [comment]
Installing `xdg-desktop-portal-gtk` worked it seems, seems like it should be in the readme? Thanks.

**Comment by TingPing** [comment]
Your distro is expected to provide these by default. It has nothing to do with individual packages.
