### ISSUE TITLE
'RTC Connecting' caused by disconnection from pipewire

### ISSUE THREAD

**Issue by RalekArts** [flathub/com.discordapp.Discord#274]
Any time I attempt to connect to a voice call, it gets stuck on 'RTC Connecting' until I disable and re-enable any pipewire applications I have (such as EasyEffects). I must do this every time I connect to a voice channel.

Before the latest update, this only occurred when my computer woke from asleep. Now it is permanent, and audio will suddenly stop working every 10 minutes or so with no warning and pipewire needs to be restarted mid-call.

Kubuntu 22.10
KDE Plasma 5.25.5
Kernel 5.19.0-31-generic
X11

**Comment by lionirdeadman** [comment]
Is this still an issue?

Though, I imagine this is an upstream problem and I don't think that's something we can work around so I'll tag it as such.

**Comment by guihkx** [comment]
Closing due to lack of response from the reporter.

Feel free to reopen if this issue still persists with the latest version of Discord.
