### ISSUE TITLE
Crashes DE along with GPU

### ISSUE THREAD

**Issue by mritunjaymusale** [flathub/com.discordapp.Discord#275]
Whenever I try to upload a file and select Computer on the left side panel, it crashes my DE first after which it somehow causes my gpu drivers or something related to it to crash aswell.(reason why I say that is because it causes my second monitor to go pixelated)
I have experienced this with and without the file sysytem permission using flatseal. 

OS : Fedora 37
GNOME verison : 43.3

**Comment by TingPing** [comment]
See this comment which could help tracking down a problematic flag used in this package: https://github.com/flathub/com.discordapp.Discord/issues/210

That said the actual bug would be in how Electron interacts with your GPU driver. Both places we can't fix here. But maybe a workaround can be added for a specific GPU.

**Comment by guihkx** [comment]
This bug report is a bit old and kinda unusual, so can you please check if this is still an issue using the latest Discord?

**Comment by guihkx** [comment]
Closing, as the reporter seems unavailable to retest this with the current version of Discord.

If the problem still persists, I'd suggest you [report it to Discord devs](https://support.discord.com/hc/en-us/articles/1500006052822-How-to-Report-a-Bug).
