### ISSUE TITLE
Update 0.0.26 plays badly with KDE Plasma systray

### ISSUE THREAD

**Issue by aleasto** [flathub/com.discordapp.Discord#279]
The first click is discarded, afterwards the cursor changes shape and right click works. The menu cannot be closed by clicking outside.
The icon is also very low res.

**Comment by TingPing** [comment]
Discord is proprietary so unless you test it packaged in a different way it is assumed to be their bug and they'll have to fix it.

**Comment by aleasto** [comment]
It works normally with discord from the tarball

**Comment by valeth** [comment]
If I open up the entire Session D-Bus (not recommended) it is showing the tray icon as normal.
So I'm guessing it's using a fallback method for the tray icon because some bus names are not exposed.

**Comment by TingPing** [comment]
Fixed by f1f6302cbd1a710d2243f013f252cc9106162941

**Comment by carlocastoldi** [comment]
Discord does not _own_ the `org.kde.*` bus tho, does it? What kind of permissions does discord gain until electron is updated?

**Comment by TingPing** [comment]
It will try to own `org.kde.StatusNotifierItem-*-1` but we can’t have rules that specific. It is a big permission but it’s a core feature. It will go away eventually.
