### ISSUE TITLE
cannot open Discord 0.0.5 on KDE Plasma: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by glaubersm** [flathub/com.discordapp.Discord#28]
Hello
After update to Discord 0.0.5 I get this error on my system:

$flatpak run com.discordapp.Discord/x86_64/stable
/app/extra/discord: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

Problem occurs on a computer running Arch Linux, KDE Plasma 5.12.5, flatpak 0.11.5.
I have another computer also running Arch Linux with Gnome 3.28.1, flatpak 0.11.5 and it runs Discord 0.0.5 from flathub perfectly.

**Comment by glaubersm** [comment]
GS_LIB=/home/stalker/.fonts
KDE_FULL_SESSION=true
LANG=pt_BR.UTF-8
PROFILEHOME=
DISPLAY=:0
SHELL_SESSION_ID=fd7353d1af374e02afa8967eff924791
COLORTERM=truecolor
QT_SCREEN_SCALE_FACTORS=VGA-1=1.2;HDMI-1=1.2;HDMI-2=1.2;DP-1=1.2;HDMI-3=1.2;
MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
XDG_VTNR=1
PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket
XDG_SESSION_ID=c6
USER=stalker
DESKTOP_SESSION=/usr/share/xsessions/plasma
PWD=/home/stalker
HOME=/home/stalker
XCURSOR_SIZE=0
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=/home/stalker/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop
KONSOLE_DBUS_SESSION=/Sessions/1
XDG_SESSION_DESKTOP=KDE
KONSOLE_DBUS_WINDOW=/Windows/1
GTK_MODULES=canberra-gtk-module
MAIL=/var/spool/mail/stalker
TERM=xterm-256color
SHELL=/bin/bash
KONSOLE_DBUS_SERVICE=:1.85
XDG_SESSION_CLASS=user
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XCURSOR_THEME=breeze_cursors
XDG_CURRENT_DESKTOP=KDE
KONSOLE_PROFILE_NAME=Perfil 1
XDG_SEAT=seat0
SHLVL=2
COLORFGBG=15;0
LANGUAGE=en_US
WINDOWID=67108870
LOGNAME=stalker
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
XAUTHORITY=/home/stalker/.Xauthority
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session5
QT_AUTO_SCREEN_SCALE_FACTOR=0
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin
KDE_SESSION_UID=1000
KDE_SESSION_VERSION=5
SESSION_MANAGER=local/Arch-PC:@/tmp/.ICE-unix/3139,unix/Arch-PC:/tmp/.ICE-unix/3139
_=/usr/bin/env

**Comment by TingPing** [comment]
I don't see anything related to library lookup. Others have mentioned issues like this on other apps but I'm not sure what would cause it.

**Comment by glaubersm** [comment]
Today I updated Discord on another distro (Neon dev unstable) running kde plasma and I got no problem.

**Comment by glaubersm** [comment]
currently I'm getting another error

![screenshot_20180517_123336](https://user-images.githubusercontent.com/15967631/40188262-f1ce4e56-59cf-11e8-8004-4b613bc775df.png)

**Comment by jadbox** [comment]
I'm having the same `libgtk-x11-2.0.so.0` error on Fedora 28.
