### ISSUE TITLE
Tray icon disappearing after updating to 0.0.26

### ISSUE THREAD

**Issue by NOOBDY** [flathub/com.discordapp.Discord#281]
As stated, launching Discord no longer seems to show the tray icon. Restarting my computer or Discord doesn't seem to fix the issue. However rolling back to 0.0.25 does work.

0.0.26 Behavior:
![image](https://user-images.githubusercontent.com/48180490/230083165-b440bace-271a-49ed-bfd9-226b0b1f2acb.png)

0.0.25 Behavior:
![image](https://user-images.githubusercontent.com/48180490/230083097-4f3b7334-0982-410c-8b61-42759b376a2e.png)

* Discord version: Stable 186309 (0f83804) Host 0.0.26 Linux 64-Bit (6.1.22-1-Lts)
* OS: Arch Linux
* DE/WM: Sway 1.8.1-1
* Kernel: 6.1.22-1-lts

**Comment by TingPing** [comment]
Should be fixed by f1f6302cbd1a710d2243f013f252cc9106162941
