### ISSUE TITLE
Gif picker keeps flashing

### ISSUE THREAD

**Issue by xmo-odoo** [flathub/com.discordapp.Discord#282]
I'm lucky not to have photosensitive epilepsy, but I'd assume a victim of such would have a hard time (warning: flashes):

https://user-images.githubusercontent.com/7571158/230324718-7097b44c-8869-4c6c-94cf-735e92a50363.mp4

This is with:

- Linux Mint 21.1
- Cinnamon 5.6.8
- Flatpak 1.12.7
```
          ID: com.discordapp.Discord
         Ref: app/com.discordapp.Discord/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.0.26
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 240.7 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: 76a6690cacf868dc6bb4ba258357453ea7e641e5d5aeb97b5844f2909420f1ed
      Parent: 8a36b8d955cb265aabf43fe247c69a2271b8ffadf920864cfee9f06f27225bbe
     Subject: Update discord-0.0.25.tar.gz to 0.0.26 (ba14eeee)
        Date: 2023-04-02 22:48:41 +0000
```

**Comment by TingPing** [comment]
Probably report it to Discord: https://support.discord.com/hc/en-us/articles/360046057772-Discord-Bugs

**Comment by TingPing** [comment]
Can leave it for now. I imagine it will get fixed next Electron update for them.

**Comment by Bikutoso** [comment]
I will add some additional information i found.

For one it's not only the gif picker that does it, switching servers and possibly unminimizing discord causes flashing too.
And my .xsession-errors gets the message `ERROR:shared_image_manager.cc(202)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.`  every time it happens.

**Comment by TingPing** [comment]
@Bikutoso Can you test `flatpak run --command=zypak-wrapper com.discordapp.Discord /app/discord/Discord --enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization`

And try removing/readding arguments to see if one is problematic?

**Comment by Bikutoso** [comment]
> @Bikutoso Can you test `flatpak run --command=zypak-wrapper com.discordapp.Discord /app/discord/Discord --enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization`
> 
> And try removing/readding arguments to see if one is problematic?

All combinations of the 5 arguments gives the same result
Included are a [log](https://github.com/flathub/com.discordapp.Discord/files/11196238/full_log.txt) of a run with all 5 arguments used, where i went to a server opened the gif browser and looked at some gif's to trigger the issue.

**Comment by lionirdeadman** [comment]
Does this still happen on 0.0.27?

**Comment by Bikutoso** [comment]
@lionirdeadman I can confirm it's still present in 0.0.27

**Comment by Bikutoso** [comment]
I still have the issue in 0.0.28.

And i did just notice as i installed Discord on another computer i had it worked there without issues, so i do wonder what is different on machines having this issue to those who do not?

**Comment by faelana** [comment]
> I still have the issue in 0.0.28.
> 
> And i did just notice as i installed Discord on another computer i had it worked there without issues, so i do wonder what is different on machines having this issue to those who do not?

@Bikutoso Hi, you should try my fix.

**Comment by Bikutoso** [comment]
I turned off Hardware Acceleration in Discord and it seems to have fixed the flashing. It's not optimal without it, but it should be better than running an out of date version

**Comment by MintMain21** [comment]
Using the Flatpak on the latest version of Linux Mint in February 2024. I want to use the app with Hardware Acceleration for optimal usability, but this bug persists. I thought enabling reduced motion would fix it but it doesn't. 

I might transition to using the deb package from the official Discord website. 

Might also have something to do with Swappiness, but I don't know.

**Comment by TingPing** [comment]
> I might transition to using the deb package from the official Discord website.

Unless its a Mesa bug it should behave identical. Let us know if otherwise.

**Comment by MintMain21** [comment]
Haven't been using the Deb package for long. In general it seems to work better, but the bug is more or less the same, just not as frequent.

**Comment by guihkx** [comment]
Can anyone please check if this is still an issue with latest Discord (0.0.70)?

**Comment by Bikutoso** [comment]
> Can anyone please check if this is still an issue with latest Discord (0.0.70)?
> 
> I do not see this on NVIDIA (470xx drivers) + X11.

I'm on 0.0.68 (i3-1315U UHD + X11) and haven't had issues for a few months now with hardware acceleration enabled
