### ISSUE TITLE
https://github.com/GooseMod/OpenAsar as a plugin in gnome software

### ISSUE THREAD

**Issue by nickname76** [flathub/com.discordapp.Discord#285]
I suggest adding https://github.com/GooseMod/OpenAsar as a plugin to enable for flaptaked discord in gnome software. https://github.com/GooseMod/OpenAsar/issues/136

**Comment by TingPing** [comment]
I don't think this will happen. It isn't something that can be supported when updates come out. It also violates Discord's EULA.
