### ISSUE TITLE
Support native wayland by default

### ISSUE THREAD

**Issue by Pythoner6** [flathub/com.discordapp.Discord#287]
When running the discord flatpak on wayland with fractional scaling (which I need to do to get comfortable UI sizing on many of my higher dpi displays), discord appears very blurry which is rather frustrating. I believe this is because it's running through xwayland which doesn't play nicely with fractional scaling. If I run discord manually like this `flatpak run --socket=wayland com.discordapp.Discord --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto` after allowing the wayland permission through flatseal, it mostly looks better, though something is really weird with the cursor.

**Comment by Vilianexe** [comment]
this could be implemented from the bash script used to open discord, if the user is running with a wayland session it automatically start with the variables, or am i missing something?
