### ISSUE TITLE
Add support for automatic titlebar theme based on application theme on Wayland

### ISSUE THREAD

**Issue by lionirdeadman** [flathub/com.discordapp.Discord#293]
Essentially, we currently have https://github.com/flathub/com.discordapp.Discord/blob/master/set-gtk-dark-theme.py which handles this but it currently doesn't work on Wayland.

Related to #270

**Comment by TingPing** [comment]
On Wayland we have no control over the titlebar, it is rendered by the application.

**Comment by lionirdeadman** [comment]
I thought you said this was possible https://github.com/flathub/com.discordapp.Discord/pull/270#issuecomment-1399678066

However, I've now realized that settings.json no longer has `BACKGROUND_COLOR` so the script currently doesn't work at all anymore, it seems..

**Comment by TingPing** [comment]
My eyes overlooked the "and wayland" part.

I meant it was easy to respect the freedesktop setting as its just a dbus call.

**Comment by TingPing** [comment]
Now that I'm on the Wayland version I'm a bit more open to letting the script just die.

Maybe there are some other workarounds I don't know of though.
