### ISSUE TITLE
Toggling Fullscreen Mode On and Off Breaks the Menu Bar on GNOME 44

### ISSUE THREAD

**Issue by manoliptram** [flathub/com.discordapp.Discord#294]
On bootup, everything looks fine, and maximizing + unmaximizing the window works just fine. However, when fullscreen mode is toggled on and back off, the menu bar appears suddenly at the top of the client and refuses to go away even when I try to press alt to toggle it. Images shown below.

Before fullscreen mode:
![image](https://user-images.githubusercontent.com/25092054/235289954-10989a0b-afc6-49ed-bc60-1074896c7b67.png)

After fullscreen toggle on and off:
![image](https://user-images.githubusercontent.com/25092054/235289972-a3611d01-ad7a-48cf-9f47-65660546c231.png)

**Comment by rowbawts** [comment]
Same bug, Silverblue F37 (GNOME 43.5). Someone with a more "traditional distro" should see if the upstream `.deb` exhibits the same behavior.

**Comment by selfdocumentingcode** [comment]
Experiencing the same problem on KDE 5.27 running on openSUSE Tumbleweed.

**Comment by virtuallyunknown** [comment]
I've also been having this issue for a few months now.

Linux Mint 21.1 Cinnamon.

**Comment by guihkx** [comment]
Revisiting this with Discord 0.0.70... Cannot reproduce.

**Steps attempted:**

1. Open Discord
2. Toggle full screen mode a few times with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd>

**Observed result:**

Discord never displayed its menu bar.

**Test environment 1:**

- Rocky 9.4 (virtual machine)
- GNOME 40.4.0 (Wayland)

https://github.com/user-attachments/assets/f423f12f-cd26-47bb-8481-8899bab04573

---

**Test environment 2:**

- Arch Linux
- KDE Plasma 6.1.5 (X11)

https://github.com/user-attachments/assets/e7b56967-85a4-4a4a-a0f3-aa946c58a8f7
