### ISSUE TITLE
Closed on login KDE

### ISSUE THREAD

**Issue by Felting** [flathub/com.discordapp.Discord#298]
When logging in on kde if discord was opened when the computer was put to sleep, it is closed and not in the tray.

**Comment by cYDN48** [comment]
Currently facing the same issue, but on Gnome using Pop!_OS 22.04 LTS. I haven't had that problem for very long, so some recent update caused it for me.

**Steps to reproduce:**
1. Start Discord if not already running
2. Suspend the pc
3. Wake up the pc

**Expected Result:**
Discord keeps running

**Actual Result:**
Discord crashes shortly after the pc is woken up

**Comment by Felting** [comment]
My error logs:
`[43:0509/070000.290184:ERROR:shared_context_state.cc(859)] SharedContextState context lost via ARB/EXT_robustness. Reset status = GL_UNKNOWN_CONTEXT_RESET_KHR
[43:0509/070000.290345:ERROR:gpu_service_impl.cc(988)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[5:0509/070000.307009:ERROR:gpu_process_host.cc(991)] GPU process exited unexpectedly: exit_code=8704
(electron) 'gpu-process-crashed event' is deprecated and will be removed. Please use 'child-process-gone event' instead.
`

**Comment by virtuallyunknown** [comment]
Currently facing the same issue on Linux Mint 21.1 Cinnamon with Discord v0.0.27.

Essentially when I wake up my computer from sleep, the Discord app will either close itself or it will appear in the system tray, but as soon as you click to restore it it will crash instead.

**Comment by guihkx** [comment]
Can anyone please revisit this?

It's been a while since the last comment here, and Discord has received many updates after that...

**Comment by cYDN48** [comment]
Would love to be able to give an update, but I don't think I can 😅

The previously posted logs mention the GPU, and I got myself a new PC with an AMD graphics card (had Nvidia before). So I don't think it means much when I say I can't reproduce it now

**Comment by guihkx** [comment]
No problem, thanks for replying, though.

I'll wait a bit longer to see if someone is able to revisit this, otherwise I'll close it.

**Comment by guihkx** [comment]
Closing, as the reporter seems available to retest this with the current version of Discord at this time.

If the problem still persists, I'd suggest you [report it to Discord devs](https://support.discord.com/hc/en-us/articles/1500006052822-How-to-Report-a-Bug).
