### ISSUE TITLE
Audio output crackling

### ISSUE THREAD

**Issue by Operativ** [flathub/com.discordapp.Discord#299]
Issue: Audio output (listening to people speak) has irregular crackling when somebody is speaking. Happens every 10-20 words.

System: Pop!_OS 22.04 (based on Ubuntu 22.04)

Notes: Other apps are functioning as normal. For example, flatpak Spotify has no audio crackling. Non-flatpak apps have no audio crackling.

**Comment by TingPing** [comment]
> Non-flatpak apps have no audio crackling.

But does non-flatpak Discord?

I don't think this is really actionable.

**Comment by Operativ** [comment]
I haven't tested with non-flatpak Discord, however I have noticed this after the most recent few updates to the flatpak version that recently came along with Discord's own soundboard feature. (There were like 2 or 3 same version Discord re-releases for flatpak).

**Comment by TingPing** [comment]
It is most likely just a Discord bug. Flatpak doesn't really interfere with how audio works. I doubt any library update was relevant too.

**Comment by Operativ** [comment]
> It is most likely just a Discord bug. Flatpak doesn't really interfere with how audio works. I doubt any library update was relevant too.

Quite frankly I would not be surprised about it being a Discord bug. As we say in my friend's group - Discord has unique bugs for each user configuration, so that everybody has a tailored experience... ;)

Well, I'll close this case then and continue looking on what could be causing this potential conflict.
