### ISSUE TITLE
Cursor Icon Problem!!

### ISSUE THREAD

**Issue by Syntist** [flathub/com.discordapp.Discord#3]
Cursor Icon changes when i hover over Discord (Flatpak Only), 
Was Experiencing the same issue on Arch Linux Aswell

Using Breeze Snow and Default Unity Icon.

As Shown in Video,
https://www.youtube.com/watch?v=t7sMh7vca1o

**Comment by TingPing** [comment]
Yes Flatpak does not package the Breeze icon theme yet.

**Comment by Syntist** [comment]
But it works ok on other apps, like Gnome-Twitch (flatpak), Corebird (flatpak), spotify also!!

**Comment by TingPing** [comment]
Just do document it, packaging Breeze_Snow cursor theme alone was not enough.

**Comment by TingPing** [comment]
This will probably be fixed once flatpak/freedesktop-sdk-images#39 lands
