### ISSUE TITLE
Somehow discord is able to see my game activity?

### ISSUE THREAD

**Issue by K4LCIFER** [flathub/com.discordapp.Discord#306]
From the README in this repo:
> Game Activity: This flatpak version of Discord cannot scan running processes to detect running games.
There is currently no workaround or solution for this limitation.

But somehow it is, as seen here.
![image](https://github.com/flathub/com.discordapp.Discord/assets/7829231/3e4e3472-f0ad-4798-a78a-83a274bd6ff9)
 It is showing what game is active, and in what state, and for how long. I have changed no permissions in flatseal; the permissions are left as they were when it was installed.

- OS: Arch Linux
- DE: KDE Plasm v5.27.5, Wayland
- Flatpak v1.15.4
- Discord (Flatpak) (com.discordapp.Discord) v0.0.27

**Comment by TingPing** [comment]
Discord cannot see running process. However specific applications that support it can talk to Discord itself over RPC. This is called "Rich Presence" I believe.
