### ISSUE TITLE
Nvidia Wayland only works with "--use-gl=desktop"

### ISSUE THREAD

**Issue by fishxz** [flathub/com.discordapp.Discord#311]
hey, 
as title says. without "--use-gl=desktop" discord fails to start on nvidia wayland.

please consider setting this as default (atleast for nvidia)

**Comment by TingPing** [comment]
When it finishes building can you test that PR ^

**Comment by fishxz** [comment]
something i noticed. even when running discord in wayland, it spawns an xwayland server. im sure im on wayland, because of the new window title bar.
![grafik](https://github.com/flathub/com.discordapp.Discord/assets/1385258/34641411-2283-4806-9f47-e5367aec5e27)
is this normal behavior?

**Comment by TingPing** [comment]
@fishxz Was this a recent change because of this PR and you use NVidia?

Please open a new issue either way. I suspect "desktop" GL is incompatible with Wayland, which requires EGL.

**Comment by fishxz** [comment]
@TingPing xprop says its a wayland window.
