### ISSUE TITLE
Recent revert breaks rendering on NVIDIA/Wayland

### ISSUE THREAD

**Issue by gnusenpai** [flathub/com.discordapp.Discord#316]
The recent commit (1ae26eb) completely breaks the rendering for me, where it was working flawlessly before.
I'm getting back-and-forth hitching and flickering similar to when using XWayland, most noticeable when keying text.
Using NVIDIA driver 535.104.05 with an RTX 3080 on Hyprland.

**Comment by TingPing** [comment]
Unfortunately it seems like both are broken for different groups of users.

**Comment by gnusenpai** [comment]
Since it seems that either `--use-gl=desktop` or `--disable-gpu-sandbox` breaks NVIDIA for different groups of people, one group of us is going to have to employ a manual workaround.

So these are steps I've taken to revert the change locally:

1. Place a copy of [discord.sh](https://github.com/flathub/com.discordapp.Discord/blob/58ae6e5d2cc3966356fabdf03e58bff8c088de7c/discord.sh) somewhere in your home folder, e.g., `~/app/discord/discord.sh`.
2. Add a filesystem override so that the sandbox can access it, using either Flatseal or the following command:
`$ flatpak override --filesystem=~/app/discord:ro com.discordapp.Discord`
3. Write a wrapper script to launch Discord using the local copy of `discord.sh`:
```sh
#!/bin/sh
exec flatpak run --command="${HOME}/app/discord/discord.sh" com.discordapp.Discord
```

**Comment by ZVNexus** [comment]
@gnusenpai Can you retest this after https://github.com/flathub/com.discordapp.Discord/commit/48212a07d473502aa50c7c32ede1fe40b40d428b ?

**Comment by gnusenpai** [comment]
I've been using the client with 48212a0 for the past few days and it's working great!
Nice find, @ZVNexus.
