### ISSUE TITLE
CKJ IME support

### ISSUE THREAD

**Issue by tommydrum** [flathub/com.discordapp.Discord#317]
It seems typing in Japanese does not work, and only types alphanumeric characters, despite the host OS being configured and accepting Japanese IME into other text boxes. I have also tested this on other flatpak apps (Brave, Joplin, etc), and they work correctly. The Discord flatpak specifically is not accepting typing in Japanese (with the Anthy IME).

As Japanese language-specific problems seem to always also affect Korean and Chinese, I'm assuming this also affects others, hence the CKJ title.

One other note: I'm on Fedora Silverblue, so this is with the ostree derivative of Flatpak. I have not tested this on a non-ostree-based system, so I can't tell you if this affects other distros, but as I have tested this on other flatpak apps, narrowing it down to this repo seems to be the right thing to do.

**Comment by nuleftus** [comment]
is your discord running in wayland? (usually does when you enable wayland for the flatpak)
electron, or chromium specifically, does not support text-input-v3 yet so IME in gnome wayland is especially off the table

you can disable wayland for discord using flatseal or something as a workaround

**Comment by guihkx** [comment]
Closed due to lack of follow up from reporter.

Please test this again with latest Discord and open a new issue if necessary.
