### ISSUE TITLE
Unable to open developer console

### ISSUE THREAD

**Issue by tempo660** [flathub/com.discordapp.Discord#318]
Hi. I'm running the Discord flatpak on Debian. It's working fine, but I seem to be unable to open the developer console. Normally the key to launch the dev console is `ctrl+shift+i` I believe. Was this functionality purposely disabled for security reasons for something? I'm trying to obtain my Authentication key in order to run [Discord Chat Exporter](https://github.com/Tyrrrz/DiscordChatExporter).

**Comment by TingPing** [comment]
We don't modify the application. This doesn't sound like anything specific to this package.

**Comment by TheJanzap** [comment]
You can enable the developer console by adding `"DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING": true`
 to `~/.var/app/com.discordapp.Discord/config/discord/settings.json`. CTRL+SHIFT+I works after restarting Discord
