### ISSUE TITLE
Inability to click on links

### ISSUE THREAD

**Issue by Dormanil** [flathub/com.discordapp.Discord#32]
I suspect this is another of these pesky issues that arise from Discord not being willing to work in a sandboxed environment, but any links that usually open up in a browser refuse to work.

**Comment by TingPing** [comment]
Do you not have `xdg-desktop-portal-gtk` installed on the host?

**Comment by FrozenDroid** [comment]
Same problem here. @TingPing I do have that installed.

**Comment by A6GibKm** [comment]
Same here, I also have `xdg-desktop-portal-gtk` installed.

**Comment by A6GibKm** [comment]
I will add that I am using the lattest Firefox.

**Comment by eiglow** [comment]
Links work fine for me in the Flatpak.

**Comment by Fuseteam** [comment]
dang so many stale issues

**Comment by A6GibKm** [comment]
Yes, seems completely fixed by now. @lionirdeadman do the thing.
