### ISSUE TITLE
Drop `org.kde.*` when Discord uses Electron >=23.3.0

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.discordapp.Discord#324]
This is no longer required with newer Electron and runtime

https://docs.flatpak.org/en/latest/desktop-integration.html#statusnotifier
    
> Most implementations of StatusNotifer have dropped this requirement
> but known exceptions to this are Electron versions older than 23.3.0.
    
Current version uses

```
Chrome/108.0.5359.215 Electron/22.3.24
```

**Comment by jntesteves** [comment]
Duplicate of #283

**Comment by bbhtt** [comment]
Indeed, thanks
