### ISSUE TITLE
"Uncaught exception: Error: Write EPIPE" on launch

### ISSUE THREAD

**Issue by MisterSheeple** [flathub/com.discordapp.Discord#328]
![image](https://github.com/flathub/com.discordapp.Discord/assets/27652712/e408042f-2543-44b4-b6aa-291c7b6e833e)

**Comment by TenSeventy7** [comment]
Same here. But only when launched using the DE, it launches fine when running `flatpak run com.discordapp.Discord` for me.

**Comment by Morethanevil** [comment]
Same for me too

**Comment by mvdan** [comment]
Started running into this as well. Funnily enough, for me it only happens hours after I've been using Discord, and it disappears if I restart. The error also repeats forever, meaning I have to quit the app to work around it.

**Comment by bruno-fs** [comment]
I had the same issue today on fedora 39 kinoite with wayland. Oddly enough, after restarting discord was working properly again.

**Comment by hyunlee1o** [comment]
I have the same issue all the time. Specially with updates

**Comment by rayzorben** [comment]
I'm getting this too on NixOS 

![image](https://github.com/flathub/com.discordapp.Discord/assets/7737834/2ab3cfaa-deb9-4085-bd33-6eda8e59b5da)

**Comment by Melchyore** [comment]
Same here on ZorinOS 17.

**Comment by guihkx** [comment]
Since this issue also affects non-Flatpak Discord (as per the NixOS comment above), there's nothing we can do here.

As always, my suggestion is to report such issues [directly to them](https://support.discord.com/hc/en-us/articles/1500006052822-How-to-Report-a-Bug) instead.
