### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Victor239** [flathub/com.discordapp.Discord#329]
Changelogs can be displayed on Flathub and within distro app updaters, all that's needed is an `.appdata`/[.metainfo.xml](https://docs.flatpak.org/en/latest/conventions.html#appdata-files) file. 

See these examples of another app's [appdata.xml](https://github.com/flathub/io.github.trigg.discover_overlay/blob/master/io.github.trigg.discover_overlay.appdata.xml), and how their changelog is [displayed on Flathub](https://flathub.org/en-GB/apps/io.github.trigg.discover_overlay).

**Comment by TingPing** [comment]
Volunteers welcomed to add information to them. It would be a rather manual process every update.

**Comment by guihkx** [comment]
I don't think Discord's [release notes](https://discord.com/tags/changelog) will be either useful or relevant, especially for Linux users.

**Comment by guihkx** [comment]
Closing due to the reason above.
