### ISSUE TITLE
Had to install CJK fonts separately

### ISSUE THREAD

**Issue by saif-ellafi** [flathub/com.discordapp.Discord#334]
Hi, I was getting missing characters and emojis in Discord from Flathub (OpenSUSE Tumbleweed).

After installing `google-noto-sans-cjk-fonts` it got fixed.

Just wanted to suggest it fixed or made part of the packagea for a better out of the box experience.

Best regards

**Comment by TingPing** [comment]
The package does bundle an emoji font: https://github.com/flathub/com.discordapp.Discord/blob/e568bb30418bcd650a42a108384eab1a5f2f0efc/com.discordapp.Discord.json#L31-L52

Not sure why it wasn't working for you.

**Comment by saif-ellafi** [comment]
It wasn't all, or really terrible, but some Discord servers used emojis on the channel names and those didn't work until I installed the one mentioned above.

![image](https://github.com/flathub/com.discordapp.Discord/assets/27952699/19468904-ee83-441e-a115-b52d04c75823)

**Comment by Vilianexe** [comment]
my guess, is that Twemoji is owned for twitter, and we all know mess that it become since a year ago, twemoji stop updating the opensource project(the emoji used in twitter itself has the new emojis spec 15, but not the github) https://github.com/twitter/twemoji/issues/570

**Comment by wdym-lmao** [comment]
We're still pushing twemoji updates [here](https://github.com/jdecked/twemoji)
