### ISSUE TITLE
Can't open portal file chooser

### ISSUE THREAD

**Issue by kevinlucasilva** [flathub/com.discordapp.Discord#335]
When I click to upload any file, don't open the file chooser for that.

![Peek 2023-10-24 12-17](https://github.com/flathub/com.discordapp.Discord/assets/103600951/136207d4-3dfd-43b7-8d6f-1e96b019ee29)

**Comment by OrderlyUnicode** [comment]
Same issue, running it in a terminal shows the following: `Gtk-WARNING **: 15:14:39.648: Can't open portal file chooser: GDbus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface "org.freedesktop.portal.FileChooser" on object at path /org/freedesktop/portal/desktop`

I have also tried giving Discord DBus session permissions via Flatseal, but this changed nothing.

**Comment by Vilianexe** [comment]
What is the system that's you'll running?, i'm using fedora Kinoite and it's working fine

**Comment by OrderlyUnicode** [comment]
Apologies for the late reply. I'm running Arch. Although, it seems there was an update that supposedly fixes it, so I'm going to need to try that in case it fixed the issue.

**Comment by guihkx** [comment]
This issue is a kinda old at this point, and I don't think it applies to newer versions of Discord. But if it does, please re-open it.
