### ISSUE TITLE
arm64 build

### ISSUE THREAD

**Issue by andirsun** [flathub/com.discordapp.Discord#339]
Hey! I am using my MacBook Pro m1 running official fedora 38 and I am wondering if there will be a arm64 version to use discord ?

**Comment by TingPing** [comment]
Discord currently has no arm builds.

**Comment by Redemption198** [comment]
> Hey! I am using my MacBook Pro m1 running official fedora 38 and I am wondering if there will be a arm64 version to use discord ?

You can use [ArmCord](https://github.com/ArmCord/ArmCord).

**Comment by TingPing** [comment]
That would be a different package entirely.
