### ISSUE TITLE
AppIndicator icon invisible

### ISSUE THREAD

**Issue by junglerobba** [flathub/com.discordapp.Discord#34]
https://github.com/flathub/com.discordapp.Discord/commit/0123b627a74d81f48e2ae330f4dee88166104645 
After this commit the AppIndicator icon (at least on Gnome, using the (K)StatusNotifierItem/AppIndicator Support extension) becomes invisible, can still be interacted with though.
Trying to launch Discord when no window is currently open launches a new instance instead of bringing up the current one, which also spawns another (also invisible) AppIndicator.
I built it reverting just this commit and both these issues did not exist.

**Comment by rafamoreira** [comment]
Same with System Tray Icons on Plasma.
