### ISSUE TITLE
Can't launch after the latest update

### ISSUE THREAD

**Issue by lethinhrider** [flathub/com.discordapp.Discord#341]
After the latest update, I'm stuck on Discord's spinning logo and can't open the app: 
![1](https://github.com/flathub/com.discordapp.Discord/assets/43519453/1363e96c-4fa2-4b9d-bc81-4c53488d8a36)

I tried reinstalling but still having this problem.
Here is my output in terminal:
[output.txt](https://github.com/flathub/com.discordapp.Discord/files/13205397/output.txt)
```
t@T:~$ flatpak run com.discordapp.Discord
Disabling updates already done
Discord 0.0.32
Starting app.
Starting updater.
2023-10-30T12:20:16.343Z [Modules] Modules initializing
2023-10-30T12:20:16.343Z [Modules] Distribution: remote
2023-10-30T12:20:16.343Z [Modules] Host updates: disabled
2023-10-30T12:20:16.344Z [Modules] Module updates: enabled
2023-10-30T12:20:16.344Z [Modules] Module install path: /home/t/.var/app/com.discordapp.Discord/config/discord/0.0.32/modules
2023-10-30T12:20:16.344Z [Modules] Module installed file path: /home/t/.var/app/com.discordapp.Discord/config/discord/0.0.32/modules/installed.json
2023-10-30T12:20:16.344Z [Modules] Module download path: /home/t/.var/app/com.discordapp.Discord/config/discord/0.0.32/modules/pending
splashScreen.initSplash(false)
blackbox: 2023-10-30T12:20:16.385Z 0 

----------------------------------------------
blackbox: 2023-10-30T12:20:16.419Z 1 Discord starting: {"releaseChannel":"stable","version":"0.0.32"}, modulepath: /home/t/.var/app/com.discordapp.Discord/config/discord/0.0.32/modules
blackbox: 2023-10-30T12:20:16.423Z 2 ✅ webContents.created web1 ""
blackbox: 2023-10-30T12:20:16.426Z 3 ✅ window.created win1 "discord"
[5:1030/192016.528776:ERROR:cert_verify_proc_builtin.cc(670)] CertVerifyProcBuiltin for redirector.gvt1.com failed:
----- Certificate i=3 (CN=GlobalSign Root CA,OU=Root CA,O=GlobalSign nv-sa,C=BE) -----
ERROR: No matching issuer found


[60:1030/192016.529216:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -202
splashScreen: SPLASH_SCREEN_READY
2023-10-30T12:20:16.585Z [Modules] No updates to install
splashScreen: no-pending-updates
2023-10-30T12:20:16.587Z [Modules] Host is up to date.
2023-10-30T12:20:16.587Z [Modules] Checking for module updates at https://discord.com/api/modules/stable/versions.json
splashScreen: checking-for-updates
splashScreen.updateSplashState checking-for-updates checking-for-updates {}
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'checking-for-updates' } ]
[5:1030/192016.683190:ERROR:cert_verify_proc_builtin.cc(670)] CertVerifyProcBuiltin for discord.com failed:
----- Certificate i=1 (CN=Cloudflare Inc ECC CA-3,O=Cloudflare\, Inc.,C=US) -----
ERROR: No matching issuer found


[60:1030/192016.683760:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -202
Error downloading with electron net: net::ERR_CERT_AUTHORITY_INVALID
Falling back to node net library..
[55:1030/192016.720151:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[55:1030/192016.722205:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[55:1030/192016.726821:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[55:1030/192016.728973:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[55:1030/192016.732795:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
blackbox: 2023-10-30T12:20:16.733Z 4 ✅ webContents.did-finish-load web1
[55:1030/192016.755840:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[55:1030/192016.758779:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
2023-10-30T12:20:16.854Z [Modules] No module updates available.
splashScreen: update-check-finished true 0 false
splashScreen.launchMainWindow: false
Optional module ./ElectronTestRpc was not included.
splashScreen.updateSplashState launching launching {}
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'launching' } ]
blackbox: 2023-10-30T12:20:16.984Z 5 ✅ webContents.created web2 ""
blackbox: 2023-10-30T12:20:17.003Z 6 ✅ window.created win2 "Discord"
[55:1030/192017.014310:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[5:1030/192017.065135:ERROR:cert_verify_proc_builtin.cc(670)] CertVerifyProcBuiltin for discordapp.com failed:
----- Certificate i=1 (CN=Cloudflare Inc ECC CA-3,O=Cloudflare\, Inc.,C=US) -----
ERROR: No matching issuer found


[60:1030/192017.065941:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -202
blackbox: 2023-10-30T12:20:17.149Z 7 ❌ webContents.did-fail-provisional-load web2: -202 ERR_CERT_AUTHORITY_INVALID
[WebContents] did-fail-load -202 ERR_CERT_AUTHORITY_INVALID retry in 1000 ms
(node:5) electron: Failed to load URL: https://discordapp.com/app?_=1698668416932 with error: ERR_CERT_AUTHORITY_INVALID
(Use `Discord --trace-warnings ...` to show where the warning was created)
blackbox: 2023-10-30T12:20:17.158Z 8 ❌ webContents.did-fail-load web2" -202 ERR_CERT_AUTHORITY_INVALID
mainScreen.on(did-finish-load) true false
blackbox: 2023-10-30T12:20:17.493Z 9 ✅ webContents.did-finish-load web2
[WebContents] retrying load https://discordapp.com/app?_=1698668416932
[60:1030/192019.872181:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -202
blackbox: 2023-10-30T12:20:19.881Z 10 ❌ webContents.did-fail-provisional-load web2: -202 ERR_CERT_AUTHORITY_INVALID
[WebContents] did-fail-load -202 ERR_CERT_AUTHORITY_INVALID retry in 2643.2672250586074 ms
(node:5) electron: Failed to load URL: https://discordapp.com/app?_=1698668416932 with error: ERR_CERT_AUTHORITY_INVALID
blackbox: 2023-10-30T12:20:19.888Z 11 ❌ webContents.did-fail-load web2" -202 ERR_CERT_AUTHORITY_INVALID
mainScreen.on(did-finish-load) true true
blackbox: 2023-10-30T12:20:20.082Z 12 ✅ webContents.did-finish-load web2
[WebContents] retrying load https://discordapp.com/app?_=1698668416932
[60:1030/192025.808255:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -202
blackbox: 2023-10-30T12:20:25.813Z 13 ❌ webContents.did-fail-provisional-load web2: -202 ERR_CERT_AUTHORITY_INVALID
[WebContents] did-fail-load -202 ERR_CERT_AUTHORITY_INVALID retry in 5849.590446735748 ms
(node:5) electron: Failed to load URL: https://discordapp.com/app?_=1698668416932 with error: ERR_CERT_AUTHORITY_INVALID
blackbox: 2023-10-30T12:20:25.819Z 14 ❌ webContents.did-fail-load web2" -202 ERR_CERT_AUTHORITY_INVALID
mainScreen.on(did-finish-load) true true
blackbox: 2023-10-30T12:20:26.019Z 15 ✅ webContents.did-finish-load web2
[WebContents] retrying load https://discordapp.com/app?_=1698668416932
[60:1030/192042.018938:ERROR:ssl_client_socket_impl.cc(982)] handshake failed; returned -1, SSL error code 1, net_error -202
blackbox: 2023-10-30T12:20:42.023Z 16 ❌ webContents.did-fail-provisional-load web2: -202 ERR_CERT_AUTHORITY_INVALID
[WebContents] did-fail-load -202 ERR_CERT_AUTHORITY_INVALID retry in 16118.060415843054 ms
(node:5) electron: Failed to load URL: https://discordapp.com/app?_=1698668416932 with error: ERR_CERT_AUTHORITY_INVALID
blackbox: 2023-10-30T12:20:42.030Z 17 ❌ webContents.did-fail-load web2" -202 ERR_CERT_AUTHORITY_INVALID
mainScreen.on(did-finish-load) true true
blackbox: 2023-10-30T12:20:42.239Z 18 ✅ webContents.did-finish-load web2
blackbox: 2023-10-30T12:20:50.945Z 19 window.close win1
blackbox: 2023-10-30T12:20:50.964Z 20 webContents.destroyed web1
blackbox: 2023-10-30T12:20:50.969Z 21 window.closed win1
blackbox: 2023-10-30T12:20:57.151Z 22 window.close win2
t@T:~$ 
```

**Comment by TingPing** [comment]
Maybe this is a host certificate problem.

Everything validates here, both in Discord, and on the host:

```
>gnutls-cli discordapp.com:443
Processed 354 CA certificate(s).
Resolving 'discordapp.com:443'...
Connecting to '162.159.129.233:443'...
- Certificate type: X.509
- Got a certificate list of 2 certificates.
- Certificate[0] info:
 - subject `CN=discordapp.com,O=Cloudflare\, Inc.,L=San Francisco,ST=California,C=US', issuer `CN=Cloudflare Inc ECC CA-3,O=Cloudflare\, Inc.,C=US', serial 0x0353e301a4c51f406d1e7154d46961df, EC/ECDSA key 256 bits, signed using ECDSA-SHA256, activated `2023-10-20 00:00:00 UTC', expires `2024-10-19 23:59:59 UTC', pin-sha256="9rkD7S2CXIJ5m8CZviXmo11c3O4nDS+YXT84lT9ReYo="
	Public Key ID:
		sha1:b40920cc3d49cd3c7227f3786f52558690f38b73
		sha256:f6b903ed2d825c82799bc099be25e6a35d5cdcee270d2f985d3f38953f51798a
	Public Key PIN:
		pin-sha256:9rkD7S2CXIJ5m8CZviXmo11c3O4nDS+YXT84lT9ReYo=

- Certificate[1] info:
 - subject `CN=Cloudflare Inc ECC CA-3,O=Cloudflare\, Inc.,C=US', issuer `CN=Baltimore CyberTrust Root,OU=CyberTrust,O=Baltimore,C=IE', serial 0x0a3787645e5fb48c224efd1bed140c3c, EC/ECDSA key 256 bits, signed using RSA-SHA256, activated `2020-01-27 12:48:08 UTC', expires `2024-12-31 23:59:59 UTC', pin-sha256="FEzVOUp4dF3gI0ZVPRJhFbSJVXR+uQmMH65xhs1glH4="
- Status: The certificate is trusted. 
- Description: (TLS1.3-X.509)-(ECDHE-X25519)-(ECDSA-SECP256R1-SHA256)-(AES-256-GCM)
- Session ID: 86:5C:A4:13:18:A8:20:92:7F:70:0F:F8:9E:FC:7E:AD:62:A8:26:EC:BA:6B:F7:1B:4C:50:6B:0D:93:C8:38:15
- Options: OCSP status request,
- Handshake was completed
```

**Comment by lethinhrider** [comment]
> Maybe this is a host certificate problem.
> 
> Everything validates here, both in Discord, and on the host:
> 
> ```
> >gnutls-cli discordapp.com:443
> Processed 354 CA certificate(s).
> Resolving 'discordapp.com:443'...
> Connecting to '162.159.129.233:443'...
> - Certificate type: X.509
> - Got a certificate list of 2 certificates.
> - Certificate[0] info:
>  - subject `CN=discordapp.com,O=Cloudflare\, Inc.,L=San Francisco,ST=California,C=US', issuer `CN=Cloudflare Inc ECC CA-3,O=Cloudflare\, Inc.,C=US', serial 0x0353e301a4c51f406d1e7154d46961df, EC/ECDSA key 256 bits, signed using ECDSA-SHA256, activated `2023-10-20 00:00:00 UTC', expires `2024-10-19 23:59:59 UTC', pin-sha256="9rkD7S2CXIJ5m8CZviXmo11c3O4nDS+YXT84lT9ReYo="
> 	Public Key ID:
> 		sha1:b40920cc3d49cd3c7227f3786f52558690f38b73
> 		sha256:f6b903ed2d825c82799bc099be25e6a35d5cdcee270d2f985d3f38953f51798a
> 	Public Key PIN:
> 		pin-sha256:9rkD7S2CXIJ5m8CZviXmo11c3O4nDS+YXT84lT9ReYo=
> 
> - Certificate[1] info:
>  - subject `CN=Cloudflare Inc ECC CA-3,O=Cloudflare\, Inc.,C=US', issuer `CN=Baltimore CyberTrust Root,OU=CyberTrust,O=Baltimore,C=IE', serial 0x0a3787645e5fb48c224efd1bed140c3c, EC/ECDSA key 256 bits, signed using RSA-SHA256, activated `2020-01-27 12:48:08 UTC', expires `2024-12-31 23:59:59 UTC', pin-sha256="FEzVOUp4dF3gI0ZVPRJhFbSJVXR+uQmMH65xhs1glH4="
> - Status: The certificate is trusted. 
> - Description: (TLS1.3-X.509)-(ECDHE-X25519)-(ECDSA-SECP256R1-SHA256)-(AES-256-GCM)
> - Session ID: 86:5C:A4:13:18:A8:20:92:7F:70:0F:F8:9E:FC:7E:AD:62:A8:26:EC:BA:6B:F7:1B:4C:50:6B:0D:93:C8:38:15
> - Options: OCSP status request,
> - Handshake was completed
> ```

Same with me:
t@T:~$ gnutls-cli discord.com
Processed 141 CA certificate(s).
Resolving 'discord.com:443'...
Connecting to '162.159.135.232:443'...
- Certificate type: X.509
- Got a certificate list of 2 certificates.
- Certificate[0] info:
 - subject `CN=discord.com,O=Cloudflare\, Inc.,L=San Francisco,ST=California,C=US', issuer `CN=Cloudflare Inc ECC CA-3,O=Cloudflare\, Inc.,C=US', serial 0x01b328515e9ca6ea72e196bb5515293e, EC/ECDSA key 256 bits, signed using ECDSA-SHA256, activated `2023-10-20 00:00:00 UTC', expires `2024-10-19 23:59:59 UTC', pin-sha256="EUhKxLX7pr2yGQOVMbTy1gkGHcASS2wuyLUKOhPyar4="
        Public Key ID:
                sha1:ad244242bf4a0c357ca3ad0c5193636d4b3bbfde
                sha256:11484ac4b5fba6bdb219039531b4f2d609061dc0124b6c2ec8b50a3a13f26abe
        Public Key PIN:
                pin-sha256:EUhKxLX7pr2yGQOVMbTy1gkGHcASS2wuyLUKOhPyar4=

- Certificate[1] info:
 - subject `CN=Cloudflare Inc ECC CA-3,O=Cloudflare\, Inc.,C=US', issuer `CN=Baltimore CyberTrust Root,OU=CyberTrust,O=Baltimore,C=IE', serial 0x0a3787645e5fb48c224efd1bed140c3c, EC/ECDSA key 256 bits, signed using RSA-SHA256, activated `2020-01-27 12:48:08 UTC', expires `2024-12-31 23:59:59 UTC', pin-sha256="FEzVOUp4dF3gI0ZVPRJhFbSJVXR+uQmMH65xhs1glH4="
- Status: The certificate is trusted. 
- Description: (TLS1.3-X.509)-(ECDHE-X25519)-(ECDSA-SECP256R1-SHA256)-(AES-256-GCM)
- Session ID: 25:59:04:2B:48:60:ED:B7:AF:6A:7B:76:1B:3F:AB:73:0D:E7:B3:1F:1A:83:59:36:C0:1C:9E:E5:4B:1B:80:07
- Options: OCSP status request,
- Handshake was completed

- Simple Client Mode:

- Peer has closed the GnuTLS connection
t@T:~$ 



t@T:~$ gnutls-cli discordapp.com
Processed 141 CA certificate(s).
Resolving 'discordapp.com:443'...
Connecting to '162.159.134.233:443'...
- Certificate type: X.509
- Got a certificate list of 2 certificates.
- Certificate[0] info:
 - subject `CN=discordapp.com,O=Cloudflare\, Inc.,L=San Francisco,ST=California,C=US', issuer `CN=Cloudflare Inc ECC CA-3,O=Cloudflare\, Inc.,C=US', serial 0x0353e301a4c51f406d1e7154d46961df, EC/ECDSA key 256 bits, signed using ECDSA-SHA256, activated `2023-10-20 00:00:00 UTC', expires `2024-10-19 23:59:59 UTC', pin-sha256="9rkD7S2CXIJ5m8CZviXmo11c3O4nDS+YXT84lT9ReYo="
        Public Key ID:
                sha1:b40920cc3d49cd3c7227f3786f52558690f38b73
                sha256:f6b903ed2d825c82799bc099be25e6a35d5cdcee270d2f985d3f38953f51798a
        Public Key PIN:
                pin-sha256:9rkD7S2CXIJ5m8CZviXmo11c3O4nDS+YXT84lT9ReYo=

- Certificate[1] info:
 - subject `CN=Cloudflare Inc ECC CA-3,O=Cloudflare\, Inc.,C=US', issuer `CN=Baltimore CyberTrust Root,OU=CyberTrust,O=Baltimore,C=IE', serial 0x0a3787645e5fb48c224efd1bed140c3c, EC/ECDSA key 256 bits, signed using RSA-SHA256, activated `2020-01-27 12:48:08 UTC', expires `2024-12-31 23:59:59 UTC', pin-sha256="FEzVOUp4dF3gI0ZVPRJhFbSJVXR+uQmMH65xhs1glH4="
- Status: The certificate is trusted. 
- Description: (TLS1.3-X.509)-(ECDHE-X25519)-(ECDSA-SECP256R1-SHA256)-(AES-256-GCM)
- Session ID: 52:E1:76:79:31:E4:A4:FE:68:44:AA:67:4F:D2:BF:B3:00:70:41:3B:6D:EB:52:23:AE:9E:E5:86:B9:57:23:8F
- Options: OCSP status request,
- Handshake was completed

- Simple Client Mode:

- Peer has closed the GnuTLS connection
t@T:~$

**Comment by nonki72** [comment]
$ flatpak run com.discordapp.Discord
2023/10/30 13:26:40 socat[3] E "/run/user/1000/app/com.discordapp.Discord/discord-ipc-0" exists
Disabling updates already done
ldconfig: Can't create temporary cache file /run/ld-so-cache-dir/805ff9f088045292b87c48a54bd2c619fa4dba0521d018b6a0fffb6db4cac66c.TZjyp4~: Not a directory
error: ldconfig failed, exit status 256
[5 preload-host-spawn-strategy] Failed to let stub process know of exit: Bad file descriptor (errno 9)

won't start when installed with USER or regular
no spash screen
version 0.0.32

**Comment by lethinhrider** [comment]
**[Solved]**
This bug caused by linuxbrew(homebrew on linux), the issue was the p11-kit process had been overriden by the linuxbrew one (installed as dependency for other development tools). Linuxbrew's p11-kit was not updating root CA and flatpak relied on it, and today was the day some root CAs expired.

**Solution**:
- Unlink linuxbrew p11-kit:
`brew unlink p11-kit`
- Reinstall p11-kit:
Depending on the distro you have different commands, I'm using Kubuntu so the command will be:
`sudo apt reinstall p11-kit`
- Then reboot or logout/login again
