### ISSUE TITLE
Discord fails to run with `Failed to call Spawn: org.freedesktop.DBus.Error.InvalidArgs: Could not find requesting pid`

### ISSUE THREAD

**Issue by RangHo** [flathub/com.discordapp.Discord#349]
Starting from today, Discord fails to launch with the message: `Failed to call Spawn: org.freedesktop.DBus.Error.InvalidArgs: Could not find requesting pid` on Void Linux with kernel 6.5.12..

Launching Discord with `-vv` argument does not give much more information, as Discord fails after Flatpak configures the container.

Here is the output of `flatpak run -v com.discordapp.Discord`:

```
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/rangho/.local/share/flatpak
F: Opening user flatpak installation at path /home/rangho/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/rangho/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/23.08/75d6f5f7daf46127a5e53608274216b46405b7197894970021bb7230113a30a7/files/lib32 does not exist
F: Cleaning up unused container id 2340721952
F: Cleaning up per-app-ID state for com.discordapp.Discord
F: Allocated instance id 3217103838
F: Add defaults in dir /com/discordapp/Discord/
F: Add locks in dir /com/discordapp/Discord/
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/rangho/.config/pulse/client.conf': Error opening file /home/rangho/.config/pulse/client.conf: No such file or directory
F: Pulseaudio user configuration file '/etc/pulse/client.conf': Error opening file /etc/pulse/client.conf: No such file or directory
F: Failed to run in transient scope: No systemd user session available, cgroups not available
F: Running 'bwrap --args 41 xdg-dbus-proxy --args=43'
F: Running 'bwrap --args 41 discord'
Disabling updates already done
[5 preload-host-spawn-strategy] Failed to call Spawn: org.freedesktop.DBus.Error.InvalidArgs: Could not find requesting pid
```

I first suspected that, since I am running D-Bus session bus as a user service, I failed to supply the correct variable (i.e. `DBUS_SESSION_BUS_PID`). I manually exported the variable with the correct PID and launched Discord, but it didn't work.

#### System Information

* OS: Void Linux with Kernel 6.5.12
* WM: Hyprland v0.29.1
* Graphical Server: Wayland

P.S. I have a hunch that this is an upstream issue, but I have no evidence to support my hypothesis.

**Comment by TingPing** [comment]
This is from zypak. Could be a chromium change broke it, or flatpak-portal on the host.

**Comment by RangHo** [comment]
I see. Is there a way to investigate the issue further? I skimmed through the code of zypak for a possible workaround but not quite sure if there is one.

**Comment by RangHo** [comment]
I have confirmed that the same issue happens in other apps based on `org.electronjs.Electron2.BaseApp` including Discord, Slack, and Obsidian. There exists an issue on `zypak` issue already at flathub/org.electronjs.Electron2.BaseApp#44, but not sure this is related.

I'll report this to upstream and see if this is related to the issue there.

**Comment by RangHo** [comment]
I did some investigations myself, and apparently the problem was a faulty D-Bus always returning errors to `zypak`'s `Spawn` request to desktop portal interfaces (confirmed with manual interface access using `d-spy`). A simple reconfiguration did the trick, and Electron apps work fine now.

Thank you so much for your help, and sorry for causing inconveniences!

Closing this issue.

**Comment by Strahinja** [comment]
> A simple reconfiguration did the trick, and Electron apps work fine now.

Can you share the "simple reconfiguration", so I can try to fix the issue I'm having with Ungoogled Chromium's flatpak?
