### ISSUE TITLE
discord flatpak appears to require systemd

### ISSUE THREAD

**Issue by dolphinoracle** [flathub/com.discordapp.Discord#35]
the flatpak appears to require systemd to operate, while the debs downloaded directly from discord do not.

**Comment by TingPing** [comment]
Why do you think that?

**Comment by dolphinoracle** [comment]
because when I use the same flatpak on a system booted up with sysvinit,
the launch of the discord flatpak fails with a /dev/shm permission error,
but when I switch to a systemd boot (same installed, OS, I've got 2 init
systems to choose from), the launch goes through OK.

just to note that many other flatpaks work just fine (kdenlive, abiword,
zoom, steam), so I'm presuming something particular with the discord
flatpak.

The console messages appear to indicate the failure occurs when discord is
looking for updates.

**Comment by dolphinoracle** [comment]
further info:

$ flatpak run com.discordapp.Discord
Discord 0.0.5
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path:
/home/dolphin/.var/app/com.discordapp.Discord/config/discord/0.0.5/modules
[Modules] Module installed file path:
/home/dolphin/.var/app/com.discordapp.Discord/config/discord/0.0.5/modules/installed.json
[Modules] Module download path:
/home/dolphin/.var/app/com.discordapp.Discord/config/discord/0.0.5/modules/pending
[3:0925/093842.200615:FATAL:shared_memory_posix.cc(288)] This is frequently
caused by incorrect permissions on /dev/shm.  Try 'sudo chmod 1777
/dev/shm' to fix.
#0 0x000001e57c8e <unknown>
#1 0x000001e6a80b <unknown>
#2 0x000001e3c723 <unknown>
#3 0x000000a83cac <unknown>
#4 0x0000010e9a3c <unknown>
#5 0x0000010e9850 <unknown>
#6 0x000000e07a6f <unknown>
#7 0x000000d1de95 <unknown>
#8 0x000000d20b3e <unknown>
#9 0x000000d20aa6 <unknown>
#10 0x000000a83590 <unknown>
#11 0x000000a83389 <unknown>
#12 0x000001e4bd4e <unknown>
#13 0x000001e6e34c <unknown>
#14 0x000001e6e668 <unknown>
#15 0x000001e6e9cb <unknown>
#16 0x000001df971a <unknown>
#17 0x7f12536f6c0e g_main_context_dispatch
#18 0x7f12536f6ea8 <unknown>
#19 0x7f12536f6f3c g_main_context_iteration
#20 0x000001df9606 <unknown>
#21 0x000001e6e0e7 <unknown>
#22 0x000001e29570 <unknown>
#23 0x000000c37ec8 <unknown>
#24 0x000000c37d15 <unknown>
#25 0x000000c1da7d <unknown>
#26 0x000000a9282e <unknown>
#27 0x0000007892d4 <unknown>
#28 0x0000007896e0 <unknown>
#29 0x000003b830a3 main
#30 0x7f125277e00b __libc_start_main
#31 0x00000059a0f9 <unknown>

**Comment by TingPing** [comment]
Well the error literally tells you whats wrong:

```
[3:0925/093842.200615:FATAL:shared_memory_posix.cc(288)] This is frequently
caused by incorrect permissions on /dev/shm.  Try 'sudo chmod 1777
/dev/shm' to fix.
```

Now why `/dev/shm` differs between systemd and sysvinit I don't know offhand but I don't think it is any problem with this package.

**Comment by dolphinoracle** [comment]
That's an good thought.

under sysvinit, /dev/shm is a link to /run/shm

under systemd, its just /dev/shm

**Comment by TingPing** [comment]
> under sysvinit, /dev/shm is a link to /run/shm

Hmm, perhaps report that difference to https://github.com/flatpak/flatpak

It can probably work around it.

**Comment by dolphinoracle** [comment]
10-4, thanks

**Comment by lionirdeadman** [comment]
This issue was closed upstream. Closing.
