### ISSUE TITLE
Latest update logged me out and doesn't follow system theme

### ISSUE THREAD

**Issue by Elaborendum** [flathub/com.discordapp.Discord#353]
Recently Discord updated, and upon opening it again, it logged me out of my accounts (and then logged back into the only account I have open in Firefox). Plus, now the title bar is just in the Default Adwaita Light theme and ignores my currently set theme.

I'm on Ubuntu 22.04. The default Yaru-dark themes don't seem to take effect either.

Setting my current theme manually through FlatSeal does seem to work, but its weird it got the theme on its own before.

The status bar menu also doesn't follow the system/app language anymore, now jut defaults to english.

**Comment by Vilianexe** [comment]
do you have the flatpak package org.gtk.Gtk3theme.Yaru-dark installed?

**Comment by Vilianexe** [comment]
looks like it was fixed upstream https://github.com/microsoft/vscode/issues/179448#issuecomment-1505597591 only need to wait for discord to update their electron version

**Comment by guihkx** [comment]
Regarding Discord not following the system theme, I have recently [tested that](https://github.com/flathub/com.discordapp.Discord/issues/184#issuecomment-2389438065) and it works here.

If this still isn't fixed for you, it's likely a problem with your distro (e.g. old packages) or desktop environment, and not with this Flatpak package.

Regarding the other issues you've mentioned, if you're still experiencing them, please open separate bug reports for each one.

Thank you.
