### ISSUE TITLE
Connected to discord Button.

### ISSUE THREAD

**Issue by survisatvik09** [flathub/com.discordapp.Discord#364]
In the VSCode i used this extension [crawl.discord-vscode](https://marketplace.visualstudio.com/items?itemName=icrawl.discord-vscode) and in the status bar where it says "connected to discord" it used to work where if i click it would disconnect from discord, but the button don't work anymore, i'm pressing the button but nothing happens. i'll send screenshot.

![image](https://github.com/flathub/com.discordapp.Discord/assets/141534549/e7c9fa86-4dd4-4048-8928-031a3f34a86b)

**Comment by TingPing** [comment]
It would take some effort to get working but it is possible. Documented here: https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)

**Comment by survisatvik09** [comment]
how do i do it thought?

**Comment by guihkx** [comment]
I believe this was already answered: You just need to carefully follow the steps described in the wiki. The exact steps will depend on your particular use-case.
