### ISSUE TITLE
Mouse cursor rendered at incorrect size

### ISSUE THREAD

**Issue by Subnet-Masked** [flathub/com.discordapp.Discord#369]
When moving the mouse cursor in and out of the discord window, it is rendered at the incorrect size when in the Discord window.

System:
Fedora 39
KDE 5.27.10
Graphics Platform: Wayland
Graphics: AMD Radeon RX6700 XT

Discord Flatpak version 0.0.42
Discord Version 264913

Issue occurs regardless of if the Wayland socket is enabled or disabled.

I have had a similar issue with other Flatpak applications that was solved by allowing `/usr/share/icons:ro` and `/home/subnet/.icons:ro` however this solution does not appear to work for Discord. Unsure what else to try.

**Comment by guihkx** [comment]
@Subnet-Masked Can you please retest this with latest Discord (0.70.0)?

**Comment by guihkx** [comment]
Closing, as the reporter does not seem available for a follow-up at this time.

Please retest this with the latest version of Discord, and open a new issue if the problem still exists.
