### ISSUE TITLE
Crashes after flash screen and dumps core 

### ISSUE THREAD

**Issue by bitterhalt** [flathub/com.discordapp.Discord#372]
I installed and tried to run Discord and it crashes after update screen
I also tested discord from arch repos and it starst with out any problems

System: Arch Linux
AMD Ryzen 5600
RX 6600
vulkan-radeon 1:23.3.5-1 
32GB memory
Sway 

Output for flatpak run com.discordapp.Discord:
`Disabling updates already done
Discord 0.0.43
[5:0215/004713.636700:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[5:0215/004713.636757:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting app.
Starting updater.
2024-02-14T22:47:13.660Z [Modules] Modules initializing
2024-02-14T22:47:13.660Z [Modules] Distribution: remote
2024-02-14T22:47:13.660Z [Modules] Host updates: disabled
2024-02-14T22:47:13.660Z [Modules] Module updates: enabled
2024-02-14T22:47:13.660Z [Modules] Module install path: /home/bazz/.var/app/com.discordapp.Discord/config/discord/0.0.43/modules
2024-02-14T22:47:13.660Z [Modules] Module installed file path: /home/bazz/.var/app/com.discordapp.Discord/config/discord/0.0.43/modules/installed.json
2024-02-14T22:47:13.660Z [Modules] Module download path: /home/bazz/.var/app/com.discordapp.Discord/config/discord/0.0.43/modules/pending
splashScreen.initSplash(false)
blackbox: 2024-02-14T22:47:13.672Z 0 

----------------------------------------------
blackbox: 2024-02-14T22:47:13.684Z 1 Discord starting: {"releaseChannel":"stable","version":"0.0.43"}, modulepath: /home/bazz/.var/app/com.discordapp.Discord/config/discord/0.0.43/modules
blackbox: 2024-02-14T22:47:13.685Z 2 ✅ webContents.created web1 ""
blackbox: 2024-02-14T22:47:13.686Z 3 ✅ window.created win1 "discord"
splashScreen: SPLASH_SCREEN_READY
2024-02-14T22:47:13.881Z [Modules] No updates to install
splashScreen: no-pending-updates
2024-02-14T22:47:13.881Z [Modules] Host is up to date.
2024-02-14T22:47:13.881Z [Modules] Checking for module updates at https://discord.com/api/modules/stable/versions.json
splashScreen: checking-for-updates
splashScreen.updateSplashState checking-for-updates checking-for-updates {}
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'checking-for-updates' } ]
2024-02-14T22:47:13.888Z [Modules] Module update available: discord_desktop_core@1 [installed: 0]
2024-02-14T22:47:13.888Z [Modules] Module update available: discord_erlpack@1 [installed: 0]
2024-02-14T22:47:13.888Z [Modules] Module update available: discord_spellcheck@1 [installed: 0]
2024-02-14T22:47:13.888Z [Modules] Module update available: discord_utils@1 [installed: 0]
2024-02-14T22:47:13.888Z [Modules] Module update available: discord_voice@1 [installed: 0]
splashScreen: update-check-finished true 5 false
2024-02-14T22:47:13.888Z [Modules] Fetching discord_desktop_core@1 from https://discord.com/api/modules/stable/discord_desktop_core/1
2024-02-14T22:47:13.888Z [Modules] Streaming discord_desktop_core@1 to /home/bazz/.var/app/com.discordapp.Discord/config/discord/0.0.43/modules/pending/discord_desktop_core-1.zip
splashScreen: downloading-module discord_desktop_core 1 5
splashScreen.updateSplashState downloading-updates downloading-updates { current: 1, total: 5 }
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'downloading-updates', current: 1, total: 5 } ]
blackbox: 2024-02-14T22:47:13.942Z 4 ✅ webContents.did-finish-load web1
[54:0215/004713.944269:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[54:0215/004713.944354:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[54:0215/004713.944411:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[54:0215/004713.944460:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[54:0215/004713.944513:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[54:0215/004713.972559:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[54:0215/004713.973372:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
/app/bin/com.discordapp.Discord: line 17:     5 Segmentation fault      (core dumped) env TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/discord/Discord $FLAGS "$@"
2024/02/15 00:47:14 socat[3] W exiting on signal 15`

### Core dump
` Process 9079 (Discord) of user 1000 dumped core.
                                                    
                                                    Stack trace of thread 23:
                                                    #0  0x00007177f42db449 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x60449)
                                                    #1  0x00007177f42fe426 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x83426)
                                                    #2  0x00007177f42d8656 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x5d656)
                                                    #3  0x00005e261add01c7 n/a (/app/discord/Discord + 0x65691c7)
                                                    #4  0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #5  0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #6  0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #7  0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #8  0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #9  0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #10 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #11 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #12 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #13 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #14 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #15 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #16 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #17 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #18 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #19 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #20 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #21 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #22 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #23 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #24 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #25 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #26 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #27 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #28 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #29 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #30 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #31 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #32 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #33 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #34 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #35 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #36 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #37 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #38 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #39 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #40 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #41 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #42 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #43 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #44 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #45 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #46 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #47 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #48 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #49 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #50 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #51 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #52 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #53 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #54 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #55 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #56 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #57 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #58 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #59 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #60 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #61 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #62 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    #63 0x00005e261add0a71 n/a (/app/discord/Discord + 0x6569a71)
                                                    
                                                    Stack trace of thread 5:
                                                    #0  0x00007177f438405d n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x10905d)
                                                    #1  0x00007177f577522e n/a (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7600.6 + 0xbe22e)
                                                    #2  0x00007177f5715513 n/a (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7600.6 + 0x5e513)
                                                    #3  0x00005e2619d62465 n/a (/app/discord/Discord + 0x54fb465)
                                                    #4  0x00005e2619dc125c n/a (/app/discord/Discord + 0x555a25c)
                                                    #5  0x00005e2619d84058 n/a (/app/discord/Discord + 0x551d058)
                                                    #6  0x00005e2618e96b4f n/a (/app/discord/Discord + 0x462fb4f)
                                                    #7  0x00005e2618e98a72 n/a (/app/discord/Discord + 0x4631a72)
                                                    #8  0x00005e2618e941ed n/a (/app/discord/Discord + 0x462d1ed)
                                                    #9  0x00005e2616d2d2e4 n/a (/app/discord/Discord + 0x24c62e4)
                                                    #10 0x00005e2616d2e69f n/a (/app/discord/Discord + 0x24c769f)
                                                    #11 0x00005e2616d2e44f n/a (/app/discord/Discord + 0x24c744f)
                                                    #12 0x00005e2616d2b582 n/a (/app/discord/Discord + 0x24c4582)
                                                    #13 0x00005e2616d2bcb5 n/a (/app/discord/Discord + 0x24c4cb5)
                                                    #14 0x00005e2616a7055d n/a (/app/discord/Discord + 0x220955d)
                                                    #15 0x00007177f603430b n/a (/app/lib/libzypak-preload-host-spawn-strategy.so + 0xad30b)
                                                    #16 0x00007177f42a308a n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x2808a)
                                                    #17 0x00007177f42a314b n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x2814b)
                                                    #18 0x00007177f603459d n/a (/app/lib/libzypak-preload-host-spawn-strategy.so + 0xad59d)
                                                    #19 0x00005e261670502a n/a (/app/discord/Discord + 0x1e9e02a)
                                                    ELF object binary architecture: AMD x86-64`

**Comment by guihkx** [comment]
Can you please retest this with latest Discord (0.0.70)?
