### ISSUE TITLE
Different cursor theme only on Discord

### ISSUE THREAD

**Issue by Yoru-cyber** [flathub/com.discordapp.Discord#375]
I know this is a common problem on flatpak because of the sandbox and i already fixed it in all apps except Discord.
I fixed globally by using: 
`flatpak --user override --filesystem=/home/$USER/.icons/:ro`
`flatpak --user override --filesystem=/usr/share/icons/:ro`
But on Discord this solution doesn't work and i can't imagine why.
I have already tried:
`flatpak --user override com.discordapp.Discord --filesystem=/home/$USER/.icons/:ro`
And it hasn't worked either.
My system:
OS: openSUSE Tumbleweed 20240225 x86_64
DE: KDE Plasma 5.27.10
Kernel: 6.7.6-1-default
Flatpak 1.15.6
com.discordapp.Discord 0.0.43  stable

**Comment by samjong05** [comment]
remove XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons

**Comment by adpawr** [comment]
I have configured cursor just for me, so adding this ENV worked:
`XCURSOR_PATH=/run/host/user-share/icons:/home/me/.icons:ro`

**Comment by Yoru-cyber** [comment]
@samjong05 i did and now it works perfect, thank you!!
