### ISSUE TITLE
crash at splash screen since update to version 0.0.44

### ISSUE THREAD

**Issue by emcee-101** [flathub/com.discordapp.Discord#378]
System:
ryzen 5 3600
rtx 3060 (proprietary driver)
linux 6.7.9 arch linux
plasma 6

Discord crashes when starting since the update to 0.0.44.

The output:

> ➜  ~ flatpak run com.discordapp.Discord
> Disabling updates already done
> Discord 0.0.44
> [5:0310/004101.973195:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
> [5:0310/004101.973262:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
> Starting app.
> Starting updater.
> 2024-03-09T23:41:02.003Z [Modules] Modules initializing
> 2024-03-09T23:41:02.003Z [Modules] Distribution: remote
> 2024-03-09T23:41:02.003Z [Modules] Host updates: disabled
> 2024-03-09T23:41:02.003Z [Modules] Module updates: enabled
> 2024-03-09T23:41:02.003Z [Modules] Module install path: /home/niha/.var/app/com.discordapp.Discord/config/discord/0.0.44/modules
> 2024-03-09T23:41:02.003Z [Modules] Module installed file path: /home/niha/.var/app/com.discordapp.Discord/config/discord/0.0.44/modules/installed.json
> 2024-03-09T23:41:02.004Z [Modules] Module download path: /home/niha/.var/app/com.discordapp.Discord/config/discord/0.0.44/modules/pending
> splashScreen.initSplash(false)
> blackbox: 2024-03-09T23:41:02.025Z 0 
> 
> ----------------------------------------------
> blackbox: 2024-03-09T23:41:02.041Z 1 Discord starting: {"releaseChannel":"stable","version":"0.0.44"}, modulepath: /home/niha/.var/app/com.discordapp.Discord/config/discord/0.0.44/modules
> blackbox: 2024-03-09T23:41:02.047Z 2 ✅ webContents.created web1 ""
> blackbox: 2024-03-09T23:41:02.052Z 3 ✅ window.created win1 "discord"
> MESA-LOADER: failed to retrieve device information
> MESA-LOADER: failed to open nvidia-drm: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/nvidia-drm_dri.so: Kann die Shared-Object-Datei nicht öffnen: Keine Berechtigung (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri, suffix _dri)
> MESA-LOADER: failed to open kms_swrast: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/kms_swrast_dri.so: Kann die Shared-Object-Datei nicht öffnen: Keine Berechtigung (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri, suffix _dri)
> MESA-LOADER: failed to open swrast: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/swrast_dri.so: Kann die Shared-Object-Datei nicht öffnen: Keine Berechtigung (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri, suffix _dri)
> splashScreen: SPLASH_SCREEN_READY
> splashScreen.webContentsSend: SPLASH_SCREEN_QUOTE SPLASH_SCREEN_QUOTE [ 'Hold Tight — Loading Discord' ]
> 2024-03-09T23:41:02.283Z [Modules] No updates to install
> splashScreen: no-pending-updates
> 2024-03-09T23:41:02.284Z [Modules] Host is up to date.
> 2024-03-09T23:41:02.284Z [Modules] Checking for module updates at https://discord.com/api/modules/stable/versions.json
> splashScreen: checking-for-updates
> splashScreen.updateSplashState checking-for-updates checking-for-updates {}
> splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'checking-for-updates' } ]
> 2024-03-09T23:41:02.341Z [Modules] No module updates available.
> splashScreen: update-check-finished true 0 false
> splashScreen.launchMainWindow: false
> Optional module ./ElectronTestRpc was not included.
> splashScreen.updateSplashState launching launching {}
> splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'launching' } ]
> [5:0310/004102.417542:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
> [5:0310/004102.417579:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
> blackbox: 2024-03-09T23:41:02.417Z 4 ✅ webContents.created web2 ""
> [5:0310/004102.417600:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
> [54:0310/004102.419995:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglMakeCurrent: Failed to make the GLX context current
> [54:0310/004102.420089:ERROR:gl_context_egl.cc(473)] eglMakeCurrent failed with error EGL_CONTEXT_LOST
> blackbox: 2024-03-09T23:41:02.420Z 5 ✅ window.created win2 "Discord"
> [5:0310/004103.071103:ERROR:gpu_process_host.cc(991)] GPU process exited unexpectedly: exit_code=139
> (electron) 'gpu-process-crashed event' is deprecated and will be removed. Please use 'child-process-gone event' instead.
> notificationScreen.webContentsSend: win is invalid undefined.
> child-process-gone! child: GPU (undefined) exitCode: 139
> blackbox: 2024-03-09T23:41:03.077Z 6 before-quit
> blackbox: 2024-03-09T23:41:03.086Z 7 window.close win1
> 2024/03/10 00:41:03 socat[3] W exiting on signal 15
> 
>

**Comment by emcee-101** [comment]
seems to be different output than here: https://github.com/flathub/com.discordapp.Discord/issues/372 
so I made a new issue

**Comment by pduggi-cf** [comment]
I seem to hit a very similar issue

```
Disabling updates already done
Discord 0.0.44
Gtk-Message: 12:22:37.520: Failed to load module "xapp-gtk3-module"
Gtk-Message: 12:22:37.520: Failed to load module "canberra-gtk-module"
[5:0311/122237.551618:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[5:0311/122237.551664:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting app.
Starting updater.
2024-03-11T06:52:37.573Z [Modules] Modules initializing
2024-03-11T06:52:37.573Z [Modules] Distribution: remote
2024-03-11T06:52:37.573Z [Modules] Host updates: disabled
2024-03-11T06:52:37.574Z [Modules] Module updates: enabled
2024-03-11T06:52:37.574Z [Modules] Module install path: /home/prashanth/.var/app/com.discordapp.Discord/config/discord/0.0.44/modules
2024-03-11T06:52:37.574Z [Modules] Module installed file path: /home/prashanth/.var/app/com.discordapp.Discord/config/discord/0.0.44/modules/installed.json
2024-03-11T06:52:37.574Z [Modules] Module download path: /home/prashanth/.var/app/com.discordapp.Discord/config/discord/0.0.44/modules/pending
splashScreen.initSplash(false)
blackbox: 2024-03-11T06:52:37.588Z 0 

----------------------------------------------
blackbox: 2024-03-11T06:52:37.638Z 1 Discord starting: {"releaseChannel":"stable","version":"0.0.44"}, modulepath: /home/prashanth/.var/app/com.discordapp.Discord/config/discord/0.0.44/modules
blackbox: 2024-03-11T06:52:37.642Z 2 ✅ webContents.created web1 ""
blackbox: 2024-03-11T06:52:37.644Z 3 ✅ window.created win1 "discord"
splashScreen: SPLASH_SCREEN_READY
splashScreen.webContentsSend: SPLASH_SCREEN_QUOTE SPLASH_SCREEN_QUOTE [ 'Hold Tight — Loading Discord' ]
2024-03-11T06:52:37.716Z [Modules] No updates to install
splashScreen: no-pending-updates
2024-03-11T06:52:37.716Z [Modules] Host is up to date.
2024-03-11T06:52:37.717Z [Modules] Checking for module updates at https://discord.com/api/modules/stable/versions.json
splashScreen: checking-for-updates
splashScreen.updateSplashState checking-for-updates checking-for-updates {}
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'checking-for-updates' } ]
2024-03-11T06:52:37.725Z [Modules] No module updates available.
splashScreen: update-check-finished true 0 false
splashScreen.launchMainWindow: false
Optional module ./ElectronTestRpc was not included.
splashScreen.updateSplashState launching launching {}
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'launching' } ]
[5:0311/122237.790185:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[5:0311/122237.790230:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
blackbox: 2024-03-11T06:52:37.790Z 4 ✅ webContents.created web2 ""
[5:0311/122237.790264:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
blackbox: 2024-03-11T06:52:37.792Z 5 ✅ window.created win2 "Discord"
[54:0311/122237.794241:ERROR:skia_output_surface_impl.cc(948)] 
  surface_size=1280x65508
  format=4
  color_type=4
  backend_format.isValid()=1
  backend_format.backend()=0
  backend_format.asGLFormat()=1
  backend_format.asVkFormat()=0
  backend_format.asVkFormat() vk_format=0
  sample_count=1
  surface_origin=1
  willGlFBO0=1
[54:0311/122237.795660:ERROR:skia_output_device_gl.cc(275)] Couldn't create surface:
  abandoned()=0
  color_type=0
  framebuffer_info.fFBOID=0
  framebuffer_info.fFormat=0
  color_space={primaries:BT709, transfer:SRGB, matrix:RGB, range:FULL}
  size=0x0
[54:0311/122237.795762:ERROR:gpu_service_impl.cc(988)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[5:0311/122237.802620:ERROR:gpu_process_host.cc(991)] GPU process exited unexpectedly: exit_code=8704
(electron) 'gpu-process-crashed event' is deprecated and will be removed. Please use 'child-process-gone event' instead.
notificationScreen.webContentsSend: win is invalid undefined.
child-process-gone! child: GPU (undefined) exitCode: 8704
blackbox: 2024-03-11T06:52:37.805Z 6 before-quit
blackbox: 2024-03-11T06:52:37.838Z 7 window.close win1
2024/03/11 12:22:37 socat[3] W exiting on signal 15

```

**Comment by SHSLEzra** [comment]
Same issue here on EndeavourOS

**Comment by guihkx** [comment]
Can someone please retest this with latest Discord (0.0.70)?

**Comment by KernelFreeze** [comment]
I have the same problem on Discord 0.0.71
<details>

<summary>Log</summary>

```
CDM completed with status: cdm-ready-success
blackbox: 2024-10-12T22:11:57.960Z 1 Discord starting: {"releaseChannel":"stable","version":"0.0.71"}, modulepath: /home/celeste/.var/app/com.discordapp.Discord/config/discord/0.0.71/modules
blackbox: 2024-10-12T22:11:57.966Z 2 ✅ webContents.created web1 "index.html"
blackbox: 2024-10-12T22:11:57.973Z 3 ✅ window.created win1 "discord"
splashScreen: SPLASH_SCREEN_READY
splashScreen.webContentsSend: SPLASH_SCREEN_QUOTE SPLASH_SCREEN_QUOTE [ 'Hold Tight — Loading Discord' ]
2024-10-12T22:11:58.081Z [Modules] No updates to install
splashScreen: no-pending-updates
2024-10-12T22:11:58.081Z [Modules] Host is up to date.
2024-10-12T22:11:58.081Z [Modules] Checking for module updates at https://discord.com/api/modules/stable/versions.json
splashScreen: checking-for-updates
splashScreen.updateSplashState checking-for-updates checking-for-updates {}
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'checking-for-updates' } ]
2024-10-12T22:11:58.088Z [Modules] No module updates available.
splashScreen: update-check-finished true 0 false
splashScreen.launchMainWindow: false
Optional module ./ElectronTestRpc was not included.
splashScreen.updateSplashState launching launching {}
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'launching' } ]
blackbox: 2024-10-12T22:11:58.160Z 4 ✅ webContents.created web2 ""
blackbox: 2024-10-12T22:11:58.176Z 5 ✅ window.created win2 "Discord"
blackbox: 2024-10-12T22:11:58.183Z 6 ✅ webContents.did-finish-load web1
17:11:58.594 › Unrecognized Content-Security-Policy directive 'prefetch-src'.
17:11:58.939 › [FAST CONNECT] wss://gateway.discord.gg/?encoding=etf&v=9&compress=zstd-stream, encoding: etf, version: 9
17:11:59.263 › Initializing voice engine with audio subsystem: standard
[WebContents] crashed (reason: crashed, exitCode: 139)... reloading
Optional module ./ElectronTestRpc was not included.
blackbox: 2024-10-12T22:11:59.323Z 7 ❌ render-process-gone { reason: 'crashed', exitCode: 139 }
blackbox: 2024-10-12T22:11:59.339Z 8 window.closed win2
blackbox: 2024-10-12T22:11:59.346Z 9 ✅ webContents.created web3 ""
blackbox: 2024-10-12T22:11:59.352Z 10 ✅ window.created win3 "Discord"
blackbox: 2024-10-12T22:11:59.359Z 11 webContents.destroyed web2
17:11:59.390 › Unrecognized Content-Security-Policy directive 'prefetch-src'.
17:11:59.725 › [FAST CONNECT] wss://gateway.discord.gg/?encoding=etf&v=9&compress=zstd-stream, encoding: etf, version: 9
17:12:00.043 › Initializing voice engine with audio subsystem: standard
[WebContents] double crashed (reason: crashed, exitCode: 139)... RIP =(
notificationScreen.webContentsSend: win is invalid undefined.
blackbox: 2024-10-12T22:12:00.093Z 12 ❌ render-process-gone { reason: 'crashed', exitCode: 139 }
blackbox: 2024-10-12T22:12:00.101Z 13 before-quit
2024/10/12 17:12:00 socat[4] W exiting on signal 15
```
</details>

**Comment by guihkx** [comment]
@KernelFreeze What's your distro and GPU model? Also, did you run with `--socket=wayland`?

**Comment by KernelFreeze** [comment]
> @KernelFreeze What's your distro and GPU model? Also, did you run with `--socket=wayland`?

Distro: Fedora Silverblue
GPU: Nvidia RTX 3080

And yes, I tried using wayland, on XWayland it doesn't crash

**Comment by guihkx** [comment]
Then I think your problem is more related to #413 instead.

At least I'm assuming this isn't Wayland-related, but I'm still waiting for a confirmation from the person who reported this...

**Comment by guihkx** [comment]
Closing, as the reporter does not seem available for a follow-up at this time.

In any case, issues like crashes and poor performance are out of our control most of the times, so I always suggest people to report those [directly to Discord devs](https://support.discord.com/hc/en-us/articles/1500006052822-How-to-Report-a-Bug) instead.
