### ISSUE TITLE
Discord 0.0.46 Fails to start as Wayland Client

### ISSUE THREAD

**Issue by sfalken** [flathub/com.discordapp.Discord#382]
When launching Discord 0.0.46 as a wayland client, rather than an X11 one, it fails to start, with the following Error:

```
[sfalken@mustang ~]$ flatpak run --socket=wayland com.discordapp.Discord
Disabling updates already done
Discord 0.0.46
[5:0322/133747.437344:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY
[5:0322/133747.437377:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.
[0322/133747.446235:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
/app/bin/com.discordapp.Discord: line 17:     5 Aborted                 (core dumped) env TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/discord/Discord $FLAGS "$@"
2024/03/22 13:37:48 socat[3] W exiting on signal 15
```

Operating System:  openSUSE Kalpa
Kernel: 6.8.1
Graphics:  In Kernel amdgpu driver
Flatpak Version: 1.15.6
Desktop: KDE Plasma 6.0.2

**Comment by aleasto** [comment]
That is expected, only the x11 socket is exposed: https://github.com/flathub/com.discordapp.Discord/blob/b46a5f24a1963601ac751bfb48c9557ab1ec6e2b/com.discordapp.Discord.json#L15

But you can override the permissions locally

**Comment by sfalken** [comment]
On 3/23/24 07:04, Alessandro Astone wrote:
> That is expected, only the x11 socket is exposed: 
> https://github.com/flathub/com.discordapp.Discord/blob/b46a5f24a1963601ac751bfb48c9557ab1ec6e2b/com.discordapp.Discord.json#L15 <https://github.com/flathub/com.discordapp.Discord/blob/b46a5f24a1963601ac751bfb48c9557ab1ec6e2b/com.discordapp.Discord.json#L15>
> 
> But you can override the permissions locally
> 
> —
Right, The wayland socket is there, and enabled in kcm_flatpak, if I 
disable the X11 socket, or only set the "Fallback to X11 Windowing 
System" Discord fails to launch at all.

Discord isn't the "only" flatpak I have that's not running on wayland, 
but it is one of them that *was* working in the past, and isn't now.

```
***@***.*** ~]$ flatpak override --user --show com.discordapp.Discord
[Context]
filesystems=/home/sfalken/Nextcloud:ro;
sockets=wayland;
```

**Comment by lionirdeadman** [comment]
Discord even when run to use Wayland rendering will crash because it needs X11 for screensharing. You need to give it both X11 and Wayland for it to run.

**Comment by sfalken** [comment]
Ok, good to know.   But with both enabled, it's still running as an X11 client.    If that's the intended behavior, and discord is just going to remain needing XWayland, that's fine, I'd just prefer to be running it as a Wayland client.

Are there some flags that I'm missing, that I need to setup a custom .desktop file for or something?    Because I *have* had it running fine as a Wayland client in the past.

**Comment by lionirdeadman** [comment]
With our script (see here: https://github.com/flathub/com.discordapp.Discord/blob/master/discord.sh#L11), if the wayland socket is there, it does *render* as a wayland client though it has access to X11 functionality.

Using GNOME's looking glass, I can confirm this to be working as intended - as in, the Discord window registers as a wayland window, not an xwayland one.

**Comment by sfalken** [comment]
So my general "quick" verification to see if something is running as a Wayland or X11 client, is to fire up `xeyes` and see if it follows the mouse while I'm over that window.     I don't have GNOME on this machine to check (and I'm not sure how to check that with Plasma, as I don't believe theres an inspector like `Looking Glass`), any chance you could check that?   It might be a false positive, since the X11 socket is active.

**Comment by aleasto** [comment]
I can also confirm that with `X11 Windowing System` **and** `Wayland Windowing System` enabled in `kcm_flatpak` (Plasma 5) my Discord runs as a native Wayland client.

**Comment by sfalken** [comment]
> I can also confirm that with `X11 Windowing System` **and** `Wayland Windowing System` enabled in `kcm_flatpak` (Plasma 5) my Discord runs as a native Wayland client.

Ok, so it must be something "local", with Plasma6 causing the issue.

**Comment by lionirdeadman** [comment]
I'm a bit lazy so I don't want to install xeyes but it would be logical for xeyes to be triggered by the Discord client. It's the same reason why Discord running as a wayland client can still screenshare itself through xwayland.

**Comment by sfalken** [comment]
> I'm a bit lazy so I don't want to install xeyes but it would be logical for xeyes to be triggered by the Discord client. It's the same reason why Discord running as a wayland client can still screenshare itself through xwayland.

No worries, I'm still trying to figure out how to verify this thing is actually running as a Wayland client.   I've had our lead KDE maintainer tell me that if `xprop` says it's running as an XWayland client, then it's running as an XWayland client, but I'm not so sure now, that I'm not seeing a false positive here, I'm trying to get some other folks running Plasma6 on other platforms to confirm.

**Comment by tyrone-sudeium** [comment]
Having the same issue, I've also given Discord _both_ X11 and Wayland permission in Flatseal / KDE Flatpak Permissions, and in the past (i.e Plasma 5) this would result in a Wayland window that uses X11 for screen sharing and global hotkeys etc.

I'm _pretty_ sure it's Plasma 6 related, not 0.0.46 related, as when I downgrade to e55db501 it still happens. It's very easy to tell in my case as the scrollwheel behaviour for an XWayland application is vastly different to a Wayland one, but in any case I can verify with `xwininfo` that it's definitely XWayland.

**Comment by pedrovanzella** [comment]
> > I can also confirm that with `X11 Windowing System` **and** `Wayland Windowing System` enabled in `kcm_flatpak` (Plasma 5) my Discord runs as a native Wayland client.
> 
> Ok, so it must be something "local", with Plasma6 causing the issue.

This PR should fix that for you: https://github.com/flathub/com.discordapp.Discord/pull/377

**Comment by sfalken** [comment]
Excellent, thanks!

**Comment by guihkx** [comment]
I think this is fixed? Let me know if it isn't, though. I'm just trying to clean up some stale issues on the repo.
