### ISSUE TITLE
How to pass flag --disable-features=WaylandFractionalScaleV1 when I opt in Wayland?

### ISSUE THREAD

**Issue by ankworld** [flathub/com.discordapp.Discord#385]
With latest discord, Electron version has changed. When I use Wayland with Gnome 45, It's blur. 

How to pass --disable-features=WaylandFractionalScaleV1 flag.

ref: https://github.com/microsoft/vscode/issues/192590

**Comment by ankworld** [comment]
Oh! I see customize FLAGS by ENV in Discord Canary repo. That is what I want.

**Comment by zastrixarundell** [comment]
Sorry, did you find out how to do it via flags in ENV?

**Comment by guihkx** [comment]
I'll add the ability to do this through config file, which is a bit better than environment variables because we'll be able to add comments to the file explaining the reason for each flag.

If have any input, feel free to share it on issue #402.
