### ISSUE TITLE
Discord keep crashing

### ISSUE THREAD

**Issue by Faqterson** [flathub/com.discordapp.Discord#394]
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20402]: Warning: vkCreateInstance: Found no drivers!
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20402]: Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20402]:     at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:101)
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20402]:     at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:493)
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20402]:     at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:379)
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20402]:     at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:301)
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20402]:     at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:556)
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20402]: Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 487: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20343]: [5:0427/110239.366365:ERROR:gpu_process_host.cc(993)] GPU process exited unexpectedly: exit_code=32512
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20343]: (electron) 'gpu-process-crashed event' is deprecated and will be removed. Please use 'child-process-gone event' instead.
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20343]: child-process-gone! child: GPU (undefined) exitCode: 32512
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20343]: blackbox: 2024-04-27T09:02:39.373Z 11 ❌ child-process-gone {
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20343]:   type: 'GPU',
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20343]:   reason: 'abnormal-exit',
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20343]:   exitCode: 32512,
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20343]:   serviceName: 'GPU'
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20343]: }
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20343]: notificationScreen.webContentsSend: win is invalid undefined.
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20343]: blackbox: 2024-04-27T09:02:39.382Z 12 before-quit
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20343]: blackbox: 2024-04-27T09:02:39.387Z 13 window.close win2
Apr 27 11:02:39 faqterson-pc com.discordapp.Discord.desktop[20343]: blackbox: 2024-04-27T09:02:39.542Z 14 webContents.destroyed web2
Apr 27 11:02:40 faqterson-pc com.discordapp.Discord.desktop[20341]: 2024/04/27 11:02:40 socat[3] W exiting on signal 15

Intel® Core™ i7-9700K CPU @ 3.60GHz × 8 
NVIDIA Corporation TU102 [GeForce RTX 2080 Ti Rev. A]
Pop!_OS 22.04 LTS

**Comment by dlarue** [comment]
0.0.58 also exits with error 32512

----------------------------------------------
CDM work timed out
blackbox: 2024-07-01T13:37:27.338Z 1 Discord starting: {"releaseChannel":"stable","version":"0.0.58"}, modulepath: /home/dlarue/.config/discord/0.0.58/modules
blackbox: 2024-07-01T13:37:27.376Z 2 ✅ webContents.created web1 ""
blackbox: 2024-07-01T13:37:27.379Z 3 ✅ window.created win1 "discord"
splashScreen: SPLASH_SCREEN_READY
splashScreen.webContentsSend: SPLASH_SCREEN_QUOTE SPLASH_SCREEN_QUOTE [ 'Hold Tight — Loading Discord' ]
2024-07-01T13:37:27.635Z [Modules] No updates to install
splashScreen: no-pending-updates
2024-07-01T13:37:27.636Z [Modules] Checking for host updates.
splashScreen: checking-for-updates
splashScreen.updateSplashState checking-for-updates checking-for-updates {}
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'checking-for-updates' } ]
blackbox: 2024-07-01T13:37:27.801Z 4 ✅ webContents.did-finish-load web1
2024-07-01T13:37:27.820Z [Modules] Host is up to date.
2024-07-01T13:37:27.820Z [Modules] Checking for module updates at https://discord.com/api/modules/stable/versions.json
2024-07-01T13:37:27.862Z [Modules] No module updates available.
splashScreen: update-check-finished true 0 false
CDM completed with status (old updater): undefined
splashScreen.launchMainWindow: false
Optional module ./ElectronTestRpc was not included.
splashScreen.updateSplashState launching launching {}
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'launching' } ]
blackbox: 2024-07-01T13:37:27.974Z 5 ✅ webContents.created web2 ""
blackbox: 2024-07-01T13:37:27.986Z 6 ✅ window.created win2 "Discord"
[WebContents] crashed (reason: abnormal-exit, exitCode: 32512)... reloading
Optional module ./ElectronTestRpc was not included.
blackbox: 2024-07-01T13:37:29.474Z 7 ❌ render-process-gone { reason: 'abnormal-exit', exitCode: 32512 }
blackbox: 2024-07-01T13:37:29.544Z 8 window.closed win2
blackbox: 2024-07-01T13:37:29.553Z 9 ✅ webContents.created web3 ""
blackbox: 2024-07-01T13:37:29.558Z 10 ✅ window.created win3 "Discord"
blackbox: 2024-07-01T13:37:29.566Z 11 webContents.destroyed web2
[WebContents] double crashed (reason: abnormal-exit, exitCode: 32512)... RIP =(
notificationScreen.webContentsSend: win is invalid undefined.
blackbox: 2024-07-01T13:37:30.687Z 12 ❌ render-process-gone { reason: 'abnormal-exit', exitCode: 32512 }
blackbox: 2024-07-01T13:37:30.727Z 13 before-quit

**Comment by FlailoftheLord** [comment]
Same Issue with 0.65 (latest release as of August 23rd 2024)

```
----------------------------------------------
CDM completed with status: cdm-ready-success
blackbox: 2024-08-23T14:06:03.460Z 1 Discord starting: {"releaseChannel":"stable","version":"0.0.65"}, modulepath: /home/flail/.var/app/com.discordapp.Discord/config/discord/0.0.65/modules
blackbox: 2024-08-23T14:06:03.463Z 2 ✅ webContents.created web1 "index.html"
blackbox: 2024-08-23T14:06:03.467Z 3 ✅ window.created win1 "discord"
splashScreen: SPLASH_SCREEN_READY
splashScreen.webContentsSend: SPLASH_SCREEN_QUOTE SPLASH_SCREEN_QUOTE [ 'Hold Tight — Loading Discord' ]
2024-08-23T14:06:03.526Z [Modules] No updates to install
splashScreen: no-pending-updates
2024-08-23T14:06:03.526Z [Modules] Host is up to date.
2024-08-23T14:06:03.527Z [Modules] Checking for module updates at https://discord.com/api/modules/stable/versions.json
splashScreen: checking-for-updates
splashScreen.updateSplashState checking-for-updates checking-for-updates {}
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'checking-for-updates' } ]
blackbox: 2024-08-23T14:06:03.660Z 4 ✅ webContents.did-finish-load web1
2024-08-23T14:06:03.724Z [Modules] No module updates available.
splashScreen: update-check-finished true 0 false
splashScreen.launchMainWindow: false
[5:0823/100603.756902:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[5:0823/100603.756932:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[5:0823/100603.756950:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Optional module ./ElectronTestRpc was not included.
splashScreen.updateSplashState launching launching {}
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'launching' } ]
blackbox: 2024-08-23T14:06:03.813Z 5 ✅ webContents.created web2 ""
blackbox: 2024-08-23T14:06:03.816Z 6 ✅ window.created win2 "Discord"
[WebContents] crashed (reason: crashed, exitCode: 139)... reloading
Optional module ./ElectronTestRpc was not included.
blackbox: 2024-08-23T14:06:05.341Z 7 ❌ render-process-gone { reason: 'crashed', exitCode: 139 }
blackbox: 2024-08-23T14:06:05.346Z 8 window.closed win2
blackbox: 2024-08-23T14:06:05.352Z 9 ✅ webContents.created web3 ""
blackbox: 2024-08-23T14:06:05.355Z 10 ✅ window.created win3 "Discord"
blackbox: 2024-08-23T14:06:05.358Z 11 webContents.destroyed web2
[WebContents] double crashed (reason: crashed, exitCode: 139)... RIP =(
notificationScreen.webContentsSend: win is invalid undefined.
blackbox: 2024-08-23T14:06:06.769Z 12 ❌ render-process-gone { reason: 'crashed', exitCode: 139 }
blackbox: 2024-08-23T14:06:06.776Z 13 before-quit
2024/08/23 10:06:06 socat[3] W exiting on signal 15                                                                     
```

Linux 6.10.5-arch1-1
KDE plasma on wayland.

**Comment by guihkx** [comment]
>This is NOT using flathub's release but it may be valuable as it is pretty much the same error.

Thank you for that information.

This tells us that these crashes are not specific to the Flatpak package, which is what this issue tracker is really for.

My usual recommendation is to report these issues to the [appropriate channel](https://support.discord.com/hc/en-us/articles/1500006052822-How-to-Report-a-Bug) instead.

**Comment by dlarue** [comment]
[quote] My usual recommendation is to report these issues to the [appropriate channel](https://support.discord.com/hc/en-us/articles/1500006052822-How-to-Report-a-Bug) instead. [/quote]

I was going to write "Chicken or the Egg" thinking we needed to use the discord app to post the bug report. We don't so I posted using that link. Thanks for pointing that out.

**Comment by guihkx** [comment]
No problem!

Despite this package having the "verified" badge on Flathub, my suspicion is that no one from the Discord team actually goes through any of the reported issues we have here.

So it's more likely to get them fixed if we use their own bug report form instead...

For that reason, I'll close this one. Thank you for understanding.
