### ISSUE TITLE
Screen share not working (keeps asking for screen/window to share) on Fedora KDE Spin

### ISSUE THREAD

**Issue by atirut-w** [flathub/com.discordapp.Discord#399]

**Comment by TheFattestCatProg** [comment]
Same problem on PopOs 22.04 with Gnome 42.9

**Comment by E3FxGaming** [comment]
Potential duplicate of #380

**Comment by DUB1401** [comment]
Also have this problem on Fedora Silverblue 40.

**Comment by TheBlackmeister** [comment]
Discord version 0.0.55 still not fixed, Fedora 40 Workstation, Gnome 46. The Discord app is repeatedly asking the system to select screen share or app share.

**Comment by Zachs-Kappler** [comment]
Happens to me on Fedora Workstation 40, but only on Wayland sessions like GNOME 46.3 and not a legacy session like Cinnamon.

**Comment by felipetomm** [comment]
> Happens to me on Fedora Workstation 40, but only on Wayland sessions like GNOME and not a legacy session like Cinnamon.
> 
> Gnome 46.3.1 Cinnamon 6.2.7

Same here @Zachs-Kappler . After I change from Wayland to legacy, the problem disappears.
I did it in Fedora Workstation 40 and Ubuntu 24.04

**Comment by guihkx** [comment]
Closing as duplicate of https://github.com/flathub/com.discordapp.Discord/issues/380.
