### ISSUE TITLE
Discord fails to start due to the available update

### ISSUE THREAD

**Issue by kostich** [flathub/com.discordapp.Discord#40]
Seems that the 0.0.6 version has been released but you can't update to it through Flathub (yet).

![2019-01-15 18-19-39](https://user-images.githubusercontent.com/4953862/51197611-5775c900-18f2-11e9-8859-840017eb5553.png)

**Comment by Preisschild** [comment]
Use this `flatpak install --user http://repo-test.flathub.org:8080/build-repo/1197/com.discordapp.Discord.flatpakref` while the maintainer is not here to accept the PR.

**Comment by kostich** [comment]
@Preisschild, ok seems that you just bumped the version and changed the url path for the tar-ball on the Discord site. Nothing malicious. :smile: 

Thanks!

I'll wait a bit longer for it to get merged.

**Comment by Preisschild** [comment]
Well, it seems like it still works with the old dependencies, so not much changing required.

**Comment by kostich** [comment]
I'm not that informed about the pipeline from GitHub to Flathub. How long does it usually take for the update to be available on FlatHub @TingPing?

**Comment by beheh** [comment]
It appears they immediately released 0.0.7?

![0.0.7](https://user-images.githubusercontent.com/929769/51206243-eb9e5b00-1907-11e9-949d-3a064b818d91.png)

**Comment by kostich** [comment]
@beheh, I've opened [another issue](https://github.com/flathub/com.discordapp.Discord/issues/42).
