### ISSUE TITLE
Dragging files not working

### ISSUE THREAD

**Issue by Cobriss** [flathub/com.discordapp.Discord#408]
Unable to drag files from Files application into Discord. Met with error and it fails to upload when I try, however using the + icon to upload photos manually works perfectly fine. I will be attaching screenshots of the errors, if their is any further information required, I will do my best to submit it.
![Screenshot from 2024-06-20 17-12-26](https://github.com/flathub/com.discordapp.Discord/assets/173421194/3d1be792-c03a-4503-ba8a-274bf36a3f9b)
![Screenshot from 2024-06-20 17-12-41](https://github.com/flathub/com.discordapp.Discord/assets/173421194/61bbddf1-61eb-4124-a66f-0ce820bd0c0e)

**Comment by MaledictYtb** [comment]
It's because discord doesn't have access to these files. By default it has only access to downloads, pictures and images. 
You can give discord access to your home directory using flatseal.

**Comment by guihkx** [comment]
Exactly what the MaledictYtb said above.

In other words, for drag-and-drop to work securely, Electron will have [to implement it first](https://github.com/electron/electron/issues/30650).

The "insecure" alternative is to allow Discord unrestricted access to your home folder, as explained by [this section](https://github.com/flathub/com.discordapp.Discord?tab=readme-ov-file#differences-in-flatpak-version) of our README page.
