### ISSUE TITLE
login with security key fails

### ISSUE THREAD

**Issue by xi** [flathub/com.discordapp.Discord#418]
During authentication, when I click on "Authenticate with security key", discord immediately shows the error message "An error occurred. Please try again." Trying again of course has the identical result.

**Comment by guihkx** [comment]
Can you please check if this works with the non-Flatpak Discord package?

**Comment by ZVNexus** [comment]
@xi Can you try enabling the pcsc socket with Flatseal to test?

**Comment by guihkx** [comment]
Please note that security authentication can be a bit iffy at the moment:

https://github.com/flathub/com.discordapp.Discord/pull/470#issuecomment-2412991172

It also affects the official deb package, hence why I think this particular issue is solved.
