### ISSUE TITLE
DiscordProcessObserver: Skipping '' log spam

### ISSUE THREAD

**Issue by doums** [flathub/com.discordapp.Discord#423]
Hi, not sure if this can be addressed at the flatpak package level, but since a recent update the app is spaming this message in the logs pretty aggresively, like ~2 messages/sec

```
Discord - Messaging, voice and video client

          ID: com.discordapp.Discord
         Ref: app/com.discordapp.Discord/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.0.64
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 273.9 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: 466270714da0b6e2595b6e19e5800964b8d5592107ab58a8a554b90876a92f60
      Parent: b27bca8db1be97040ee18af5de942338b81281bcae86350b6274ccfccb82a548
     Subject: discord: Update discord-0.0.63.tar.gz to 0.0.64 (2ba93b0b)
        Date: 2024-08-13 18:37:33 +0000
```

os

```
Arch 6.10.3-arch1-2
```

**Comment by keyboardsquid** [comment]
Found this issue searching for the same logspam. 

`flatpak info com.discordapp.Discord

Discord - Messaging, voice and video client

          ID: com.discordapp.Discord
         Ref: app/com.discordapp.Discord/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.0.67
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 273.9 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: d5013e6110cfc84e3653551c0039923d13317c0111cce3c8f194245f16aa60c9
      Parent: 5ce335709d428a2befb768f5b66350f7b7d7c64c541e9b317ccfd605bf6eb5a5
     Subject: discord: Update discord-0.0.66.tar.gz to 0.0.67 (2bbcf90f)
        Date: 2024-09-04 18:46:58 +0000`

I leave discord open all day, and the volume of log messages is causing my Logrotate to kick in more than I would like. 

Makes /var/log/messages almost useless for historic review.

**Comment by guihkx** [comment]
I don't see such message in my Discord logs... Can any of you check if this is still an issue?

And if is, please provide clear reproduction steps, if possible.

**Comment by andrewd18** [comment]
> I don't see such message in my Discord logs... Can any of you check if this is still an issue?
> 
> And if is, please provide clear reproduction steps, if possible.

### Reproduction steps:
1. In a terminal, run `journalctl --follow`.
2. Start Discord.
3. Watch the terminal.

```
Sep 18 11:21:23 Phobetor flatpak[17996]: DiscordProcessObserver: Skipping ''
Sep 18 11:21:23 Phobetor flatpak[17996]: DiscordProcessObserver: Skipping ''
Sep 18 11:21:23 Phobetor flatpak[17996]: DiscordProcessObserver: Skipping ''
Sep 18 11:21:23 Phobetor flatpak[17996]: DiscordProcessObserver: Skipping ''
Sep 18 11:21:23 Phobetor flatpak[17996]: DiscordProcessObserver: Skipping ''
Sep 18 11:21:23 Phobetor flatpak[17996]: DiscordProcessObserver: Skipping ''
Sep 18 11:21:23 Phobetor flatpak[17996]: DiscordProcessObserver: Skipping ''
Sep 18 11:21:23 Phobetor flatpak[17996]: DiscordProcessObserver: Skipping ''
Sep 18 11:21:23 Phobetor flatpak[17996]: DiscordProcessObserver: Skipping ''
Sep 18 11:21:23 Phobetor flatpak[17996]: DiscordProcessObserver: Skipping ''
Sep 18 11:21:23 Phobetor flatpak[17996]: DiscordProcessObserver: Skipping ''
Sep 18 11:21:23 Phobetor flatpak[17996]: DiscordProcessObserver: Skipping ''
Sep 18 11:21:23 Phobetor flatpak[17996]: DiscordProcessObserver: Skipping ''
Sep 18 11:21:23 Phobetor flatpak[17996]: DiscordProcessObserver: Skipping ''
Sep 18 11:21:23 Phobetor flatpak[17996]: DiscordProcessObserver: Skipping ''
Sep 18 11:21:23 Phobetor flatpak[17996]: DiscordProcessObserver: Skipping ''
Sep 18 11:21:23 Phobetor flatpak[17996]: DiscordProcessObserver: Skipping ''
Sep 18 11:21:23 Phobetor flatpak[17996]: DiscordProcessObserver: Skipping ''
Sep 18 11:21:23 Phobetor flatpak[17996]: DiscordProcessObserver: Skipping ''
Sep 18 11:21:23 Phobetor flatpak[17996]: DiscordProcessObserver: Skipping ''
```

### System info
```
andrew@Phobetor:~$ inxi -S
System:
  Host: Phobetor Kernel: 6.10.6-200.amd.fc40.x86_64 arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 6.1.4 Distro: Fedora Linux 40 (KDE Plasma)
```

### Flatpak version info
```
andrew@Phobetor:~$ flatpak info com.discordapp.Discord

Discord - Messaging, voice and video client

          ID: com.discordapp.Discord
         Ref: app/com.discordapp.Discord/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.0.68
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 273.9 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: 01d68d8277a10b98615e1c6efe1b51a4336e1c057c748b876045c5055b9444e1
      Parent: 279ad962066e4f0d04dc185cdb2e0d8c9fbaf36d82ffd9beefbdf80c74ab2a23
     Subject: discord: Update discord-0.0.68.tar.gz to 0.0.68 (f2a8b688)
        Date: 2024-09-18 10:33:27 +0000
```

**Comment by guihkx** [comment]
Thank you, @andrewd18.

Does the message appear for you as soon as you open Discord? I hasn't popped up for me here yet, but I'll keep Discord running for a few hours and see what happens.

**Comment by andrewd18** [comment]
It is immediate and is spammed about once per 5 seconds when the
application is open, or once per second if I am in a voice channel.

**Comment by guihkx** [comment]
Yeah, unfortunately I do not see such message here, even after a clean Discord install...

If I had to guess, it could be tied to a specific option being enabled or disabled in Discord.

I'll keep looking.

**Comment by guihkx** [comment]
Okay, I'm able to see them by launching Discord from KDE's app launcher.

Previously, I was just launching Discord using `flatpak run` from a terminal window. And no, that message didn't show up in the terminal.

I guess the next logical step is try to understand why launching from the terminal suppresses those messages.

**Comment by guihkx** [comment]
Unfortunately, that message comes from this binary Node module used by Discord: `~/.var/app/com.discordapp.Discord/config/discord/*/modules/discord_utils/discord_utils.node`.

The message seems to be printed unconditionally to `stdout`, unless a terminal ("tty") is detected.

Fortunately, by creating a custom desktop file for Discord, we can suppress all those messages by wrapping Discord's launch script over the [`script` tool](https://www.man7.org/linux/man-pages/man1/script.1.html):

```desktop
# Save this file to ~/.local/share/applications/com.discordapp.Discord.desktop
[Desktop Entry]
Name=Discord
StartupWMClass=discord
Comment=All-in-one voice and text chat for gamers thats free, secure, and works on both your desktop and phone.
GenericName=Internet Messenger
Exec=/usr/bin/flatpak run --command=script com.discordapp.Discord -efqc com.discordapp.Discord /dev/null
Icon=com.discordapp.Discord
Type=Application
Categories=Network;InstantMessaging;
MimeType=x-scheme-handler/discord;
```

So, since this is not a Flatpak-specific issue, i.e. it also happens with the official Discord package, I think users interested in getting this issue properly "fixed", should use the [appropriate channel](https://support.discord.com/hc/en-us/articles/1500006052822-How-to-Report-a-Bug).

**Comment by kosimas** [comment]
From the Arch [wiki()](https://wiki.archlinux.org/title/Discord#Discord_spams_systemd_journal):
To disable the logging that causes this pollution: go to User Settings, select "Voice & Video", scroll to bottom of the screen and disable "Debug Logging". 

This also fixed it for me.

**Comment by guihkx** [comment]
Just an update to this: The workaround above shouldn't be necessary anymore if you're running Discord version 0.0.91 (released in 2025-04-15) or newer, because Discord devs finally removed that spammy message! So feel free to remove that `.desktop` file.

I verified this by downloading the `discord_utils.node` file for version 0.0.90 and 0.0.91, and with a combination of commands, I observed that the `DiscordProcessObserver: Skipping ''` message is not present anymore in the 0.0.91 binary:

### 0.0.90 (message is still present)

```sh
$ curl -sL https://stable.dl2.discordapp.net/apps/linux/0.0.90/modules/discord_utils-1.zip |
  bsdtar -xOf- discord_utils.node |
  strings |
  grep -F Skipping
DiscordProcessObserver: Skipping '%s'
```

### 0.0.91 (message is gone)

```sh
$ curl -sL https://stable.dl2.discordapp.net/apps/linux/0.0.91/modules/discord_utils-1.zip |
  bsdtar -xOf- discord_utils.node |
  strings |
  grep -F Skipping
```
