### ISSUE TITLE
Spotify Listen Along

### ISSUE THREAD

**Issue by JAD3N** [flathub/com.discordapp.Discord#447]
Is it possible to get the Spotify listen along feature to work with the Flatpak version of Discord and Spotify?

**Comment by guihkx** [comment]
It works just fine here. What's exactly the problem you're having?

**Comment by JAD3N** [comment]
I have Spotify and Discord install via Flatpak. When I click the listen along, the button appears not do anything. I've tried this multiple times but no luck. Any ideas? Could it be a problem with having Spotify installed via Flatpak as well?

**Comment by guihkx** [comment]
>Could it be a problem with having Spotify installed via Flatpak as well?

Well, I also have both of them installed as Flatpak, and it works fine here:

https://github.com/user-attachments/assets/ad39218d-52cc-42da-905b-e862a2790b3a

Maybe try disconnecting/connecting your Spotify account to Discord?

**Comment by JAD3N** [comment]
@guihkx Yea, I reconnected my Spotify account and it seems to be working now (no idea what changed). Thanks for the help!
