### ISSUE TITLE
They just released 0.0.8 (??)

### ISSUE THREAD

**Issue by kirbyfan64** [flathub/com.discordapp.Discord#45]
I don't even know what the hell is going on at this point.

**Comment by beheh** [comment]
![0.0.8](https://user-images.githubusercontent.com/929769/51220318-0fc46100-1935-11e9-9737-4dbb8e290bf3.png)
Same here!

**Comment by fanfan54** [comment]
![image](https://user-images.githubusercontent.com/11705441/51239361-78cdc800-1979-11e9-9c8b-30b46be284c9.png)

Hi,
Sorry for asking again how to do that but I still don't understand how to run the test build.
As you can see, flatpak keeps saying that app/com.discordapp.Discord/x86_64/stable is not installed
I'm on Fedora 28 and I have Flatpak 1.0.6

**Comment by beheh** [comment]
@fanfan54 Just to follow up with your issues: You can either install flatpaks user-local, or system wide. User-local requires the --user flag but no special permissions, and system-wide is the default and would require you to have the appropriate permissions or prefix the command with `sudo`. As you ran the install both with `sudo` and `--user`, you've effectively installed the flatpak user-local to root, which menas you would only be able to execute it as root (note the final column of the first row in `sudo flatpak list` ). I suggest running `flatpak install` only with one of `sudo` or `--user`.

**Comment by 9034725985** [comment]
same here 

![screenshot from 2019-01-16 16-11-40](https://user-images.githubusercontent.com/1676445/51278901-d67a0880-19a9-11e9-9b6e-954ad484d2ef.png)
