### ISSUE TITLE
Discord error when alt + tab

### ISSUE THREAD

**Issue by Heryhelder** [flathub/com.discordapp.Discord#48]
Everytime when i alt + tab from discord to another app and go back to discord it shows me an error message.

I'm using Fedora 29 and flatpak version is 0.0.8

![screenshot_20190116_202949](https://user-images.githubusercontent.com/8170891/51285565-0f2bd900-19ce-11e9-8e52-39351fb777a4.png)

**Comment by Heryhelder** [comment]
I'm still having messages notifications and can listen/speak in call even with this error message on screen

**Comment by LeandroStanger** [comment]
@nedrichards I am having the same error in Endless OS
```
Gtk-Message: 08:43:19.982: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:43:19.982: Failed to load module "canberra-gtk-module"
Discord 0.0.8
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: /sysroot/home/leandro/.var/app/com.discordapp.Discord/config/discord/0.0.8/modules
[Modules] Module installed file path: /sysroot/home/leandro/.var/app/com.discordapp.Discord/config/discord/0.0.8/modules/installed.json
[Modules] Module download path: /sysroot/home/leandro/.var/app/com.discordapp.Discord/config/discord/0.0.8/modules/pending
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/stable/versions.json
[Modules] No module updates available.
Feature redeclared; is this a duplicate flag?  voice_panning
Feature redeclared; is this a duplicate flag?  voice_multiple_connections
Feature redeclared; is this a duplicate flag?  media_devices
Feature redeclared; is this a duplicate flag?  media_video
Feature redeclared; is this a duplicate flag?  debug_logging
Feature redeclared; is this a duplicate flag?  set_audio_device_by_id
Feature redeclared; is this a duplicate flag?  loopback

(discord:5): Gdk-WARNING **: 08:44:11.881: Can't set ParentRelative background for window 0x3800027, depth of parent doesn't match

(discord:5): Gdk-WARNING **: 08:44:14.261: Can't set ParentRelative background for window 0x380000c, depth of parent doesn't match

```

**Comment by glaubersm** [comment]
on my system discord shows the same error when I receive a notification.
My system is Arch Linux running gnome 3.30.2 and flatpak 1.1.3.

**Comment by Heryhelder** [comment]
i'm having no problems after last update.

Ref: app/com.discordapp.Discord/x86_64/stable
ID: com.discordapp.Discord
Arq.: x86_64
Ramo: stable
Origem: flathub
ID de coleção: org.flathub.Stable
Data: 2019-01-17 02:38:18 +0000
Assunto: Update base app to Electron2 (ba0c3ba7)
Commit: fa97741601c4a3c9cbc55bed8ddb110a79d33e70e40b3327f045889899e68c35
Pai: c1d08d15d4042f76203ab977dfeaa7dbdff76a245e5d512fdd36a80c46bd0a38
Localização: /var/lib/flatpak/app/com.discordapp.Discord/x86_64/stable/fa97741601c4a3c9cbc55bed8ddb110a79d33e70e40b3327f045889899e68c35
Tamanho instalado: 3,2 MB
Runtime: org.freedesktop.Platform/x86_64/18.08
Sdk: org.freedesktop.Sdk/x86_64/18.08

Can you guys confirm if this issue is resolved?

**Comment by Progman-DT** [comment]
I got the same error when I tried to go to Change log in the options. Since then discord has been throwing this error immediately after launch.

**Comment by glaubersm** [comment]
@Progman-DT  Same thing here.
Arch Linux, flatpak 1.1.3.

**Comment by Heryhelder** [comment]
Same here @Progman-DT

**Comment by MischievousTomato** [comment]
I have this error as well.

**Comment by FastOSlinux** [comment]
Same..

**Comment by Xunjin** [comment]
it seems to be a problem trying to loading some modules here is what i got from terminal running:
$ flatpak run com.discordapp.Discord
`2019/01/20 12:01:49 socat[3] E "/run/user/1000/discord/ipc-0" exists
Gtk-Message: 12:01:49.807: Failed to load module "pk-gtk-module"
Gtk-Message: 12:01:49.807: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:01:49.807: Failed to load module "pk-gtk-module"
Gtk-Message: 12:01:49.807: Failed to load module "canberra-gtk-module"
Discord 0.0.8
Starting updater.
/app/bin/discord: line 8: kill: (3) - No such process`

**Comment by Xunjin** [comment]
Here is some output:
```$ flatpak run com.discordapp.Discord
Gtk-Message: 12:08:27.093: Failed to load module "pk-gtk-module"
Gtk-Message: 12:08:27.093: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:08:27.093: Failed to load module "pk-gtk-module"
Gtk-Message: 12:08:27.093: Failed to load module "canberra-gtk-module"
Discord 0.0.8
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: /home/xunjin/.var/app/com.discordapp.Discord/config/discord/0.0.8/modules
[Modules] Module installed file path: /home/xunjin/.var/app/com.discordapp.Discord/config/discord/0.0.8/modules/installed.json
[Modules] Module download path: /home/xunjin/.var/app/com.discordapp.Discord/config/discord/0.0.8/modules/pending
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/stable/versions.json
[Modules] No module updates available.
```

**Comment by FastOSlinux** [comment]
snap/.rpm(rpmfusion) versions works

**Comment by FastOSlinux** [comment]
flatpak override --user --env=TZ=America/New_York com.discordapp.Discord works for me

**Comment by Heryhelder** [comment]
When i try flatpak override --user --env=TZ=America/New_York com.discordapp.Discord nothing happens. Discord is not even starting.

**Comment by Heryhelder** [comment]
Sorry, missclicked and closed this issue

**Comment by TingPing** [comment]
Well it should probably be reported against flatpak/flatpak if it hasn't already.

**Comment by glaubersm** [comment]
Problem persists on Arch Linux after update to discord 0.0.9.

**Comment by arifur** [comment]
Work around fixed the crashes for me.

**Comment by eiglow** [comment]
Pretty sure this is the same issue as #53, which has been fixed.

**Comment by lionirdeadman** [comment]
Will close, feel free to reopen.
