### ISSUE TITLE
When using the VS Code Remote, the status is not displayed correctly (it works properly when I play League of Legends).

### ISSUE THREAD

**Issue by 2eppeli** [flathub/com.discordapp.Discord#481]
title

**Comment by guihkx** [comment]
Is VSCode installed as non-Flatpak? If so, did you [set it up accordingly](https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-\(discord-rpc\)#unsandboxed-applications)?

**Comment by guihkx** [comment]
Closing due to lack of response.
