### ISSUE TITLE
Adding flathub as a Linux option on discords website

### ISSUE THREAD

**Issue by polluxau** [flathub/com.discordapp.Discord#485]
Often times a new Linux user will go onto the web to grab their applications and so going to discords website to find out that .Deb is not a supported package for them as they are running something that isn't based on debian and they don't want to download the tar as you have to run in manually 

Adding flathub as a option directs them to the flathub store and so there won't be any issues as Flatpak is supported across all major Distros 

![Screenshot_20241213-042532](https://github.com/user-attachments/assets/462b58f4-0e22-42b0-9551-d502842ce913)

I know you probably can't do anything about it but if you can send it to the right people so this can happen id appreciate it :>

**Comment by guihkx** [comment]
It looks like someone has already made this request on Discord's Feedback Forum:

https://support.discord.com/hc/en-us/community/posts/22823790788119-Add-Flathub-Flatpak-as-desktop-application-download-option-for-Linux

I suggest either upvoting the request or leaving a comment there, so it hopefully gains traction.

Other than that, we unfortunately can't do much about it...
