### ISSUE TITLE
Discord is stuck at just a blank screen

### ISSUE THREAD

**Issue by acz13** [flathub/com.discordapp.Discord#5]
`Linux MyPC 4.9.56-1-lts #1 SMP Thu Oct 12 22:34:15 CEST 2017 x86_64 GNU/Linux`

Arch Linux...

![2017-10-20-170717_1366x768_scrot](https://user-images.githubusercontent.com/8976828/31841806-29d98196-b5b9-11e7-980a-83517d312c3b.png)

**Comment by acz13** [comment]
So apparently my `PATH` is not set very well...

**Comment by jurf** [comment]
Is `discord` an alias? The proper way to launch the Flatpak version of Discord should be `flatpak run com.discordapp.Discord`.

**Comment by acz13** [comment]
`discord` should be a wrapper command in my `PATH`, but my other non-working previous installation of Discord was ahead of that in the `PATH` 😂
