### ISSUE TITLE
error while selecting groups in discord

### ISSUE THREAD

**Issue by FastOSlinux** [flathub/com.discordapp.Discord#51]
error while selecting groups in discord

Fedora 29 xfce

![captura de tela_2019-01-18_20-12-28](https://user-images.githubusercontent.com/17401812/51415671-c4d96200-1b5d-11e9-859c-95c7c8fff00d.png)

**Comment by Heryhelder** [comment]
seems related to #48

**Comment by TingPing** [comment]
These are both surely just Discord bugs, nothing this package can do about it.

**Comment by Heryhelder** [comment]
@TingPing maybe this can help in something?

[heryhelder@localhost ~]$ flatpak run --verbose com.discordapp.Discord
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening user flatpak installation at path /home/heryhelder/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/heryhelder/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/heryhelder/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 2992954312
F: Allocated instance id 1704683550
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/heryhelder/.config/pulse/client.conf': Erro ao abrir arquivo /home/heryhelder/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 34 /usr/libexec/flatpak-dbus-proxy --args=36'
F: Running 'bwrap --args 31 discord'
Discord 0.0.8
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: /home/heryhelder/.var/app/com.discordapp.Discord/config/discord/0.0.8/modules
[Modules] Module installed file path: /home/heryhelder/.var/app/com.discordapp.Discord/config/discord/0.0.8/modules/installed.json
[Modules] Module download path: /home/heryhelder/.var/app/com.discordapp.Discord/config/discord/0.0.8/modules/pending
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/stable/versions.json
[Modules] No module updates available.

"F: Pulseaudio user configuration file '/home/heryhelder/.config/pulse/client.conf': Erro ao abrir arquivo /home/heryhelder/.config/pulse/client.conf: No such file or directory" do you guys have this error as well?

**Comment by TingPing** [comment]
I wouldn't expect that pulse warning to cause these issues and otherwise it says nothing.

**Comment by Heryhelder** [comment]
i'm testing discord on snap and its running ok so far. Maybe is something wrong only in flatpak version?

**Comment by TingPing** [comment]
I mean literally every library is a different version so that doesn't necessarily narrow it down.

**Comment by FastOSlinux** [comment]
> No meu caso, o problema é ter definido a variável de ambiente timezone como ": / etc / localtime". Desmarcá-lo antes de executar a discórdia corrige todos os meus problemas (unset TZ, em seguida, flatpak executar com.discordapp.Discord). É semelhante ao que está acontecendo no pacote flatpak do Steam: https://github.com/flathub/com.valvesoftware.Steam/wiki/Frequently-asked-questions#im-having-incorrect-timezone-in-steam
> 
> ... então, fazer um override dessa variável de ambiente é suficiente, se é isso que está acontecendo com você. Naturalmente, o pacote flatpak deve tentar corrigir o problema em si, como o pacote flatpack do Steam. Pelo menos, avise o usuário sobre isso.

you're right flatpak override --user --env=TZ=America/New_York com.discordapp.Discord
 works

**Comment by lionirdeadman** [comment]
If the timezone workaround fixed it then the upstream bug (flatpak #3338) was fixed so it shouldn't happen again.
