### ISSUE TITLE
discord tells me about an update and doesnt start

### ISSUE THREAD

**Issue by fredoche** [flathub/com.discordapp.Discord#52]
Hi,
Recently, when I start discord, it tells me that theres an update (v0.0.8) , asks me to download either a deb or rpm or, if I select "I'll figure it out" , simply exits.
I dont know what to do, it used to work fine.
Thanks for your help packaging it.

**Comment by TingPing** [comment]
`flatpak update`

**Comment by fredoche** [comment]
I had hit the update button in fedora's gnome-software approximately a 100 times to no avail. Well, thanks for the tip!
