### ISSUE TITLE
No Microphone input possible.

### ISSUE THREAD

**Issue by Tids** [flathub/com.discordapp.Discord#54]
For a few days I'm not able anymore to get my Microphone working in discord flatpak.
I can set it as input in discord, so it will get recognized, but when I speak something in, there is no pulse in the settings and discord itself tells me that it does not hear me.

Other flatpaks like steam work just fine, also native distro packages. Discord was also working a week or 2 ago.

The same is on another PC with build in microphone.

Distros I use are arch Linux and Debian testing

Other than that, audio output works, webcam input also works.

**Comment by Heryhelder** [comment]
Same here on Fedora 29. Using built-in mic

**Comment by FastOSlinux** [comment]
disable supression noise in settings

**Comment by Preisschild** [comment]
Thanks, @FastOSlinux, that fixed it for me. I also tested it on the official rpm file and it has the same issue, so its discord related.

**Comment by eiglow** [comment]
For me, the microphone works fine both with and without noise suppression enabled.

**Comment by Tids** [comment]
@eiglow Thanks for the reminder. This is fixed for a long time :+1:
