### ISSUE TITLE
Discord 0.0.8 from .tar.gz launches with empty screen

### ISSUE THREAD

**Issue by stefan-reich** [flathub/com.discordapp.Discord#55]
This is on Peppermint Linux (64 bit).

```
stefan@stefan-quadcore ~/dev/Discord $ ./Discord
Discord 0.0.8
Starting updater.

```
After that, it just shows a blank window titled "Discord".

Also, the executable file ("Discord") did not have executable permissions after unpacking the archive.

Edit: Oh wait, is this the wrong place to report? I'm not using flatpak.

**Comment by stefan-reich** [comment]
I'm not sure where to put this report

**Comment by TingPing** [comment]
https://support.discordapp.com/hc/en-us/requests/new?ticket_form_id=360000029212

**Comment by stefan-reich** [comment]
OK, I thought there is maybe a Discord server for Discord server or something. Thanks for your help
