### ISSUE TITLE
Discord crashes on launch fedora

### ISSUE THREAD

**Issue by JanekKondzior** [flathub/com.discordapp.Discord#56]
flatpak run com.discordapp.Discord
Tried reinstalling but still crashes on launch . Have had this issue for a few months.

2019/02/24 01:59:49 socat[3] E "/run/user/1000/discord/ipc-0" exists
Gtk-Message: 01:59:49.543: Failed to load module "pk-gtk-module"
Gtk-Message: 01:59:49.543: Failed to load module "canberra-gtk-module"
Gtk-Message: 01:59:49.543: Failed to load module "pk-gtk-module"
Gtk-Message: 01:59:49.543: Failed to load module "canberra-gtk-module"
Discord 0.0.8
Starting updater.
/app/bin/discord: line 8: kill: (3) - No such process

**Comment by ricvelozo** [comment]
https://github.com/flathub/com.discordapp.Discord/issues/53#issuecomment-496020265

**Comment by eiglow** [comment]
If this is the same issue as #53, then this should also be closed.

**Comment by lionirdeadman** [comment]
If the timezone workaround fixed it then the upstream bug (flatpak #3338) was fixed so it shouldn't happen again.
