### ISSUE TITLE
Video Chat

### ISSUE THREAD

**Issue by katastrophal** [flathub/com.discordapp.Discord#6]
Discord has video chat functionality, but I think it is blocked by the sandbox. the Viber flatpak has
 "finish-args" [...
    "--device=all",
    ...]

maybe this is needed here as well?

**Comment by TingPing** [comment]
Can you test if `flatpak run --device=all com.discordapp.Discord` works? (I don't have the hardware to try)

**Comment by katastrophal** [comment]
yea. works.
