### ISSUE TITLE
Add canary in beta flathub

### ISSUE THREAD

**Issue by lionirdeadman** [flathub/com.discordapp.Discord#60]
I think that'd be appropriate.. :thinking:

**Comment by TingPing** [comment]
I'm not interested in maintaining a beta version.

**Comment by CorruptComputer** [comment]
I would like to second this, the stable Linux Discord app is updated to infrequently to be viable to use. It often gets features extremely late compared to even the stable Windows version. Adding Canary would be a great addition.

**Comment by TingPing** [comment]
I'm curious what features canary has atm that stable doesn't.

**Comment by Yamboy1** [comment]
I'd like this as well, I would also be willing to help maintain it

**Comment by Yamboy1** [comment]
> Discord's launcher refuses to start when its outdated and a version that I don't use that updates frequently is just not worth the effort.

It only updates the version maybe once every few weeks to a month, which is what triggers the out of date message, all the other updates just run when you start the app

**Comment by dr03m** [comment]
> I'm curious what features canary has atm that stable doesn't.

Some client mods such as Powercord require Canary.

**Comment by refi64** [comment]
Just for clarity, this exists now, as [`com.discordapp.DiscordCanary`](https://github.com/flathub/com.discordapp.DiscordCanary).
