### ISSUE TITLE
Update to new version required

### ISSUE THREAD

**Issue by keponk** [flathub/com.discordapp.Discord#66]
Discord app demading to download latest version.

**Comment by TingPing** [comment]
What version? Must be a delayed rollout as it works fine here.

**Comment by keponk** [comment]
It says "version 0.0.9 available"

**Comment by TingPing** [comment]
Which has been packaged for 2 months: https://github.com/flathub/com.discordapp.Discord/commit/30cac3bb17177b82a35ec2d63df12f203fc51087

Some bad state on your end.

**Comment by keponk** [comment]
@TingPing looks like you're right. I think it might running into this or similar (case someone else asks): https://gitlab.gnome.org/GNOME/gnome-software/issues/235 

I ran `flatpak update` from terminal and there it was the update. Thanks!
