### ISSUE TITLE
Installation error "The specified session has been invalidated for some reason"

### ISSUE THREAD

**Issue by aliasless** [flathub/com.discordapp.Discord#70]
Hi, I'm trying to install this flatpak on a fully patched Slackware 14.2 system. During the downloading step for "discord-0.0.9.tar.gz", it fails with the following error
``error: Failed to install com.discordapp.Discord/x86_64/stable: While downloading https://dl.discordapp.net/apps/linux/0.0.9/discord-0.0.9.tar.gz: Error writing data to TLS socket: The specified session has been invalidated for some reason.
``

Here is the full log with the -vv flag
https://gist.github.com/aliasless/ab3b064bc8d6ce99c67c91492e0113d7#file-gistfile1-txt

**Comment by lionirdeadman** [comment]
Now that I think about it, this shouldn't be an issue since we moved away from extra-data. Closing.
