### ISSUE TITLE
Discord crashes on launch manjaro

### ISSUE THREAD

**Issue by jcmljunior** [flathub/com.discordapp.Discord#71]
Gtk-Message: 18:51:27.196: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:51:27.197: Failed to load module "appmenu-gtk-module"
Discord 0.0.9
Starting app.
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: /home/julio/.var/app/com.discordapp.Discord/config/discord/0.0.9/modules
[Modules] Module installed file path: /home/julio/.var/app/com.discordapp.Discord/config/discord/0.0.9/modules/installed.json
[Modules] Module download path: /home/julio/.var/app/com.discordapp.Discord/config/discord/0.0.9/modules/pending
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/stable/versions.json
[Modules] No module updates available.

![Screenshot_20190611_184951](https://user-images.githubusercontent.com/35886100/59310045-90388500-8c7b-11e9-877a-d06e96653e6b.png)

**Comment by AlexKF98** [comment]
Also affects Ubuntu.

**Comment by jcmljunior** [comment]
Could you be a little more specific?
At the moment I'm using another version of Linux: KDE Neon
This same problem happens.

**Comment by ricvelozo** [comment]
https://github.com/flathub/com.discordapp.Discord/issues/53#issuecomment-496020265

**Comment by iglosiggio** [comment]
Hi (im going to repost this in all the duplicated issues). After digging a while seems caused by [this](https://bugs.chromium.org/p/chromium/issues/detail?id=364374) bug in chromium. Maybe updating the electron version will fix it?
