### ISSUE TITLE
Blank attachments from certain directories, and pin bugs

### ISSUE THREAD

**Issue by beskhu3epnm** [flathub/com.discordapp.Discord#77]
Two issues. Using Linux Mint 19.2. Installed through the Software Manager.

1) Attaching/uploading files doesn't allow from certain directories. Most Home directories are fine (like Pictures and Videos), but not the Desktop or any sub-directories in the Desktop.

2) Occasionally, clicking on a image, video, or link will pin it instead of opening/maximizing it.

Both of these issues are extremely annoying and I won't be using the flatpak version of Discord until they are resolved.

**Comment by TingPing** [comment]
> Attaching/uploading files doesn't allow from certain directories. Most Home directories are fine (like Pictures and Videos), but not the Desktop or any sub-directories in the Desktop.

`flatpak override --user com.discordapp.Discord --filesystem=xdg-desktop`

**Comment by TingPing** [comment]
> Occasionally, clicking on a image, video, or link will pin it instead of opening/maximizing it.

Sounds unrelated to the package?

**Comment by Vash63** [comment]
I can duplicate this. It's a common use case for me as I take screenshots with Steam (which saves to its own userdata directory in `~/.local/share/Steam` - when I drag and drop an image from my Steam screenshots it comes up with an empty white window. The same thing with a non-flatpak version of Discord works fine.

Running the above flatpak override command does not help.

**Comment by TingPing** [comment]
@Vash63 I already answered your question.

**Comment by beskhu3epnm** [comment]
@Vash63 Thanks for the help.

**Comment by Vash63** [comment]
So it's the intended functionality for users to have to run an override after installing the flatpak for it to function as it does on a native installation (or any other platform)?

**Comment by tannisroot** [comment]
@TingPing  I really feel like this should not have been closed.
Apps should not ship with broken basic functionality out of the box.

**Comment by Leopard1907** [comment]
If those flatpak solutions are not meant to work OOTB , what is the point of this futile effort? Basic user needs this and you're saying " nah, do this and do this " .

**Comment by TingPing** [comment]
Flatpak is a sandbox.

Discord is a proprietary application that it is nice to sandbox.

This is just how things are. If you want to extend Discords permissions you cant. There is nothing that can be done further.

**Comment by Vash63** [comment]
At very least I think there should be a message instructing people in the metadata that gnome-software shows that they need to run that command if they want it to work as they would expect from _every other platform_ where you can upload files by dragging and dropping them from anywhere. Or a GUI toggle somewhere in the installation interface, but that's probably beyond the scope of flathub.

**Comment by tannisroot** [comment]
> Discord is a proprietary application that it is nice to sandbox.
english please?

**Comment by tannisroot** [comment]
> Flatpak is a sandbox.

No, it's a platform for app distribution first, sandbox is just a nice addition.
But what is the point in the latter when it butchers core functionality of the application?
I know dozens of people who basically stopped using Flatpaked version and instead installed it from PPA/Snap/AUR because of this issue.

**Comment by TingPing** [comment]
@Vash63 This problem will go away naturally in a future Electron release: https://github.com/electron/electron/pull/19159

@tannisroot There is a security risk allowing a proprietary networked chat application to read all of a users files.

**Comment by tannisroot** [comment]
I imagine users who are concerned with security will probably not install a proprietary chatting app aimed at mostly gamers.

**Comment by TingPing** [comment]
The sandbox literally makes some Discord features impossible (tracking running games). So honestly any discussion about users using a different package to enable all features will never have an acceptable answer for some users. The file system permissions are solvable and will go away in a future update as I just linked.

**Comment by Vash63** [comment]
> @Vash63 This problem will go away naturally in a future Electron release: [electron/electron#19159](https://github.com/electron/electron/pull/19159)

This will fix drag and drop, not just picking with the chooser? I generally just drop the files onto the Discord client

**Comment by TingPing** [comment]
There is no solution for dnd atm.

**Comment by tristan957** [comment]
@Vash63 sorry about the PR. I need to spend some time setting up the Electron build environment, and that does not look easy! I then need to figure out a way to test my changes. I am also a GNOME user, so will require the help of a KDE/LXQt user. Also the PR has not seen too much attention from the Electron team, so for right now we wait.
