### ISSUE TITLE
Discord frequently forgets logon details and settings

### ISSUE THREAD

**Issue by einarjh** [flathub/com.discordapp.Discord#81]
It seems every time there's an update to Discord, it forgets my logon details and all the other settings I set within it (specifically I have to constantly disable the sound notification on chat messages).

Distro: Fedora 31

**Comment by HarryMichal** [comment]
@einarjh Does this still occur? I've been using the flatpak for a long time and this issue hasn't occured for quite some time.

**Comment by lionirdeadman** [comment]
Considering the issue maker didn't answer and I've not experienced this issue either for a long time (like HarryMichal). Closing.
