### ISSUE TITLE
Discord sandbox cannot access anything on my HDD

### ISSUE THREAD

**Issue by egee-irl** [flathub/com.discordapp.Discord#82]
I just tried updating my profile picture and noticed that Discord no longer has access to *anything* on my HDD.

Before, it had access to my Documents or Pictures folder and that was it. Now, it appears it cannot access anything.

![image](https://user-images.githubusercontent.com/6679968/70091323-bc044a00-15d0-11ea-8b68-200621bf97c7.png)

**Comment by TingPing** [comment]
What is the output of `flatpak info --show-permissions com.discordapp.Discord`

**Comment by egee-irl** [comment]
Its:

```
[Context]
shared=network;ipc;
sockets=x11;pulseaudio;
devices=all;
filesystems=xdg-videos:ro;xdg-download;xdg-pictures:ro;

[Session Bus Policy]
org.kde.StatusNotifierWatcher=talk
org.freedesktop.portal.Fcitx=talk
org.freedesktop.Notifications=talk

[Environment]
XDG_CURRENT_DESKTOP=Unity
```

**Comment by egee-irl** [comment]
The problem appears to stem from the fact that those folders listed in `filesystems` are symlinks. However, this was not an issue until recently; these folders have been symlinked for quite some time.

**Comment by TingPing** [comment]
You can do `xdg-user-dirs-update PICTURES /the/path/you/want` instead of relying on symlinks. If symlinks should work is an issue for `flatpak`.
