### ISSUE TITLE
Use dark GTK theme like the the Spotify flatpak

### ISSUE THREAD

**Issue by alexmex90** [flathub/com.discordapp.Discord#90]
Spotify on flatpak uses dark GTK theme which looks nicer than the default theme on GNOME. Perhaps the flatpak for Discord should do the same? any opinions? 

![Screenshot from 2020-03-27 08-06-05](https://user-images.githubusercontent.com/43529725/77770194-1d2dae80-7002-11ea-9d82-ad63eb51f061.png)

**Comment by TingPing** [comment]
The one complication is Discord has a light theme, unlike Spotify. Maybe that is stored in a config file we can read from... (I have little hope).

**Comment by alexmex90** [comment]
I think Spotify forces it, I went and gave a look on their repo and found [this](https://github.com/flathub/com.spotify.Client/blob/master/set-dark-theme-variant.py). Maybe it would be possible to implement something similar.

I know some Python, so if you need help to adjust it to Discord, I think I could help.

**Comment by Eskander** [comment]
> Maybe that is stored in a config file we can read from...

If I understood this statement correctly, you're looking for `settings.json` located in `~/.var/app/com.discordapp.Discord/config/discord/`
Discord sets the value of `BACKGROUND_COLOR` to

- `#ffffff` for light theme

- `#202225` for dark theme

**Comment by TingPing** [comment]
Cool. Now somebody just needs to write the script :grinning:

**Comment by lionirdeadman** [comment]
Isn't Discord kind of known for changing their CSS variables all the time to try to discourage people from theming the program? Has that changed? Although, I suppose if it breaks after an update, it's not that big of a deal.
