### ISSUE TITLE
Discord notifications do not open Discord

### ISSUE THREAD

**Issue by BjoernDaase** [flathub/com.discordapp.Discord#91]
* Fedora 32
* Gnome 3.36.1

When Discord is running in the background (the main window isn't visible but the tray icon is visible) and you get a notification from Discord, clicking on this notification does not open Discord (=unhiding the main window).

**Comment by TingPing** [comment]
What the notification does is handled by the application so there is nothing the package can do to change it (beyond more complex hacks).

**Comment by BjoernDaase** [comment]
Indeed, thanks.  
I somehow expected it to be a permission error due to the sandbox but it turns out also the manual installation of the `.tar.gz` does not open Discord when clicking on notifications. Closing.
