### ISSUE TITLE
Unstable without graphics card on video call

### ISSUE THREAD

**Issue by the-voidl** [flathub/com.discordapp.Discord#92]
I am using xfce4 and don't have a gpu in my laptop.

Every time I do a video call while doing some other expensive work on my laptop, discord becomes very unstable. By this I mean, the partners' videos begin to lag or the discord gui completely freezes.
`Expensive work` is playing a game or coding and debugging some crypto stuff.

Today the app freezed, so I tried to diable the others' videos. The app crashed and threw an exeption at me:
```
Uncaught exeption:
  TypeError: Cannot read property 'setMenuBarVisibility' of null
  at BrowserWindow.<anonymous> ([...]com.discordapp.Discord[....]/core.asar/app/mainScreen.js:469:16)
  at BrowserWindow.emit (events.js:203:13)
```

**Comment by TingPing** [comment]
I see no reason to believe this is an issue with this package.

**Comment by void-arch** [comment]
Ok sorry then. Could it be an issue with flatpak?

**Comment by TingPing** [comment]
Its surely just a Discord bug...
