### ISSUE TITLE
Problems launching on Chrome OS

### ISSUE THREAD

**Issue by ghost** [flathub/com.discordapp.Discord#95]
I'm trying to use the Discord on a Chrome OS device using the [Linux apps feature](https://chromium.googlesource.com/chromiumos/docs/+/master/containers_and_vms.md). I've had success with many desktop apps (from GIMP, to Firefox, to the JetBrains IDEs), but I can't get Discord to run properly.

When I launch Discord, I simply get a blank, black screen.

![Discord Black Screen](https://user-images.githubusercontent.com/66571193/84206159-2e6c5000-aa74-11ea-8c81-0d14d7e0f48a.png)

Here is what I see in my terminal if I launch Discord manually:

```bash
user@penguin:~$ flatpak run com.discordapp.Discord
Discord 0.0.10
Starting app.
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.10/modules
[Modules] Module installed file path: /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.10/modules/installed.json
[Modules] Module download path: /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.10/modules/pending
[27:0609/165533.155415:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/stable/versions.json
[Modules] No module updates available.
[27:0609/165533.915178:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[Modules] Starting to install discord_krisp...
[Modules] Fetching discord_krisp@0 from https://discordapp.com/api/modules/stable/discord_krisp/0
[Modules] Streaming discord_krisp@0 to /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.10/modules/pending/discord_krisp-0.zip
Error downloading with electron net: HTTP Error: Status Code 403
Falling back to node net library..
[Modules] Failed fetching module discord_krisp@0: Error: HTTP Error: Status Code 403
[Modules] Finished module downloads. [success: 0] [failure: 1]
```

**Comment by tabstospaces** [comment]
After searching the web, the only information I could find that might be promising is this Russian-language forum thread: https://www.linux.org.ru/forum/general/15662393

At the end of the thread, the original author states:

> "Оказывается, зачем-то нужно было установить сам пакет electron последней версии, и проблема с вылетом решилась сама собой"

Translated using Google Translate:

> "It turns out that for some reason it was necessary to install the electron package of the latest version itself, and the problem with the crash resolved by itself"

**Comment by mess-maker** [comment]
for information I have the same issue but different configuration

Win 10 host vmware player 16 VM (opensuse tumbleweed, fedora, manjaro, pop OS)
with all thoose guest I have the same issue of black screen with discord flatpak

No issue on all with the appimage
No issue with the binary install from packman on tumbleweed (didn't try on other ones vm)

NOTA 1 : I use many flatpak with no issue
NOTA2 : I have the same issue with joplin (seems to use electron also)

**Comment by guihkx** [comment]
Can someone with access to a ChromeOS please revisit this bug report?

It's a quite old issue at this point, so it's possible that it got fixed.

**Comment by guihkx** [comment]
Okay, I found [this YouTube video](https://youtu.be/upmAL-Bksbc?si=Yh3tYuukI5c6dmOf&t=310) of a person installing and running Flatpak'd Discord on a Chromebook with no obvious issues, so I'm going to close this one as completed.

Please open a new issue if the problem still exists.
